#!/usr/bin/env python3
"""Generate a source-grounded concept concordance across processed texts.

The concordance is an evidence-routing layer. It scans each processed chapter,
lecture, section, and report division for a curated concept vocabulary and
publishes source-linked pages showing where concepts appear. It does not decide
what a passage means; it shows where a researcher should read next.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import quote


BASE_URL = "/Charles-Proteus-Steinmetz-Texts-AI-Decoded"
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_concept_concordance.py. Do not edit by hand. */}"

CORE_CONCEPTS: dict[str, dict[str, Any]] = {
    "alternating-current": {
        "label": "Alternating Current",
        "aliases": ["alternating current", "alternating-current", "alternating currents", "a.c."],
    },
    "reactance": {
        "label": "Reactance",
        "aliases": ["reactance", "reactive", "inductive reactance", "condensive reactance"],
    },
    "impedance": {
        "label": "Impedance",
        "aliases": ["impedance", "impedances"],
    },
    "admittance": {
        "label": "Admittance",
        "aliases": ["admittance", "admittances"],
    },
    "susceptance": {
        "label": "Susceptance",
        "aliases": ["susceptance", "susceptances"],
    },
    "conductance": {
        "label": "Conductance",
        "aliases": ["conductance", "conductances"],
    },
    "hysteresis": {
        "label": "Hysteresis",
        "aliases": ["hysteresis", "magnetic lag", "molecular friction"],
    },
    "magnetic-permeability": {
        "label": "Magnetic Permeability",
        "aliases": ["permeability", "magnetic permeability"],
    },
    "dielectric-field": {
        "label": "Dielectric Field",
        "aliases": ["dielectric field", "dielectric", "dielectrics"],
    },
    "magnetic-field": {
        "label": "Magnetic Field",
        "aliases": ["magnetic field", "magnetic flux", "magnetic circuit", "field of magnetism"],
    },
    "electric-field": {
        "label": "Electric Field",
        "aliases": ["electric field", "electrostatic field", "field of force", "field of forces"],
    },
    "transient-phenomena": {
        "label": "Transient Phenomena",
        "aliases": ["transient", "transients", "transient phenomenon", "transient phenomena", "temporary term"],
    },
    "complex-quantities": {
        "label": "Complex Quantities",
        "aliases": ["complex quantity", "complex quantities", "imaginary quantity", "imaginary quantities"],
    },
    "symbolic-method": {
        "label": "Symbolic Method",
        "aliases": ["symbolic method", "symbolic representation", "symbolic expression", "symbolic"],
    },
    "power-factor": {
        "label": "Power Factor",
        "aliases": ["power factor", "power-factor", "wattless component", "wattless current"],
    },
    "resonance": {
        "label": "Resonance",
        "aliases": ["resonance", "resonant"],
    },
    "damping": {
        "label": "Damping",
        "aliases": ["damping", "decrement", "damped", "logarithmic decrement"],
    },
    "oscillation": {
        "label": "Oscillation",
        "aliases": ["oscillation", "oscillations", "oscillating", "oscillatory"],
    },
    "wave-propagation": {
        "label": "Wave Propagation",
        "aliases": ["wave propagation", "traveling wave", "travelling wave", "standing wave", "wave front"],
    },
    "distributed-constants": {
        "label": "Distributed Constants",
        "aliases": ["distributed constants", "distributed capacity", "distributed inductance"],
    },
    "electrostatic-capacity": {
        "label": "Electrostatic Capacity",
        "aliases": ["electrostatic capacity", "capacity", "condenser", "condensers", "capacitance"],
    },
    "inductance": {
        "label": "Inductance",
        "aliases": ["inductance", "self-inductance", "mutual inductance", "inductive"],
    },
    "counter-electromotive-force": {
        "label": "Counter-Electromotive Force",
        "aliases": ["counter electromotive force", "counter-electromotive force", "counter e.m.f.", "counter emf"],
    },
    "energy-storage-fields": {
        "label": "Energy Storage in Fields",
        "aliases": ["stored energy", "energy stored", "energy of the field", "stored in the field"],
    },
    "field-collapse": {
        "label": "Field Collapse",
        "aliases": ["collapse of the field", "collapsing field", "field collapse"],
    },
    "lightning-surges": {
        "label": "Lightning and Surges",
        "aliases": ["lightning", "surge", "surges", "impulse", "impulses", "arrester", "arresters"],
    },
    "electrical-radiation": {
        "label": "Electrical Radiation",
        "aliases": ["electrical radiation", "electric radiation", "radiant energy"],
    },
    "ether": {
        "label": "Ether",
        "aliases": ["ether", "aether"],
    },
    "field-stress": {
        "label": "Field Stress, Strain, Pressure, and Tension",
        "aliases": ["stress", "strain", "pressure", "tension", "elastic"],
    },
    "dielectricity": {
        "label": "Dielectricity",
        "aliases": ["dielectricity", "dielectric", "electrostatic", "displacement current", "displacement"],
    },
    "magnetism": {
        "label": "Magnetism",
        "aliases": ["magnetism", "magnetic", "magnetization", "magnetizing", "flux", "reluctance"],
    },
    "tesla-era-overlap": {
        "label": "Tesla-Era Overlap",
        "aliases": ["wireless", "high frequency", "hertzian", "oscillator", "high potential", "high tension"],
    },
    "radiation": {
        "label": "Radiation",
        "aliases": ["radiation", "radiations", "radiant energy"],
    },
    "light": {
        "label": "Light",
        "aliases": ["light", "visible light", "luminous"],
    },
    "illumination": {
        "label": "Illumination",
        "aliases": ["illumination", "illuminating", "illuminant", "illuminants", "candle-power", "candle power"],
    },
    "frequency": {
        "label": "Frequency",
        "aliases": ["frequency", "frequencies", "cycles per second", "periodicity"],
    },
    "wave-length": {
        "label": "Wave Length",
        "aliases": ["wave length", "wave-length", "wavelength", "wave lengths", "wave-lengths"],
    },
    "spectrum": {
        "label": "Spectrum",
        "aliases": ["spectrum", "spectra", "spectral"],
    },
    "ultraviolet": {
        "label": "Ultra-Violet Radiation",
        "aliases": ["ultra-violet", "ultraviolet", "actinic rays"],
    },
    "ultrared": {
        "label": "Ultra-Red Radiation",
        "aliases": ["ultra-red", "ultrared", "infra-red", "infrared"],
    },
    "x-rays": {
        "label": "X-Rays",
        "aliases": ["x-rays", "x rays", "x-ray"],
    },
    "synchronism": {
        "label": "Synchronism",
        "aliases": ["synchronism", "synchronous", "synchronizing", "synchronising"],
    },
    "power-limiting-reactor": {
        "label": "Power-Limiting Reactor",
        "aliases": ["power limiting reactor", "power-limiting reactor", "current limiting reactor", "reactor"],
    },
    "short-circuit": {
        "label": "Short Circuit",
        "aliases": ["short circuit", "short-circuit", "short circuits", "short-circuits"],
    },
    "arc-lamp": {
        "label": "Arc Lamp",
        "aliases": ["arc lamp", "arc lamps", "arc lighting", "arc light"],
    },
    "photometry": {
        "label": "Photometry",
        "aliases": ["photometry", "photometric", "photometer", "photometers"],
    },
}

CONCEPT_ID_OVERRIDES = {
    "permeability": "magnetic-permeability",
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "untitled"


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("$", "&#36;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def code_fence(text: str) -> str:
    text = text.rstrip() or "[No snippet captured.]"
    longest = 3
    for match in re.finditer(r"`+", text):
        longest = max(longest, len(match.group(0)) + 1)
    fence = "`" * longest
    return f"{fence}text wrap\n{text}\n{fence}"


def source_page_slug(record: dict[str, Any]) -> str:
    path = Path(str(record.get("text_path") or ""))
    if path.stem:
        return slugify(path.stem)
    return slugify(str(record.get("id") or record.get("title") or "section"))


def reader_focus_url(url: Any, query: Any = None, anchor: str = "source-text-reader") -> str:
    value = "" if url is None else str(url)
    if not value:
        return "#"
    base = value.split("#", 1)[0]
    query_text = "" if query is None else str(query).strip()
    if query_text:
        separator = "&" if "?" in base else "?"
        base = f"{base}{separator}q={quote(query_text)}"
    return f"{base}#{anchor}"


def chapter_label(record: dict[str, Any]) -> str:
    kind = str(record.get("kind") or "section").replace("-", " ").title()
    number = record.get("number") or record.get("sequence")
    title = str(record.get("title") or "Untitled")
    if number:
        return f"{kind} {number}: {title}"
    return f"{kind}: {title}"


def record_location(record: dict[str, Any]) -> str:
    start = record.get("line_start")
    end = record.get("line_end")
    page_start = record.get("pdf_page_start")
    page_end = record.get("pdf_page_end")
    parts = []
    if page_start and page_end:
        parts.append(f"PDF pages {page_start}-{page_end}" if page_start != page_end else f"PDF page {page_start}")
    if start and end:
        parts.append(f"lines {start}-{end}")
    return ", ".join(parts) or "processed source text"


def read_chapter_text(root: Path, record: dict[str, Any]) -> str:
    path = root / str(record.get("text_path") or "")
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def flexible_alias_pattern(alias: str) -> str:
    alias = alias.strip()
    if not alias:
        return r"(?!x)x"
    if alias.lower() == "a.c.":
        return r"(?<![A-Za-z0-9])a\s*\.?\s*c\s*\.?(?![A-Za-z0-9])"
    tokens = re.findall(r"[A-Za-z0-9]+", alias.lower())
    if not tokens:
        return re.escape(alias.lower())
    if len(tokens) == 1:
        body = re.escape(tokens[0])
    else:
        body = r"[\s\-/.]+".join(re.escape(token) for token in tokens)
    return rf"(?<![A-Za-z0-9]){body}(?![A-Za-z0-9])"


def compile_concept_regex(aliases: list[str]) -> re.Pattern[str]:
    patterns = [flexible_alias_pattern(alias) for alias in aliases if alias.strip()]
    patterns = sorted(set(patterns), key=len, reverse=True)
    return re.compile("|".join(patterns) or r"(?!x)x", re.IGNORECASE)


def find_snippets(text: str, matches: list[re.Match[str]], radius: int = 260, limit: int = 3) -> list[str]:
    snippets: list[str] = []
    seen: set[str] = set()
    for match in matches[: max(limit * 3, limit)]:
        start = max(0, match.start() - radius)
        end = min(len(text), match.end() + radius)
        snippet = normalize_space(text[start:end])
        if start > 0:
            snippet = "... " + snippet
        if end < len(text):
            snippet += " ..."
        key = snippet.lower()
        if key not in seen:
            snippets.append(snippet)
            seen.add(key)
        if len(snippets) >= limit:
            break
    return snippets


def build_concept_vocabulary(root: Path) -> list[dict[str, Any]]:
    concepts = {key: {"id": key, **value} for key, value in CORE_CONCEPTS.items()}
    concept_index = load_json(root / "processed" / "concept_index.json", {})
    for record in concept_index.get("records", []) if isinstance(concept_index, dict) else []:
        concept_id = slugify(str(record.get("id") or record.get("label") or ""))
        concept_id = CONCEPT_ID_OVERRIDES.get(concept_id, concept_id)
        label = str(record.get("label") or concept_id.replace("-", " ").title())
        bucket = concepts.setdefault(concept_id, {"id": concept_id, "label": label, "aliases": []})
        bucket["label"] = bucket.get("label") or label
        for alias in {label, str(record.get("id") or "")}:
            if alias and alias not in bucket["aliases"]:
                bucket["aliases"].append(alias)
    for concept in concepts.values():
        concept["aliases"] = sorted(set(str(alias).strip() for alias in concept.get("aliases", []) if str(alias).strip()))
    return sorted(concepts.values(), key=lambda item: item["label"].lower())


def load_chapter_records(root: Path, source_catalog: list[dict[str, Any]]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    source_titles = {source["source_id"]: source.get("title") for source in source_catalog}
    source_years = {source["source_id"]: source.get("year") for source in source_catalog}
    for source in source_catalog:
        source_id = str(source["source_id"])
        chapters = load_json(root / "processed" / source_id / "chapters.json", [])
        if not isinstance(chapters, list):
            continue
        for record in chapters:
            text = read_chapter_text(root, record)
            slug = source_page_slug(record)
            record = dict(record)
            record["_text"] = text
            record["_source_title"] = source_titles.get(source_id) or source_id
            record["_year"] = source_years.get(source_id)
            record["_source_text_url"] = f"{BASE_URL}/source-texts/{source_id}/{slug}/"
            record["_workbench_url"] = f"{BASE_URL}/chapter-workbench/{source_id}/{slug}/"
            records.append(record)
    return records


def build_concordance(root: Path) -> dict[str, Any]:
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    if not isinstance(source_catalog, list):
        source_catalog = []
    concept_vocabulary = build_concept_vocabulary(root)
    chapter_records = load_chapter_records(root, source_catalog)

    concepts: list[dict[str, Any]] = []
    for concept in concept_vocabulary:
        regex = compile_concept_regex(concept["aliases"])
        section_hits: list[dict[str, Any]] = []
        source_totals: Counter[str] = Counter()
        source_sections: Counter[str] = Counter()
        total_occurrences = 0
        for record in chapter_records:
            text = str(record.get("_text") or "")
            if not text:
                continue
            matches = list(regex.finditer(text))
            if not matches:
                continue
            source_id = str(record.get("source_id") or "")
            count = len(matches)
            total_occurrences += count
            source_totals[source_id] += count
            source_sections[source_id] += 1
            section_hits.append(
                {
                    "source_id": source_id,
                    "source_title": record.get("_source_title"),
                    "year": record.get("_year"),
                    "section_id": record.get("id"),
                    "section_label": chapter_label(record),
                    "section_title": record.get("title"),
                    "kind": record.get("kind"),
                    "sequence": record.get("sequence"),
                    "number": record.get("number"),
                    "location": record_location(record),
                    "status": record.get("status", "candidate"),
                    "occurrence_count": count,
                    "source_text_url": record.get("_source_text_url"),
                    "workbench_url": record.get("_workbench_url"),
                    "snippets": find_snippets(text, matches),
                }
            )
        section_hits.sort(key=lambda item: (-int(item["occurrence_count"]), str(item["source_id"]), str(item["section_id"])))
        concepts.append(
            {
                "id": concept["id"],
                "label": concept["label"],
                "aliases": concept["aliases"],
                "total_occurrences": total_occurrences,
                "matching_section_count": len(section_hits),
                "matching_source_count": len(source_totals),
                "source_totals": [
                    {
                        "source_id": source_id,
                        "source_title": next((source.get("title") for source in source_catalog if source.get("source_id") == source_id), source_id),
                        "occurrence_count": source_totals[source_id],
                        "section_count": source_sections[source_id],
                    }
                    for source_id, _ in source_totals.most_common()
                ],
                "section_hits": section_hits,
            }
        )

    concepts.sort(key=lambda item: (-int(item["total_occurrences"]), item["label"]))
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Generated source-text concordance. Counts are OCR/PDF text aids, not final conceptual claims. Verify exact passages against scans before quotation or interpretation.",
        "person": "Charles Proteus Steinmetz",
        "collection": "steinmetz",
        "source_count": len(source_catalog),
        "section_count": len(chapter_records),
        "total_concepts": len(concepts),
        "concepts": concepts,
    }


def build_index_page(concordance: dict[str, Any]) -> str:
    rows = []
    for concept in concordance["concepts"]:
        rows.append(
            f"| [{md_escape(concept['label'])}]({BASE_URL}/concept-concordance/{concept['id']}/) | {concept['total_occurrences']} | {concept['matching_source_count']} | {concept['matching_section_count']} | {md_escape(', '.join(concept['aliases'][:6]))} |"
        )
    return f"""---
title: "Concept Concordance"
description: "Generated source-grounded concept concordance across processed Steinmetz texts."
---

{GENERATED_NOTE}

## Concept Concordance

This generated concordance scans every processed Steinmetz chapter, lecture, section, and report division for the archive's current concept vocabulary. It is a navigation and evidence-discovery layer: it tells researchers where a term or concept appears, then links back to the source text and chapter workbench for careful reading.

<div class="source-text-warning" data-layer="source">
  <strong>Quality rule:</strong> concordance hits are OCR/PDF-text aids. They are not final definitions, not interpretive proof, and not replacements for scan verification.
</div>

<div class="codex-signal">
  <div><strong>{concordance['total_concepts']} concepts</strong><p>Curated Steinmetz electrical, mathematical, historical, and field-language terms.</p></div>
  <div><strong>{concordance['section_count']} sections</strong><p>Every currently processed chapter, lecture, section, and report division is searched.</p></div>
  <div><strong>{concordance['source_count']} sources</strong><p>All seeded book/report sources are included in the current pass.</p></div>
</div>

## Concepts

| Concept | Hits | Sources | Sections | Matched aliases |
| --- | ---: | ---: | ---: | --- |
{chr(10).join(rows)}
"""


def build_concept_page(concept: dict[str, Any]) -> str:
    query = concept.get("label") or concept.get("id")
    source_rows = []
    for source in concept["source_totals"]:
        source_rows.append(
            f"| {md_escape(source['source_title'])} | {source['occurrence_count']} | {source['section_count']} |"
        )
    if not source_rows:
        source_rows.append("| No current hits | 0 | 0 |")

    section_rows = []
    for hit in concept["section_hits"]:
        source_url = reader_focus_url(hit["source_text_url"], query)
        section_rows.append(
            f"| [{md_escape(hit['section_label'])}]({source_url}) | [{md_escape(hit['source_title'])}]({BASE_URL}/source-texts/{hit['source_id']}/) | {hit['occurrence_count']} | [{md_escape('Workbench')}]({hit['workbench_url']}#chapter-local-concept-hits) | {md_escape(hit['location'])} |"
        )
    if not section_rows:
        section_rows.append("| No current hits | - | 0 | - | - |")

    snippets = []
    for hit in concept["section_hits"][:18]:
        first_snippet = hit["snippets"][0] if hit.get("snippets") else ""
        if not first_snippet:
            continue
        source_url = reader_focus_url(hit["source_text_url"], query)
        snippets.append(
            f"""<details class="layered-reading" data-layer="source">
<summary>{html_escape(hit['section_label'])} - {hit['occurrence_count']} hit(s)</summary>
<div class="body">

[Open source text]({source_url}) | [Open chapter workbench]({hit['workbench_url']}#chapter-local-concept-hits)

{code_fence(first_snippet)}

</div>
</details>"""
        )
    snippet_text = "\n\n".join(snippets) or "No snippets captured for the current pass."

    return f"""---
title: {yaml_quote(concept['label'] + " Concordance")}
description: {yaml_quote("Generated source-text concordance for " + concept['label'] + ".")}
---

{GENERATED_NOTE}

## {md_escape(concept['label'])}

<div class="source-text-warning" data-layer="source">
  <strong>Concordance status:</strong> generated from processed OCR/PDF text. Treat these as source-location aids until each passage is checked against the scan.
</div>

<div class="codex-signal">
  <div><strong>{concept['total_occurrences']} hits</strong><p>Total text matches across processed Steinmetz sections.</p></div>
  <div><strong>{concept['matching_source_count']} sources</strong><p>Sources containing at least one matched alias.</p></div>
  <div><strong>{concept['matching_section_count']} sections</strong><p>Chapters, lectures, sections, or report divisions with matches.</p></div>
</div>

## Matched Aliases

{', '.join(f'`{md_escape(alias)}`' for alias in concept['aliases'])}

## Source Distribution

| Source | Hits | Sections |
| --- | ---: | ---: |
{chr(10).join(source_rows)}

## Section Hits

| Section | Source | Hits | Workbench | Location |
| --- | --- | ---: | --- | --- |
{chr(10).join(section_rows)}

## Representative Source Snippets

{snippet_text}
"""


def write_pages(root: Path, concordance: dict[str, Any]) -> None:
    out_dir = root / "site" / "src" / "content" / "docs" / "concept-concordance"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    write_text(out_dir / "index.mdx", build_index_page(concordance))
    for concept in concordance["concepts"]:
        write_text(out_dir / str(concept["id"]) / "index.mdx", build_concept_page(concept))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()
    concordance = build_concordance(root)
    write_json(root / "processed" / "concept_concordance.json", concordance)
    write_pages(root, concordance)
    print(
        f"Generated {concordance['total_concepts']} concept concordance pages "
        f"from {concordance['section_count']} processed sections."
    )


if __name__ == "__main__":
    main()
