#!/usr/bin/env python3
"""Generate scholarly control ledgers for the Steinmetz archive.

These artifacts turn broad generated coverage into reviewable scholarly
infrastructure: notation tracking, diagram provenance, schema reference, and
expert review packets. They are conservative by design. A ledger entry explains
what exists and what still needs verification; it does not promote a candidate
to canonical status by itself.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_world_class_artifacts.py. Do not edit by hand. */}"

SYMBOL_NOTES = {
    "f": "Frequency. Check whether Steinmetz is using cycles per second or angular frequency in the surrounding text.",
    "S": "Velocity of propagation in Steinmetz's radiation notation.",
    "lambda": "Wave length in the source relation; modern notation usually uses lambda.",
    "v": "Modern velocity symbol used when translating Steinmetz's S.",
    "I": "Alternating current quantity or complex current, depending on chapter context.",
    "i": "Current component or instantaneous/current magnitude in Steinmetz-era notation. Needs local context.",
    "i'": "Quadrature current component in the symbolic-method passage.",
    "j": "Imaginary operator used by Steinmetz as a quarter-period or 90-degree rotation.",
    "x": "Reactance in Steinmetz AC notation.",
    "L": "Inductance.",
    "C": "Capacity or capacitance. Preserve Steinmetz's capacity language before modernizing it.",
    "Z": "Impedance as a complex AC quantity.",
    "r": "Resistance or effective resistance in Steinmetz notation, depending on source context.",
    "Y": "Admittance.",
    "g": "Conductance component of admittance.",
    "b": "Susceptance component of admittance.",
    "R": "Modern resistance symbol.",
    "X": "Modern reactance symbol.",
    "G": "Modern conductance symbol.",
    "B": "Modern susceptance symbol.",
    "P_o": "Real or output power notation in the source record; verify typography against scan.",
    "P": "Power.",
    "e": "Electromotive force or voltage in older notation; verify whether RMS or instantaneous value is meant.",
    "V": "Modern voltage symbol.",
    "theta": "Phase angle in source notation.",
    "phi": "Modern phase-angle notation.",
    "pi": "Circle constant in frequency/reactance relations; verify whether source writes pi as a symbol or text.",
    "omega": "Modern angular frequency notation used in archive translations.",
    "cos": "Cosine function used in power-factor relations.",
    "R_eff": "Modern effective-resistance notation used in the archive translation.",
    "B_C": "Modern capacity susceptance notation used in the archive translation.",
}

SCHEMA_FILES = [
    ("source_catalog", "sources/source_catalog.json", "Seeded source records and custody pointers."),
    ("research_index", "processed/research_index.json", "Corpus-wide processing inventory."),
    ("evidence_ledger", "processed/evidence_ledger.json", "Traceability records for source/candidate/promoted items."),
    ("chapter_atlas", "processed/chapter_atlas.json", "Theme routing records for processed sections."),
    ("book_coverage_atlas", "processed/book_coverage_atlas.json", "Book-level coverage records for processed sources and sections."),
    ("chapter_workbench", "processed/chapter_workbench.json", "Section-level research workbench records."),
    ("concept_concordance", "processed/concept_concordance.json", "Source-text concept hit records."),
    ("canonical_equations", "processed/canonical_equations.json", "First equation canon and review state."),
    ("completion_audit", "processed/completion_audit.json", "Source-by-source readiness gates."),
    ("citation_index", "processed/citation_index.json", "Project and source citation records."),
    ("notation_ledger", "processed/notation_ledger.json", "Equation notation and translation ledger."),
    ("diagram_provenance_ledger", "processed/diagram_provenance_ledger.json", "Original crop and redraw provenance ledger."),
    ("schema_reference", "processed/schema_reference.json", "Machine-readable schema/reference guide."),
    ("expert_review_packets", "processed/expert_review_packets.json", "Review bundles for experts and contributors."),
    ("release_readiness", "processed/release_readiness.json", "Named publication release levels and readiness states."),
    ("accessibility_audit", "processed/accessibility_audit.json", "Automated accessibility-readiness scan and manual review gates."),
    ("edition_comparison_index", "processed/edition_comparison_index.json", "Edition collation queue for seeded sources."),
    ("patent_theory_bridge", "processed/patent_theory_bridge.json", "Seeded bridge from patents to concepts and theory-review targets."),
    ("canonical_verification_workbench", "processed/canonical_verification_workbench.json", "Top-level queue index for canonical verification work."),
    ("equation_verification_queue", "processed/equation_verification_queue.json", "Equation scan-check queue with OCR line snippets."),
    ("figure_verification_queue", "processed/figure_verification_queue.json", "Original figure crop verification queue."),
    ("patent_verification_queue", "processed/patent_verification_queue.json", "Patent authority PDF, claim, drawing, and theory bridge queue."),
    ("claim_attribution_ledger", "processed/claim_attribution_ledger.json", "Source-isolation ledger for fact, candidate, translation, patent, diagram, and interpretation layers."),
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def slug_label(path: str) -> str:
    stem = Path(path).stem
    return stem.replace("-", " ").replace("_", " ").title()


def source_lookup(root: Path) -> dict[str, dict[str, Any]]:
    catalog = load_json(root / "sources" / "source_catalog.json", [])
    if not isinstance(catalog, list):
        return {}
    return {str(source.get("source_id")): source for source in catalog if source.get("source_id")}


def symbol_present(symbol: str, text: str) -> bool:
    escaped = re.escape(symbol)
    compact = re.sub(r"\s+", "", text)
    if symbol == "j" and re.search(r"(?<![A-Za-z0-9_'])j(?=x|[^A-Za-z0-9_']|$)", text):
        return True
    if symbol == "x" and re.search(r"(?<![A-Za-z0-9_'])(?:x(?:_[A-Za-z0-9]+)?|jx)(?![A-Za-z0-9_'])", text):
        return True
    if symbol == "V" and "VI" in compact:
        return True
    if symbol == "I" and "VI" in compact:
        return True
    if symbol == "e" and "ei" in compact:
        return True
    if symbol == "i" and "ei" in compact:
        return True
    if symbol.endswith("'"):
        return symbol in text
    return bool(re.search(rf"(?<![A-Za-z0-9_']){escaped}(?![A-Za-z0-9_'])", text))


def build_notation_ledger(root: Path) -> dict[str, Any]:
    equations = load_json(root / "processed" / "canonical_equations.json", {}).get("records", [])
    symbol_index: dict[str, dict[str, Any]] = {}
    records = []

    for equation in equations:
        forms = f"{equation.get('original_form', '')} {equation.get('modern_form', '')}"
        symbol_map = []
        for symbol, note in SYMBOL_NOTES.items():
            if symbol_present(symbol, forms):
                symbol_map.append(
                    {
                        "symbol": symbol,
                        "meaning_note": note,
                        "review_state": "needs source-context verification",
                    }
                )
                symbol_index.setdefault(
                    symbol,
                    {
                        "symbol": symbol,
                        "meaning_note": note,
                        "equation_ids": [],
                        "source_ids": [],
                    },
                )
                symbol_index[symbol]["equation_ids"].append(equation.get("id"))
                if equation.get("source_id") not in symbol_index[symbol]["source_ids"]:
                    symbol_index[symbol]["source_ids"].append(equation.get("source_id"))

        records.append(
            {
                "equation_id": equation.get("id"),
                "title": equation.get("title"),
                "source_id": equation.get("source_id"),
                "source_title": equation.get("source_title"),
                "original_form": equation.get("original_form"),
                "modern_form": equation.get("modern_form"),
                "status": equation.get("status"),
                "source_ref": equation.get("source_ref", {}),
                "site_path": equation.get("site_path"),
                "symbols": symbol_map,
                "review_actions": [
                    "Check original typography and subscripts against scan.",
                    "Confirm whether quantities are RMS, maximum, instantaneous, or symbolic.",
                    "Record unit conventions and edition differences if found.",
                ],
            }
        )

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Notation ledger for review. It maps source and modern symbols but does not certify typography until scan verification is complete.",
        "record_count": len(records),
        "symbol_count": len(symbol_index),
        "symbol_index": sorted(symbol_index.values(), key=lambda item: item["symbol"].lower()),
        "records": records,
    }


def public_diagram_url(path: str) -> str:
    normalized = path.replace("\\", "/")
    if normalized.startswith("diagrams/"):
        return f"{BASE_URL}/{normalized}"
    if normalized.startswith("site/public/"):
        return f"{BASE_URL}/{normalized.removeprefix('site/public/')}"
    return f"{BASE_URL}/{normalized}"


def infer_redraw_source(path: Path) -> str:
    name = path.as_posix().lower()
    if "alternating" in name or "ac-" in name or "phasor" in name or "impedance" in name:
        return "theory-calculation-alternating-current-phenomena"
    if "transient" in name:
        return "theory-calculation-transient-electric-phenomena-oscillations"
    if "radiation" in name or "illumination" in name or "spectrum" in name:
        return "radiation-light-and-illumination"
    return "cross-source-or-conceptual"


def build_diagram_provenance_ledger(root: Path) -> dict[str, Any]:
    sources = source_lookup(root)
    original_crops = []
    for manifest_path in sorted((root / "diagrams" / "original").rglob("*.json")):
        manifest = load_json(manifest_path, {})
        source_id = manifest.get("source_id")
        output_path = str(manifest.get("output_path") or manifest_path.with_suffix("").relative_to(root))
        original_crops.append(
            {
                "id": manifest.get("id") or manifest_path.stem,
                "asset_type": manifest.get("asset_type", "original-scan-crop"),
                "source_id": source_id,
                "source_title": sources.get(str(source_id), {}).get("title"),
                "status": manifest.get("status"),
                "source_location": manifest.get("source_location"),
                "source_image": manifest.get("source_image"),
                "crop_box_pixels": manifest.get("crop_box_pixels"),
                "output_path": output_path,
                "public_url": public_diagram_url(output_path),
                "width": manifest.get("width"),
                "height": manifest.get("height"),
                "sha256": manifest.get("sha256"),
                "quality_note": manifest.get("quality_note"),
                "manifest_path": manifest_path.relative_to(root).as_posix(),
            }
        )

    public_redraws_by_name = {
        path.name: path.relative_to(root).as_posix()
        for path in (root / "site" / "public" / "diagrams").rglob("*.svg")
    }
    redraws = []
    for svg_path in sorted((root / "diagrams" / "recreated").rglob("*.svg")):
        public_path = public_redraws_by_name.get(svg_path.name)
        rel_path = svg_path.relative_to(root).as_posix()
        redraws.append(
            {
                "id": svg_path.stem,
                "asset_type": "modern-redraw-or-reading-aid",
                "source_id": infer_redraw_source(svg_path.relative_to(root)),
                "status": "reconstruction; must remain visually distinct from original scan crop",
                "source_path": rel_path,
                "public_url": public_diagram_url(public_path or rel_path),
                "verification": "needs source-link and annotation review before canonical diagram status",
                "review_actions": [
                    "Confirm which original figure or concept the redraw explains.",
                    "Ensure annotations are not mistaken for Steinmetz's original drawing.",
                    "Link redraw to the original crop when available.",
                ],
            }
        )

    status_counts = Counter(item["status"] for item in original_crops)
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Diagram provenance ledger. Original crops are scan-derived assets; redraws are interpretive/reconstructive reading aids unless separately reviewed.",
        "original_crop_count": len(original_crops),
        "redraw_count": len(redraws),
        "original_crop_status_counts": dict(status_counts),
        "original_crops": original_crops,
        "redraws": redraws,
    }


def sample_schema(data: Any) -> dict[str, Any]:
    if isinstance(data, list):
        sample = data[0] if data else {}
        return {
            "container": "array",
            "top_level_fields": sorted(sample.keys()) if isinstance(sample, dict) else [],
            "record_count": len(data),
        }
    if isinstance(data, dict):
        sample = None
        for key in ("records", "source_audits", "exports", "packets", "original_crops"):
            value = data.get(key)
            if isinstance(value, list) and value:
                sample = value[0]
                break
        fields = sorted(sample.keys()) if isinstance(sample, dict) else sorted(data.keys())
        return {
            "container": "object",
            "top_level_fields": sorted(data.keys()),
            "sample_record_fields": fields,
            "record_count": len(data.get("records", [])) if isinstance(data.get("records"), list) else None,
        }
    return {"container": type(data).__name__, "top_level_fields": [], "record_count": None}


def review_fields(fields: list[str]) -> list[str]:
    markers = ("status", "review", "verification", "confidence", "quality", "source_ref")
    return [field for field in fields if any(marker in field.lower() for marker in markers)]


def build_schema_reference(root: Path) -> dict[str, Any]:
    files = []
    for file_id, rel_path, description in SCHEMA_FILES:
        path = root / rel_path
        exists = path.exists()
        schema = sample_schema(load_json(path, {})) if exists and path.suffix == ".json" else {}
        fields = schema.get("sample_record_fields") or schema.get("top_level_fields") or []
        files.append(
            {
                "id": file_id,
                "description": description,
                "path": rel_path,
                "exists": exists,
                "public_url": f"{BASE_URL}/data/{file_id}.json" if rel_path.startswith("processed/") or rel_path.startswith("sources/") else None,
                "schema_summary": schema,
                "review_state_fields": review_fields(fields),
                "usage_rule": "Use review-state fields before citing any record as fact.",
            }
        )
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Schema reference for public and processed data. It is descriptive, not a formal JSON Schema validator yet.",
        "files": files,
    }


def count_patents(root: Path) -> int:
    register = load_json(root / "sources" / "steinmetz_patents" / "patent_register.json", {})
    patents = register.get("patents", [])
    return len(patents) if isinstance(patents, list) else 0


def build_expert_review_packets(root: Path, notation: dict[str, Any], diagrams: dict[str, Any]) -> dict[str, Any]:
    completion = load_json(root / "processed" / "completion_audit.json", {})
    concepts = load_json(root / "processed" / "concept_concordance.json", {})
    equations = load_json(root / "processed" / "canonical_equations.json", {})
    packets = [
        {
            "id": "source-custody-and-ocr",
            "title": "Source Custody And OCR Review",
            "reviewer_profile": "Historian of technology, archivist, or careful source transcriber.",
            "scope": "Check source manifests, editions, OCR, page maps, public source links, and scan access.",
            "artifact_links": [
                f"{BASE_URL}/roadmap/completion-audit/",
                f"{BASE_URL}/source-library/",
                f"{BASE_URL}/source-texts/",
                f"{BASE_URL}/data/source_catalog.json",
            ],
            "ready_count": completion.get("project_gates", {}).get("sources_total"),
            "tasks": [
                "Confirm edition/year/publisher fields for each source.",
                "Check OCR readings only against scans or trusted editions.",
                "Record missing checksums, page maps, and public archive links.",
            ],
        },
        {
            "id": "equation-canon-and-notation",
            "title": "Equation Canon And Notation Review",
            "reviewer_profile": "Electrical engineer, mathematician, or power-systems educator.",
            "scope": "Review the first equation canon, notation translations, units, and worked-example readiness.",
            "artifact_links": [
                f"{BASE_URL}/mathematics/equations/",
                f"{BASE_URL}/roadmap/notation-ledger/",
                f"{BASE_URL}/data/canonical_equations.json",
                f"{BASE_URL}/data/notation_ledger.json",
            ],
            "ready_count": equations.get("total_records", notation.get("record_count")),
            "tasks": [
                "Verify original typography against scans.",
                "Separate Steinmetz notation from modern notation.",
                "Check dimensions, assumptions, RMS/maximum conventions, and sign conventions.",
            ],
        },
        {
            "id": "diagram-provenance",
            "title": "Diagram Provenance Review",
            "reviewer_profile": "Engineer, technical illustrator, or documentation reviewer.",
            "scope": "Check original crops, crop boxes, figure numbers, captions, checksums, and redraw labels.",
            "artifact_links": [
                f"{BASE_URL}/diagrams/",
                f"{BASE_URL}/roadmap/diagram-provenance-ledger/",
                f"{BASE_URL}/data/diagram_provenance_ledger.json",
            ],
            "ready_count": diagrams.get("original_crop_count"),
            "tasks": [
                "Verify each crop against the source scan and figure caption.",
                "Confirm redraws are labeled as reconstruction.",
                "Link diagrams to concepts, equations, and source text sections.",
            ],
        },
        {
            "id": "concept-and-glossary",
            "title": "Concept And Glossary Review",
            "reviewer_profile": "Electrical theory reader, historian, or terminology specialist.",
            "scope": "Promote generated concept hits into source-located definitions and glossary pages.",
            "artifact_links": [
                f"{BASE_URL}/concept-concordance/",
                f"{BASE_URL}/concepts/",
                f"{BASE_URL}/glossary/",
                f"{BASE_URL}/data/concept_concordance.json",
            ],
            "ready_count": concepts.get("total_concepts") or len(concepts.get("concepts", [])),
            "tasks": [
                "Distinguish original usage from modern equivalent.",
                "Mark obsolete, renamed, absorbed, or still-current terms.",
                "Add exact source locations before calling a definition canonical.",
            ],
        },
        {
            "id": "patent-authority-pass",
            "title": "Patent Authority Pass",
            "reviewer_profile": "Patent researcher, apparatus historian, or electrical engineer.",
            "scope": "Turn the seeded patent register into verified patent dossiers with PDFs, drawings, claims, and theory links.",
            "artifact_links": [
                f"{BASE_URL}/sources/steinmetz-patents/",
                f"{BASE_URL}/sources/steinmetz-patents/seeded-patent-dossiers/",
            ],
            "ready_count": count_patents(root),
            "tasks": [
                "Download and checksum each patent PDF.",
                "Extract drawings and claim text.",
                "Link patents to Steinmetz theory only where a source-located overlap exists.",
            ],
        },
        {
            "id": "interpretive-boundaries",
            "title": "Interpretive Boundary Review",
            "reviewer_profile": "Modern EE reader, Tesla-era researcher, or alternative-field researcher.",
            "scope": "Check that modern, Tesla-era, and ether-field readings remain labeled and never replace Steinmetz source claims.",
            "artifact_links": [
                f"{BASE_URL}/comparisons/",
                f"{BASE_URL}/comparisons/ether-field-reading-guide/",
                f"{BASE_URL}/roadmap/editorial-policy/",
                f"{BASE_URL}/roadmap/canonical-review-workflow/",
            ],
            "ready_count": None,
            "tasks": [
                "Mark explicit Steinmetz statements separately from interpretive readings.",
                "Prevent cross-author synthesis from being presented as historical fact.",
                "Add source references or downgrade unsupported claims to questions.",
            ],
        },
    ]
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Expert review packets route review work. They are invitations to verify, not certificates of completion.",
        "packet_count": len(packets),
        "packets": packets,
    }


def build_notation_page(ledger: dict[str, Any]) -> str:
    rows = []
    for record in ledger["records"]:
        symbols = ", ".join(f"`{item['symbol']}`" for item in record["symbols"]) or "needs mapping"
        rows.append(
            f"| `{md_escape(record['equation_id'])}` | {md_escape(record['title'])} | {symbols} | {md_escape(record['status'])} | {md_escape(record.get('source_ref', {}).get('verification'))} |"
        )
    symbol_rows = []
    for item in ledger["symbol_index"]:
        equation_ids = ", ".join(f"`{equation_id}`" for equation_id in item["equation_ids"])
        symbol_rows.append(f"| `{md_escape(item['symbol'])}` | {md_escape(item['meaning_note'])} | {equation_ids} |")

    return f"""---
title: Notation Ledger
description: Source and modern notation review ledger for Steinmetz equations.
---

{GENERATED_NOTE}

## Notation Ledger

The notation ledger prevents a quiet failure mode: translating Steinmetz into modern symbols so quickly that the older notation, assumptions, and physical language disappear. Each row remains a review target until the original typography, source context, and units are checked.

<div class="source-text-warning" data-layer="source">
  <strong>Boundary:</strong> this ledger maps notation for review. It does not certify an equation as scan-verified.
</div>

## Equation Records

| Equation | Title | Symbols Tracked | Status | Verification |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Symbol Index

| Symbol | Review Meaning | Equation Records |
| --- | --- | --- |
{chr(10).join(symbol_rows)}

## Reviewer Rule

Preserve Steinmetz's original notation first. Add modern notation second. If a symbol changes meaning across sources or editions, record the difference instead of smoothing it away.
"""


def build_diagram_page(ledger: dict[str, Any]) -> str:
    crop_rows = []
    for crop in ledger["original_crops"]:
        crop_rows.append(
            f"| `{md_escape(crop['id'])}` | {md_escape(crop.get('source_title') or crop.get('source_id'))} | {md_escape(crop.get('source_location'))} | [image]({crop['public_url']}) | `{md_escape(crop.get('status'))}` |"
        )
    redraw_rows = []
    for redraw in ledger["redraws"]:
        redraw_rows.append(
            f"| `{md_escape(redraw['id'])}` | {md_escape(redraw['source_id'])} | [svg]({redraw['public_url']}) | {md_escape(redraw['status'])} |"
        )

    return f"""---
title: Diagram Provenance Ledger
description: Original crop and modern redraw provenance for Steinmetz Decoded diagrams.
---

{GENERATED_NOTE}

## Diagram Provenance Ledger

Every serious diagram page needs to tell the reader what they are seeing: original scan crop, cleaned crop, recreated vector, annotated reconstruction, or conceptual reading aid. This ledger keeps that distinction visible.

<div class="source-text-warning" data-layer="source">
  <strong>Boundary:</strong> original crops are closer to source evidence; redraws are explanatory reconstructions unless a page says otherwise.
</div>

## Original Scan Crops

| Figure | Source | Source Location | Public Image | Status |
| --- | --- | --- | --- | --- |
{chr(10).join(crop_rows)}

## Modern Redraws And Reading Aids

| Redraw | Source Linkage | Public Asset | Status |
| --- | --- | --- | --- |
{chr(10).join(redraw_rows)}

## Completion Target

The mature archive should give every original Steinmetz figure a manifest, checksum, source-page reference, caption check, public image, and an optional reconstruction that is clearly labeled.
"""


def build_schema_page(reference: dict[str, Any]) -> str:
    rows = []
    for item in reference["files"]:
        exists = "yes" if item["exists"] else "no"
        fields = item.get("schema_summary", {}).get("sample_record_fields") or item.get("schema_summary", {}).get("top_level_fields") or []
        rows.append(
            f"| `{md_escape(item['id'])}` | {md_escape(item['description'])} | `{md_escape(item['path'])}` | {exists} | {md_escape(', '.join(fields[:8]))} |"
        )

    return f"""---
title: Schema Reference
description: Descriptive reference for processed and public Steinmetz Decoded data files.
---

{GENERATED_NOTE}

## Schema Reference

This page documents the data shapes that make the archive reusable. It is descriptive, not a formal validator yet. The rule is simple: external tools may consume these files, but review-state fields still decide whether a record can be cited as verified fact.

## Data Files

| ID | Purpose | Path | Exists | Representative Fields |
| --- | --- | --- | ---: | --- |
{chr(10).join(rows)}

## Review-State Fields

When building external tools, preserve fields such as `status`, `verification`, `confidence`, `quality_note`, `source_ref`, and `review_state`. Removing them makes candidate OCR look more certain than it is.

## Future Formalization

The next level is formal JSON Schema files in `pipeline/schemas/`, versioned export contracts, and validation in CI.
"""


def build_review_packets_page(packets: dict[str, Any]) -> str:
    cards = []
    for packet in packets["packets"]:
        links = " ".join(f'<a href="{html_escape(link)}">{html_escape(slug_label(link.rstrip("/").split("/")[-1] or "index"))}</a>' for link in packet["artifact_links"])
        tasks = "\n".join(f"    <li>{html_escape(task)}</li>" for task in packet["tasks"])
        ready = "open" if packet["ready_count"] is None else str(packet["ready_count"])
        cards.append(
            f"""<section class="source-access-card">
  <h3>{html_escape(packet['title'])}</h3>
  <p><strong>Reviewer:</strong> {html_escape(packet['reviewer_profile'])}</p>
  <p><strong>Scope:</strong> {html_escape(packet['scope'])}</p>
  <p><strong>Ready count:</strong> {html_escape(ready)}</p>
  <p class="source-access-links">{links}</p>
  <ul>
{tasks}
  </ul>
</section>"""
        )

    return f"""---
title: Expert Review Packets
description: Review bundles for engineers, historians, mathematicians, diagram reviewers, patent researchers, and interpretive-boundary reviewers.
---

{GENERATED_NOTE}

## Expert Review Packets

The archive is now large enough that review has to be routed. These packets turn the master plan into practical work bundles for people with different expertise.

<div class="source-text-warning" data-layer="source">
  <strong>Use rule:</strong> a review packet is not a certificate. It is a work queue for turning candidate material into canonical material.
</div>

<div class="research-passages">
{chr(10).join(cards)}
</div>

## Coordination Rule

Reviewers should cite source IDs, page locations, equation IDs, crop IDs, and issue template records. That keeps external expertise connected to the same traceability system used by the site.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()

    notation = build_notation_ledger(root)
    diagrams = build_diagram_provenance_ledger(root)

    write_json(root / "processed" / "notation_ledger.json", notation)
    write_json(root / "processed" / "diagram_provenance_ledger.json", diagrams)

    packets = build_expert_review_packets(root, notation, diagrams)
    write_json(root / "processed" / "expert_review_packets.json", packets)

    schema = build_schema_reference(root)
    write_json(root / "processed" / "schema_reference.json", schema)
    schema = build_schema_reference(root)
    write_json(root / "processed" / "schema_reference.json", schema)

    docs = root / "site" / "src" / "content" / "docs" / "roadmap"
    write_text(docs / "notation-ledger.mdx", build_notation_page(notation))
    write_text(docs / "diagram-provenance-ledger.mdx", build_diagram_page(diagrams))
    write_text(docs / "schema-reference.mdx", build_schema_page(schema))
    write_text(docs / "expert-review-packets.mdx", build_review_packets_page(packets))

    print(
        "Generated world-class artifacts: "
        f"{notation['record_count']} notation records, "
        f"{diagrams['original_crop_count']} original crops, "
        f"{diagrams['redraw_count']} redraws, "
        f"{packets['packet_count']} review packets."
    )


if __name__ == "__main__":
    main()
