#!/usr/bin/env python3
"""Generate guided reading routes across the processed Steinmetz corpus.

The book coverage atlas, source text browser, and chapter workbench expose the
whole processed corpus. This script adds a human-facing route layer on top of
that data so readers can enter by purpose without losing source custody.
"""

from __future__ import annotations

import html
import json
import re
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_reading_routes.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def html_escape(value: Any) -> str:
    text = html.escape("" if value is None else str(value), quote=True)
    return (
        text.replace("\\", "&#92;")
        .replace("*", "&#42;")
        .replace("_", "&#95;")
        .replace("`", "&#96;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("$", "&#36;")
    )


def slug_text(value: Any) -> str:
    text = str(value or "").lower()
    return re.sub(r"[^a-z0-9]+", " ", text)


def site_url(path: str | None) -> str:
    if not path:
        return ""
    if path.startswith("http"):
        return path
    if path.startswith(BASE_URL):
        return path
    if path.startswith("/"):
        return f"{BASE_URL}{path}"
    return f"{BASE_URL}/{path}"


def compact_list(values: list[Any], limit: int = 4) -> list[str]:
    out: list[str] = []
    for value in values[:limit]:
        if isinstance(value, dict):
            label = value.get("label") or value.get("id")
        else:
            label = value
        if label:
            out.append(str(label))
    return out


def count_label(count: int, singular: str, plural: str | None = None) -> str:
    return f"{count} {singular if count == 1 else (plural or singular + 's')}"


ROUTES: list[dict[str, Any]] = [
    {
        "id": "first-hour",
        "title": "First Hour With Steinmetz",
        "audience": "Curious readers, students, and visitors who need a humane entry before the dense technical books.",
        "why_it_exists": "Begins with biography and visual source material, then moves from radiation and light into field language, AC calculation, and transients.",
        "reading_rule": "Read the route links first, then open the source text for each section before using the workbench.",
        "keywords": ["radiation", "light", "electric waves", "field", "alternating current", "transient", "hysteresis"],
        "preferred_sources": [
            "radiation-light-and-illumination",
            "elementary-lectures-electric-discharges-waves-impulses",
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-transient-electric-phenomena-oscillations",
            "theoretical-elements-electrical-engineering",
        ],
        "feature_weights": {"figures": 12, "equations": 6, "quotes": 8, "words": 1},
        "strict_preferred": True,
        "max_per_source": 4,
        "section_limit": 10,
        "start_links": [
            ("Who Was Steinmetz?", f"{BASE_URL}/who-was-steinmetz/", "Human and technical orientation."),
            ("Begin Lecture I", f"{BASE_URL}/source-texts/radiation-light-and-illumination/lecture-01/", "Start reading a primary text immediately."),
            ("RLI Book Map", f"{BASE_URL}/book-coverage/radiation-light-and-illumination/", "Readable first book with visual source material."),
            ("Diagram Archive", f"{BASE_URL}/diagrams/", "Original crops and modern visual aids."),
        ],
    },
    {
        "id": "source-only",
        "title": "Source-Only Primary Text Route",
        "audience": "Readers who want Steinmetz first, with commentary held back until the original text has been read.",
        "why_it_exists": "Keeps the reader close to the candidate OCR/PDF text pages and source custody before any modern or interpretive layer.",
        "reading_rule": "Use the source-text link first. Use the workbench only after reading the primary text passage.",
        "keywords": ["lecture", "chapter", "section", "radiation", "alternating", "transient", "field", "apparatus"],
        "preferred_sources": [
            "radiation-light-and-illumination",
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-transient-electric-phenomena-oscillations",
            "engineering-mathematics",
            "theoretical-elements-electrical-engineering",
            "general-lectures-electrical-engineering",
        ],
        "feature_weights": {"figures": 7, "equations": 7, "quotes": 10, "words": 2},
        "strict_preferred": False,
        "max_per_source": 3,
        "section_limit": 12,
        "start_links": [
            ("Source Text Browser", f"{BASE_URL}/source-texts/", "Read the processed source text directly."),
            ("Book Coverage Atlas", f"{BASE_URL}/book-coverage/", "Choose a source before entering sections."),
            ("Editorial Policy", f"{BASE_URL}/roadmap/editorial-policy/", "Understand OCR, page, and verification rules."),
        ],
    },
    {
        "id": "ac-symbolic-method",
        "title": "Alternating Current, Complex Quantities, And Symbolic Method",
        "audience": "Electrical students and engineers studying phasors, impedance, reactance, admittance, and complex notation.",
        "why_it_exists": "Connects Steinmetz's practical AC calculation language to the modern phasor and complex-number method while preserving his notation.",
        "reading_rule": "Move from symbolic method sections to equation pages and interactive phasor tools.",
        "keywords": [
            "alternating current",
            "symbolic",
            "complex",
            "imaginary",
            "impedance",
            "reactance",
            "admittance",
            "conductance",
            "susceptance",
            "power factor",
            "phasor",
            "wave shape",
            "harmonic",
        ],
        "preferred_sources": [
            "theory-calculation-alternating-current-phenomena",
            "engineering-mathematics",
            "theoretical-elements-electrical-engineering",
        ],
        "feature_weights": {"figures": 10, "equations": 18, "quotes": 5, "words": 1},
        "strict_preferred": True,
        "max_per_source": 5,
        "section_limit": 12,
        "start_links": [
            ("AC Book Coverage", f"{BASE_URL}/book-coverage/theory-calculation-alternating-current-phenomena/", "Source map for AC phenomena."),
            ("Symbolic Method Page", f"{BASE_URL}/sources/theory-calculation-alternating-current-phenomena/symbolic-method/", "Curated deep decoding."),
            ("Equation Catalog", f"{BASE_URL}/mathematics/", "Candidate and canonical equations."),
            ("Phasor Tool", f"{BASE_URL}/tools/phasor-symbolic-form/", "Interactive symbolic-form visualizer."),
        ],
    },
    {
        "id": "transients-surges",
        "title": "Transients, Oscillations, Surges, And Tesla-Era Questions",
        "audience": "Tesla-era researchers, transient-analysis students, and readers interested in high-frequency electrical behavior.",
        "why_it_exists": "Routes the reader into Steinmetz's treatment of transient terms, condenser discharge, oscillation, waves, surges, and line behavior.",
        "reading_rule": "Read transient source sections first, then compare with the Tesla-era and modern engineering interpretation pages.",
        "keywords": [
            "transient",
            "oscillation",
            "damping",
            "surge",
            "lightning",
            "condenser",
            "discharge",
            "standing",
            "traveling",
            "line",
            "high frequency",
            "wave",
        ],
        "preferred_sources": [
            "theory-calculation-transient-electric-phenomena-oscillations",
            "elementary-lectures-electric-discharges-waves-impulses",
            "general-lectures-electrical-engineering",
        ],
        "feature_weights": {"figures": 16, "equations": 16, "quotes": 7, "words": 1},
        "strict_preferred": True,
        "max_per_source": 5,
        "section_limit": 12,
        "start_links": [
            ("Transient Book Coverage", f"{BASE_URL}/book-coverage/theory-calculation-transient-electric-phenomena-oscillations/", "Source map for transient phenomena."),
            ("Tesla-Era Transients", f"{BASE_URL}/comparisons/transients-tesla-era-high-frequency/", "Labeled comparison route."),
            ("Transient RLC Tool", f"{BASE_URL}/tools/transient-rlc/", "Interactive decay and oscillation visualizer."),
            ("Surge Tool", f"{BASE_URL}/tools/lightning-surge/", "Traveling-wave surge visualizer."),
        ],
    },
    {
        "id": "field-language",
        "title": "Fields, Ether References, Dielectricity, Magnetism, And Hysteresis",
        "audience": "Historians of field language, ether-field readers, and engineers studying material and field behavior.",
        "why_it_exists": "Gathers the most relevant source routes for field language while keeping explicit Steinmetz wording, modern physics, and interpretive readings separate.",
        "reading_rule": "Begin with exact source contexts. Treat ether-field synthesis as interpretive unless a passage explicitly supports it.",
        "keywords": [
            "field",
            "ether",
            "dielectric",
            "capacity",
            "magnetism",
            "magnetic",
            "hysteresis",
            "permeability",
            "force",
            "stress",
            "strain",
            "displacement",
        ],
        "preferred_sources": [
            "elementary-lectures-electric-discharges-waves-impulses",
            "theoretical-elements-electrical-engineering",
            "engineering-mathematics",
            "four-lectures-relativity-space",
            "theory-calculation-electric-apparatus",
        ],
        "feature_weights": {"figures": 9, "equations": 8, "quotes": 14, "words": 1},
        "strict_preferred": True,
        "max_per_source": 4,
        "section_limit": 12,
        "start_links": [
            ("Ether Concordance", f"{BASE_URL}/concept-concordance/ether/", "Exact source hits for ether."),
            ("Theme Evidence: Field Language", f"{BASE_URL}/theme-evidence/ether-field-language/", "Source-located field/ether theme route."),
            ("Hysteresis Concept", f"{BASE_URL}/concepts/hysteresis/", "Concept page with modern and interpretive layers."),
            ("Ether-Field Reading Guide", f"{BASE_URL}/comparisons/ether-field-reading-guide/", "Interpretive boundary rules."),
        ],
    },
    {
        "id": "math-equations",
        "title": "Mathematics, Equations, And Worked Calculation",
        "audience": "Readers who want notation, derivation, formula translation, and computational tools.",
        "why_it_exists": "Prioritizes equation-dense sections and connects them to the canonical equation set, notation ledger, and tools.",
        "reading_rule": "Preserve Steinmetz's notation first, then translate into modern engineering form with the equation pages.",
        "keywords": [
            "equation",
            "formula",
            "calculation",
            "method",
            "symbolic",
            "function",
            "exponential",
            "trigonometric",
            "series",
            "general number",
            "law",
            "constant",
        ],
        "preferred_sources": [
            "engineering-mathematics",
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-transient-electric-phenomena-oscillations",
            "theoretical-elements-electrical-engineering",
            "commonwealth-edison-generating-system-trouble",
        ],
        "feature_weights": {"figures": 5, "equations": 28, "quotes": 3, "words": 1},
        "strict_preferred": True,
        "max_per_source": 5,
        "section_limit": 14,
        "start_links": [
            ("Equation Catalog", f"{BASE_URL}/mathematics/", "Equation index and canonical set."),
            ("Canonical Equation Set", f"{BASE_URL}/mathematics/canonical-equation-canon/", "First promoted equation canon."),
            ("Notation Ledger", f"{BASE_URL}/roadmap/notation-ledger/", "Source and modern notation review."),
            ("Interactive Tools", f"{BASE_URL}/tools/", "Calculators and visualizers."),
        ],
    },
    {
        "id": "visual-diagram",
        "title": "Visual And Diagram Route",
        "audience": "Readers who learn through figures, circuits, waveforms, vector diagrams, scan crops, and redraws.",
        "why_it_exists": "Starts from the visual evidence layer and routes all figure-dense sections toward crop verification and modern annotation.",
        "reading_rule": "Treat scan crops as documentary evidence and redraws as reading aids. Verify OCR figure references before quoting captions.",
        "keywords": [
            "figure",
            "diagram",
            "curve",
            "wave",
            "spectrum",
            "vector",
            "circuit",
            "line",
            "loop",
            "characteristic",
            "apparatus",
        ],
        "preferred_sources": [
            "radiation-light-and-illumination",
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-transient-electric-phenomena-oscillations",
            "theory-calculation-electric-apparatus",
            "general-lectures-electrical-engineering",
        ],
        "feature_weights": {"figures": 32, "equations": 6, "quotes": 3, "words": 1},
        "strict_preferred": True,
        "max_per_source": 5,
        "section_limit": 14,
        "start_links": [
            ("Diagram Archive", f"{BASE_URL}/diagrams/", "Curated visual gallery."),
            ("Figure Candidate Atlas", f"{BASE_URL}/diagrams/figure-candidate-atlas/", "All promoted crops and figure references."),
            ("Figure Verification Queue", f"{BASE_URL}/roadmap/figure-verification-queue/", "Crop and caption review cards."),
            ("Book Coverage Atlas", f"{BASE_URL}/book-coverage/", "Find visual density by source."),
        ],
    },
    {
        "id": "apparatus-power",
        "title": "Machines, Apparatus, Power Systems, And Practical Engineering",
        "audience": "Engineers and historically minded readers following Steinmetz from theory into apparatus and grid behavior.",
        "why_it_exists": "Collects machines, power-system trouble, reactors, synchronism, motors, transformers, losses, and operating behavior.",
        "reading_rule": "Use the source sections to see how Steinmetz moves between mathematical theory and engineering diagnosis.",
        "keywords": [
            "apparatus",
            "machine",
            "motor",
            "generator",
            "transformer",
            "reactor",
            "synchronism",
            "short circuit",
            "power",
            "station",
            "system",
            "current limiting",
            "hysteresis motor",
        ],
        "preferred_sources": [
            "theory-calculation-electric-apparatus",
            "commonwealth-edison-generating-system-trouble",
            "theory-calculation-alternating-current-phenomena",
            "theoretical-elements-electrical-engineering",
        ],
        "feature_weights": {"figures": 14, "equations": 12, "quotes": 6, "words": 1},
        "strict_preferred": True,
        "max_per_source": 4,
        "section_limit": 12,
        "start_links": [
            ("Electric Apparatus Coverage", f"{BASE_URL}/book-coverage/theory-calculation-electric-apparatus/", "Machines and apparatus source map."),
            ("Commonwealth Edison Coverage", f"{BASE_URL}/book-coverage/commonwealth-edison-generating-system-trouble/", "Power-system trouble report."),
            ("Power-Limiting Reactors", f"{BASE_URL}/concepts/power-limiting-reactors/", "Concept page for reactor protection."),
            ("Synchronizing Power", f"{BASE_URL}/concepts/synchronizing-power/", "Concept page for synchronism."),
        ],
    },
    {
        "id": "patents-invention",
        "title": "Patents, Invention, And Theory Bridge",
        "audience": "Patent researchers and readers who want to connect Steinmetz's inventions to the theory pages.",
        "why_it_exists": "Separates the seeded patent register and authority workflow from book commentary while linking patents back to concepts and apparatus.",
        "reading_rule": "Start with the patent register, then use the theory bridge and authority queue before treating any patent claim as verified.",
        "keywords": [
            "patent",
            "apparatus",
            "motor",
            "generator",
            "transformer",
            "converter",
            "regulator",
            "system",
            "reactor",
            "hysteresis",
        ],
        "preferred_sources": [
            "theory-calculation-electric-apparatus",
            "commonwealth-edison-generating-system-trouble",
            "theory-calculation-alternating-current-phenomena",
            "theoretical-elements-electrical-engineering",
        ],
        "feature_weights": {"figures": 11, "equations": 8, "quotes": 5, "words": 1},
        "strict_preferred": True,
        "max_per_source": 4,
        "section_limit": 10,
        "start_links": [
            ("Patent Register", f"{BASE_URL}/sources/steinmetz-patents/", "Seeded patent records."),
            ("Seeded Patent Dossiers", f"{BASE_URL}/sources/steinmetz-patents/seeded-patent-dossiers/", "First dossier pages."),
            ("Patent Verification Queue", f"{BASE_URL}/roadmap/patent-verification-queue/", "Authority PDF and claims review."),
            ("Patent Theory Bridge", f"{BASE_URL}/roadmap/patent-to-theory-bridge/", "Concept and apparatus bridge."),
        ],
    },
]


def flatten_sections(coverage: dict[str, Any]) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    for source in coverage.get("sources") or []:
        source_id = source.get("source_id") or source.get("id")
        source_links = source.get("links") or {}
        for section in source.get("sections") or []:
            links = section.get("links") or {}
            themes = compact_list(section.get("top_themes") or [], 6)
            concepts = compact_list(section.get("top_concepts") or [], 6)
            search_text = " ".join(
                [
                    str(source_id or ""),
                    str(source.get("title") or ""),
                    str(section.get("label") or ""),
                    " ".join(themes),
                    " ".join(concepts),
                ]
            )
            sections.append(
                {
                    "source_id": source_id,
                    "source_title": source.get("title"),
                    "source_year": source.get("year"),
                    "section_id": section.get("id"),
                    "section_slug": section.get("slug"),
                    "label": section.get("label"),
                    "status": section.get("status"),
                    "word_count": int(section.get("word_count") or 0),
                    "equation_count": int(section.get("equation_count") or 0),
                    "figure_count": int(section.get("figure_count") or 0),
                    "quote_count": int(section.get("quote_count") or 0),
                    "top_themes": themes,
                    "top_concepts": concepts,
                    "links": {
                        "source_text": site_url(links.get("source_text")),
                        "workbench": site_url(links.get("workbench")),
                        "book_coverage": site_url(source_links.get("coverage")),
                        "source_overview": site_url(source_links.get("curated_source")),
                        "archive": site_url(source_links.get("archive")),
                    },
                    "search_text": slug_text(search_text),
                }
            )
    return sections


def keyword_score(text: str, keywords: list[str]) -> int:
    score = 0
    for keyword in keywords:
        needle = slug_text(keyword).strip()
        if not needle:
            continue
        if needle in text:
            score += 36 if " " in needle else 18
    return score


def source_score(source_id: str, preferred_sources: list[str]) -> int:
    try:
        position = preferred_sources.index(source_id)
    except ValueError:
        return -60 if preferred_sources else 0
    return max(40, 120 - position * 8)


def score_section(section: dict[str, Any], route: dict[str, Any]) -> int:
    weights = route.get("feature_weights") or {}
    score = keyword_score(section["search_text"], route.get("keywords") or [])
    score += source_score(str(section.get("source_id") or ""), route.get("preferred_sources") or [])
    score += int(section.get("figure_count") or 0) * int(weights.get("figures") or 0)
    score += int(section.get("equation_count") or 0) * int(weights.get("equations") or 0)
    score += int(section.get("quote_count") or 0) * int(weights.get("quotes") or 0)
    score += min(24, int(section.get("word_count") or 0) // 1200) * int(weights.get("words") or 0)
    return score


def select_sections(sections: list[dict[str, Any]], route: dict[str, Any]) -> list[dict[str, Any]]:
    scored: list[dict[str, Any]] = []
    preferred_sources = route.get("preferred_sources") or []
    strict_preferred = bool(route.get("strict_preferred"))
    for section in sections:
        if strict_preferred and preferred_sources and section.get("source_id") not in preferred_sources:
            continue
        score = score_section(section, route)
        if score <= 0:
            continue
        enriched = {key: value for key, value in section.items() if key != "search_text"}
        enriched["route_score"] = score
        scored.append(enriched)
    scored.sort(
        key=lambda item: (
            -int(item.get("route_score") or 0),
            str(item.get("source_title") or ""),
            str(item.get("label") or ""),
        )
    )
    limit = int(route.get("section_limit") or 10)
    max_per_source = int(route.get("max_per_source") or 4)
    selected: list[dict[str, Any]] = []
    source_counts: dict[str, int] = {}
    for item in scored:
        source_id = str(item.get("source_id") or "")
        if source_counts.get(source_id, 0) >= max_per_source:
            continue
        selected.append(item)
        source_counts[source_id] = source_counts.get(source_id, 0) + 1
        if len(selected) >= limit:
            break
    return selected


def build_routes(root: Path) -> dict[str, Any]:
    coverage = load_json(root / "processed" / "book_coverage_atlas.json", {})
    sections = flatten_sections(coverage)
    routes: list[dict[str, Any]] = []
    selected_ids: set[str] = set()
    for route in ROUTES:
        route_sections = select_sections(sections, route)
        for section in route_sections:
            selected_ids.add(f"{section.get('source_id')}::{section.get('section_id')}")
        source_count = len({section.get("source_id") for section in route_sections})
        routes.append(
            {
                "id": route["id"],
                "title": route["title"],
                "audience": route["audience"],
                "why_it_exists": route["why_it_exists"],
                "reading_rule": route["reading_rule"],
                "start_links": [
                    {"label": label, "url": url, "note": note}
                    for label, url, note in route.get("start_links", [])
                ],
                "keywords": route.get("keywords") or [],
                "source_count": source_count,
                "section_count": len(route_sections),
                "equation_candidate_count": sum(int(section.get("equation_count") or 0) for section in route_sections),
                "figure_candidate_count": sum(int(section.get("figure_count") or 0) for section in route_sections),
                "quote_candidate_count": sum(int(section.get("quote_count") or 0) for section in route_sections),
                "sections": route_sections,
            }
        )
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": (
            "Guided routes are generated from processed source metadata, theme hits, concept hits, "
            "and candidate equation/figure/quote counts. They are navigation aids, not final scholarly judgments."
        ),
        "route_count": len(routes),
        "source_count": int(coverage.get("source_count") or len(coverage.get("sources") or [])),
        "processed_section_count": len(sections),
        "selected_unique_section_count": len(selected_ids),
        "routes": routes,
    }


def route_index_card(route: dict[str, Any]) -> str:
    return f"""  <a href="#{html_escape(route['id'])}">
    <strong>{html_escape(route['title'])}</strong>
    <span>{html_escape(route['audience'])}</span>
    <small>{html_escape(count_label(route['section_count'], 'selected section'))} from {html_escape(count_label(route['source_count'], 'source'))}</small>
  </a>"""


def start_link_card(link: dict[str, Any]) -> str:
    return f"""  <a href="{html_escape(link.get('url'))}">{html_escape(link.get('label'))}<span>{html_escape(link.get('note'))}</span></a>"""


def section_card(section: dict[str, Any]) -> str:
    links = section.get("links") or {}
    themes = ", ".join(section.get("top_themes") or [])
    concepts = ", ".join(section.get("top_concepts") or [])
    counts = []
    if section.get("equation_count"):
        counts.append(count_label(int(section["equation_count"]), "equation candidate"))
    if section.get("figure_count"):
        counts.append(count_label(int(section["figure_count"]), "figure candidate"))
    if section.get("quote_count"):
        counts.append(count_label(int(section["quote_count"]), "quote candidate"))
    if not counts:
        counts.append(count_label(int(section.get("word_count") or 0), "word"))
    return f"""      <article class="route-section-card">
        <div>
          <h3>{html_escape(section.get('label'))}</h3>
          <p>{html_escape(section.get('source_title'))}</p>
        </div>
        <div>
          <strong>Themes</strong>
          <p>{html_escape(themes or 'General source route')}</p>
          <small>{html_escape(concepts or 'Concept density pending promotion')}</small>
        </div>
        <div>
          <strong>Why it is here</strong>
          <p>{html_escape('; '.join(counts))}</p>
        </div>
        <nav aria-label="Open reading targets for {html_escape(section.get('label'))}">
          <a href="{html_escape(links.get('source_text'))}">Read source text</a>
          <a href="{html_escape(links.get('workbench'))}">Research review</a>
          <a href="{html_escape(links.get('book_coverage'))}">Book map</a>
        </nav>
      </article>"""


def route_panel(route: dict[str, Any], open_panel: bool = False) -> str:
    links = "\n".join(start_link_card(link) for link in route.get("start_links") or [])
    section_cards = "\n".join(section_card(section) for section in route.get("sections") or [])
    open_attr = " open" if open_panel else ""
    return f"""<details class="reading-route-panel" id="{html_escape(route['id'])}"{open_attr}>
  <summary>
    <span>{html_escape(route['title'])}</span>
    <em>{html_escape(count_label(route['section_count'], 'section'))} / {html_escape(count_label(route['source_count'], 'source'))}</em>
  </summary>
  <div class="reading-route-body">
    <p><strong>Audience:</strong> {html_escape(route['audience'])}</p>
    <p><strong>Why this route exists:</strong> {html_escape(route['why_it_exists'])}</p>
    <p><strong>Reading rule:</strong> {html_escape(route['reading_rule'])}</p>
    <div class="source-matrix route-start-links">
{links}
    </div>
    <div class="route-section-list">
{section_cards}
    </div>
  </div>
</details>"""


def build_page(atlas: dict[str, Any]) -> str:
    route_cards = "\n".join(route_index_card(route) for route in atlas["routes"])
    panels = "\n\n".join(route_panel(route, open_panel=index == 0) for index, route in enumerate(atlas["routes"]))
    selected_sections = atlas.get("selected_unique_section_count") or 0
    processed_sections = atlas.get("processed_section_count") or 0
    route_count = atlas.get("route_count") or 0
    source_count = atlas.get("source_count") or 0
    return f"""---
title: "Guided Reading Routes"
description: "Purpose-built study routes through the processed Steinmetz corpus."
---

{GENERATED_NOTE}

This page turns the processed corpus into guided routes. It is not another place to get lost: choose one route, read the first source-text card, and open research review only when you want evidence, diagrams, equations, and verification notes.

<div class="coverage-hero reading-routes-hero">
  <div>
    <p class="home-kicker">Reader pathway layer</p>
    <h1>Guided Routes Through The Steinmetz Corpus</h1>
    <p>Choose a path by purpose, then move from original source text into diagrams, equations, comparisons, and research review without losing attribution.</p>
  </div>
  <div class="coverage-stat-grid">
    <div><strong>{html_escape(route_count)}</strong><p>routes</p><span>entry paths by reader purpose</span></div>
    <div><strong>{html_escape(source_count)}</strong><p>sources</p><span>processed books and reports</span></div>
    <div><strong>{html_escape(processed_sections)}</strong><p>sections</p><span>available in the processed corpus</span></div>
    <div><strong>{html_escape(selected_sections)}</strong><p>route anchors</p><span>unique sections promoted for first reading</span></div>
  </div>
</div>

## How To Use These Routes

<div class="research-passages">
  <section data-layer="source">
    <h3>1. Pick one route</h3>
    <p>If you are new, use First Hour With Steinmetz. If you already know your purpose, jump straight to AC, transients, field language, diagrams, or patents.</p>
  </section>
  <section data-layer="modern">
    <h3>2. Read source first</h3>
    <p>Each card has a direct source-text button. Use that before opening commentary when exact Steinmetz wording matters.</p>
  </section>
  <section data-layer="interpretive">
    <h3>3. Then use the workbench</h3>
    <p>Research review adds concept hits, glossary hits, equation candidates, figure candidates, quote candidates, and verification prompts.</p>
  </section>
</div>

## Route Index

<div class="reading-route-index">
{route_cards}
</div>

## Route Details

{panels}

## Data Export

The generated route data is available at [reading_routes.json]({BASE_URL}/data/reading_routes.json). Candidate counts and route scores are navigation aids, not proof that a passage has been scan-verified.
"""


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    atlas = build_routes(root)
    write_json(root / "processed" / "reading_routes.json", atlas)
    write_text(root / "site" / "src" / "content" / "docs" / "reading-routes" / "index.mdx", build_page(atlas))
    print(
        f"Generated {atlas['route_count']} guided routes across "
        f"{atlas['processed_section_count']} processed sections."
    )


if __name__ == "__main__":
    main()
