#!/usr/bin/env python3
"""Generate a mobile-readiness audit for the public Steinmetz site.

This is a structural audit, not a substitute for real device testing. It keeps
mobile behavior visible as a publication gate by checking the CSS safeguards and
cataloging page patterns that are likely to stress small screens: long source
text readers, wide tables, embedded scans, diagrams, and interactive tools.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_mobile_readiness_audit.py. Do not edit by hand. */}"


CSS_CHECKS: list[dict[str, Any]] = [
    {
        "id": "global_overflow_guard",
        "label": "Global horizontal overflow guard",
        "required": ["overflow-x: hidden", "box-sizing: border-box", "overflow-wrap: anywhere"],
        "why": "Prevents generated tables, code, and source excerpts from widening the entire viewport.",
    },
    {
        "id": "responsive_breakpoints",
        "label": "Responsive breakpoints",
        "required": ["@media (max-width: 820px)", "@media (max-width: 520px)", "@media (max-width: 380px)"],
        "why": "Keeps layout behavior explicit across tablet, phone, and very narrow phone widths.",
    },
    {
        "id": "mobile_grids_collapse",
        "label": "Generated grids collapse safely",
        "required": ["grid-template-columns: 1fr", "minmax(min(100%"],
        "why": "Avoids source cards, reading routes, and visual panels overflowing on phones.",
    },
    {
        "id": "tables_scroll_locally",
        "label": "Tables scroll locally",
        "required": [".codex-status-table", "overflow-x: auto", "-webkit-overflow-scrolling: touch"],
        "why": "Academic tables should scroll inside their own frame instead of breaking the page.",
    },
    {
        "id": "source_text_expands",
        "label": "Source text expands instead of nested scrolling",
        "required": ["pre.source-text-loader", "max-height: none", "white-space: pre-wrap"],
        "why": "Long primary-text pages should read naturally without forcing tiny internal scrollboxes.",
    },
    {
        "id": "mobile_reader_controls",
        "label": "Reader controls fit phone viewports",
        "required": [".codex-reader-controls", "100dvh", "env(safe-area-inset-bottom)", ".codex-control-row"],
        "why": "Source filters, page search, translation shortcuts, and lightbox controls must not cover the page permanently.",
    },
    {
        "id": "media_assets_scale",
        "label": "Images, diagrams, canvases, and iframes scale",
        "required": ["img, svg, video, canvas, iframe", "max-width: 100%", ".source-reader iframe"],
        "why": "Original figures, generated redraws, tools, and source scan embeds must stay within the viewport.",
    },
]


def load_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def docs_files(root: Path) -> list[Path]:
    docs = root / "site" / "src" / "content" / "docs"
    if not docs.exists():
        return []
    return sorted(path for path in docs.rglob("*.mdx") if path.is_file())


def page_slug(root: Path, path: Path) -> str:
    docs = root / "site" / "src" / "content" / "docs"
    rel = path.relative_to(docs).as_posix()
    if rel == "index.mdx":
        return "/"
    if rel.endswith("/index.mdx"):
        return "/" + rel.removesuffix("/index.mdx") + "/"
    return "/" + rel.removesuffix(".mdx") + "/"


def page_link(root: Path, path: Path) -> str:
    return f"{BASE_URL}{page_slug(root, path)}"


def build_css_results(root: Path) -> list[dict[str, Any]]:
    css = load_text(root / "site" / "src" / "styles" / "custom.css")
    results = []
    for check in CSS_CHECKS:
        missing = [pattern for pattern in check["required"] if pattern not in css]
        results.append(
            {
                "id": check["id"],
                "label": check["label"],
                "status": "pass" if not missing else "needs-review",
                "missing_patterns": missing,
                "why": check["why"],
            }
        )
    return results


def classify_page(text: str) -> Counter[str]:
    classes: Counter[str] = Counter()
    if "source-text-loader" in text:
        classes["source_text_reader"] += 1
    if "|" in text and re.search(r"^\| .+ \|$", text, flags=re.MULTILINE):
        classes["markdown_table"] += len(re.findall(r"^\| .+ \|$", text, flags=re.MULTILINE))
    if "<table" in text.lower():
        classes["html_table"] += len(re.findall(r"<table\b", text, flags=re.IGNORECASE))
    if "<iframe" in text.lower() or "source-reader" in text:
        classes["embedded_scan"] += 1
    explorer_components = re.findall(r"<[A-Z][A-Za-z0-9]*Explorer\s*/>", text)
    if "tool-shell" in text or "tool-canvas" in text or explorer_components:
        classes["interactive_tool"] += max(1, len(explorer_components))
    if "codex-visual-card" in text or "figure-source-panel" in text:
        classes["visual_archive"] += 1
    if "source-matrix" in text or "reading-route-index" in text:
        classes["link_grid"] += 1
    if "http" in text:
        long_urls = [url for url in re.findall(r"https?://[^\s)\"'>]+", text) if len(url) > 88]
        if long_urls:
            classes["long_urls"] += len(long_urls)
    return classes


def risk_level(classes: Counter[str]) -> str:
    weighted = (
        classes["source_text_reader"] * 4
        + classes["markdown_table"] // 8
        + classes["html_table"] * 3
        + classes["embedded_scan"] * 3
        + classes["interactive_tool"] * 3
        + classes["visual_archive"] * 2
        + classes["long_urls"]
    )
    if weighted >= 8:
        return "high"
    if weighted >= 4:
        return "medium"
    if weighted > 0:
        return "low"
    return "minimal"


def build_page_results(root: Path) -> dict[str, Any]:
    records = []
    counts: Counter[str] = Counter()
    for path in docs_files(root):
        text = load_text(path)
        classes = classify_page(text)
        if not classes:
            continue
        level = risk_level(classes)
        counts[level] += 1
        for key, count in classes.items():
            counts[f"class:{key}"] += count
        records.append(
            {
                "path": path.relative_to(root).as_posix(),
                "url": page_link(root, path),
                "risk_level": level,
                "patterns": dict(classes),
            }
        )
    order = {"high": 0, "medium": 1, "low": 2, "minimal": 3}
    records.sort(key=lambda item: (order.get(item["risk_level"], 9), item["path"]))
    return {"counts": dict(counts), "records": records}


def build_audit(root: Path) -> dict[str, Any]:
    css_results = build_css_results(root)
    page_results = build_page_results(root)
    pass_count = sum(1 for result in css_results if result["status"] == "pass")
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Structural mobile-readiness audit. It confirms protective CSS exists and identifies high-risk page patterns, but real phones and browser devtools still need manual review before a definitive release.",
        "css_gate_count": len(css_results),
        "css_gate_pass_count": pass_count,
        "css_results": css_results,
        "page_risk_summary": page_results["counts"],
        "high_risk_page_count": page_results["counts"].get("high", 0),
        "medium_risk_page_count": page_results["counts"].get("medium", 0),
        "records": page_results["records"],
        "manual_review_viewports": [
            {"label": "narrow phone", "width": 360, "height": 740},
            {"label": "large phone", "width": 430, "height": 932},
            {"label": "tablet portrait", "width": 768, "height": 1024},
            {"label": "desktop", "width": 1440, "height": 900},
        ],
        "manual_review_rules": [
            "No page-level horizontal scroll.",
            "Generated source text expands naturally or wraps without clipped lines.",
            "Tables scroll inside their own border when too wide.",
            "Bottom reader controls do not hide navigation, citations, or next/previous links.",
            "Source-only filtering, page search, translation shortcuts, and lightbox controls remain reachable by touch.",
            "Diagram, scan, and tool panels fit without overlapping adjacent text.",
        ],
    }


def build_public_page(audit: dict[str, Any]) -> str:
    rows = [
        f"| `{md_escape(result['id'])}` | {md_escape(result['label'])} | `{md_escape(result['status'])}` | {md_escape(result['why'])} |"
        for result in audit["css_results"]
    ]
    risk_rows = []
    for record in audit["records"][:80]:
        patterns = ", ".join(f"{key}: {value}" for key, value in record["patterns"].items())
        risk_rows.append(
            f"| [{md_escape(record['path'])}]({record['url']}) | `{md_escape(record['risk_level'])}` | {md_escape(patterns)} |"
        )
    if not risk_rows:
        risk_rows.append("| No mobile-risk patterns detected. | `pass` | None |")

    viewport_rows = [
        f"| {md_escape(viewport['label'])} | {viewport['width']} x {viewport['height']} |"
        for viewport in audit["manual_review_viewports"]
    ]
    rule_rows = "\n".join(f"- {md_escape(rule)}" for rule in audit["manual_review_rules"])
    summary = audit["page_risk_summary"]

    return f"""---
title: Mobile Readiness Audit
description: Structural mobile and small-screen readiness controls for Steinmetz Decoded.
---

{GENERATED_NOTE}

## Mobile Readiness Audit

Mobile is a first-class reading surface for this archive. This page records the structural CSS gates and page patterns that need recurring small-screen review as the corpus grows.

<div class=\"codex-signal\">
  <div><strong>{audit['css_gate_pass_count']} / {audit['css_gate_count']}</strong><p>Responsive CSS gates currently passing.</p></div>
  <div><strong>{audit['high_risk_page_count']}</strong><p>High-risk pages queued for phone review.</p></div>
  <div><strong>{audit['medium_risk_page_count']}</strong><p>Medium-risk pages queued for phone review.</p></div>
</div>

## CSS Gates

| Gate | Label | Status | Why it matters |
| --- | --- | --- | --- |
{chr(10).join(rows)}

## Page Pattern Summary

| Pattern | Count |
| --- | ---: |
| Source-text readers | {summary.get('class:source_text_reader', 0)} |
| Markdown table rows | {summary.get('class:markdown_table', 0)} |
| HTML tables | {summary.get('class:html_table', 0)} |
| Embedded scans/readers | {summary.get('class:embedded_scan', 0)} |
| Interactive tools | {summary.get('class:interactive_tool', 0)} |
| Visual archive panels | {summary.get('class:visual_archive', 0)} |
| Link grids | {summary.get('class:link_grid', 0)} |
| Long URLs | {summary.get('class:long_urls', 0)} |

## Priority Manual Review Queue

These are not failures. They are the pages most likely to reveal mobile issues during real-device or browser-devtools inspection.

| Page | Risk | Patterns |
| --- | --- | --- |
{chr(10).join(risk_rows)}

## Required Viewports

| Viewport | Size |
| --- | --- |
{chr(10).join(viewport_rows)}

## Manual Review Rules

{rule_rows}

## Publication Rule

Any newly generated page family that introduces wide tables, source transcripts, scan embeds, visual galleries, or tool canvases should either use the existing mobile-safe classes or extend this audit before publication.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate mobile-readiness audit and public roadmap page.")
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    audit = build_audit(root)
    write_json(root / "processed" / "mobile_readiness_audit.json", audit)
    write_text(root / "site" / "src" / "content" / "docs" / "roadmap" / "mobile-readiness-audit.mdx", build_public_page(audit))


if __name__ == "__main__":
    main()
