#!/usr/bin/env python3
"""Generate the next deep-decoding promotion queue.

The corpus is now broadly represented by source readers, book coverage pages,
chapter workbenches, concept concordance, and theme evidence routes. This
script converts that coverage into a prioritized editorial queue: which
sections should be promoted next into richer, curated, long-form decoding pages.
"""

from __future__ import annotations

import argparse
import html
import json
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_deep_decoding_queue.py. Do not edit by hand. */}"

THEME_LABELS = {
    "radiation-light": "Radiation / light",
    "waves-lines": "Waves / transmission lines",
    "dielectricity": "Dielectricity / capacity",
    "fields": "Field language",
    "ether": "Ether references",
    "lightning-surges": "Lightning / surges",
    "alternating-current": "Alternating current",
    "transients": "Transients / damping",
    "complex-quantities": "Complex quantities",
    "magnetism": "Magnetism / hysteresis",
    "impedance-reactance": "Impedance / reactance",
    "machines-apparatus": "Machines / apparatus",
}

LANE_RULES = [
    ("canonical-equation-candidate", "Equation-heavy section; prioritize notation, derivation, modern translation, and worked examples."),
    ("diagram-and-figure-candidate", "Figure-heavy section; prioritize scan crops, caption correction, redraws, and annotations."),
    ("field-language-candidate", "Field, dielectric, magnetic, ether, or force-language section; preserve wording before any interpretation."),
    ("transient-wave-candidate", "Transient, oscillation, surge, or traveling-wave section; connect source math to visual tools."),
    ("apparatus-and-system-candidate", "Machine, apparatus, reactor, motor, generator, or system section; keep industrial context visible."),
    ("hidden-gem-candidate", "Contains quote candidates or unusually concentrated concepts; review for hidden-gem promotion."),
    ("reader-priority-candidate", "High-value orientation section for general readers or first-hour routes."),
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def count_curated_source_pages(root: Path, source_id: str) -> int:
    source_docs = root / "site" / "src" / "content" / "docs" / "sources" / source_id
    if not source_docs.exists():
        return 0
    return len([path for path in source_docs.rglob("*.mdx") if path.is_file()])


def route_memberships(root: Path) -> dict[str, list[str]]:
    routes = load_json(root / "processed" / "reading_routes.json", {}).get("routes", [])
    memberships: dict[str, list[str]] = defaultdict(list)
    for route in routes if isinstance(routes, list) else []:
        title = route.get("title") or route.get("id")
        for section in route.get("sections", []):
            section_id = section.get("section_id")
            if section_id:
                memberships[str(section_id)].append(str(title))
    return memberships


def lane_for(record: dict[str, Any]) -> tuple[str, str]:
    themes = record.get("theme_counts", {}) if isinstance(record.get("theme_counts"), dict) else {}
    equation_count = int(record.get("equation_count") or 0)
    figure_count = int(record.get("figure_count") or 0)
    quote_count = int(record.get("quote_count") or 0)
    field_total = sum(int(themes.get(key, 0) or 0) for key in ("fields", "ether", "dielectricity", "magnetism"))
    transient_total = sum(int(themes.get(key, 0) or 0) for key in ("transients", "lightning-surges", "waves-lines"))
    apparatus_total = int(themes.get("machines-apparatus", 0) or themes.get("machines-apparatus-and-systems", 0) or 0)

    if equation_count >= 18 and equation_count >= figure_count:
        return LANE_RULES[0]
    if figure_count >= 12:
        return LANE_RULES[1]
    if field_total >= 20:
        return LANE_RULES[2]
    if transient_total >= 30:
        return LANE_RULES[3]
    if apparatus_total >= 35:
        return LANE_RULES[4]
    if quote_count:
        return LANE_RULES[5]
    return LANE_RULES[6]


def weighted_score(record: dict[str, Any], memberships: list[str], curated_count: int) -> int:
    themes = record.get("theme_counts", {}) if isinstance(record.get("theme_counts"), dict) else {}
    concept_total = sum(int(item.get("count") or 0) for item in record.get("concept_hits", [])[:8])
    glossary_total = sum(int(item.get("count") or 0) for item in record.get("glossary_hits", [])[:6])
    charter_theme_boost = sum(
        int(themes.get(key, 0) or 0)
        for key in (
            "ether",
            "fields",
            "dielectricity",
            "magnetism",
            "impedance-reactance",
            "alternating-current",
            "complex-quantities",
            "transients",
            "lightning-surges",
            "waves-lines",
        )
    )
    coverage_gap_boost = 30 if curated_count < 2 else 10 if curated_count < 4 else 0
    return int(
        min(int(record.get("word_count") or 0) / 80, 140)
        + int(record.get("equation_count") or 0) * 10
        + int(record.get("figure_count") or 0) * 8
        + int(record.get("quote_count") or 0) * 18
        + min(concept_total / 3, 120)
        + min(glossary_total / 2, 80)
        + min(charter_theme_boost / 4, 160)
        + len(memberships) * 18
        + coverage_gap_boost
    )


def compact_labels(items: list[dict[str, Any]], limit: int = 5) -> list[str]:
    labels = []
    for item in items[:limit]:
        label = item.get("label") or item.get("id")
        count = item.get("count")
        if label and count:
            labels.append(f"{label} ({count})")
        elif label:
            labels.append(str(label))
    return labels


def build_promotion_record(record: dict[str, Any], memberships: list[str], curated_count: int) -> dict[str, Any]:
    lane, lane_note = lane_for(record)
    score = weighted_score(record, memberships, curated_count)
    top_themes = [
        THEME_LABELS.get(theme, str(theme))
        for theme in record.get("top_themes", [])[:5]
    ]
    concept_labels = compact_labels(record.get("concept_hits", []), 6)
    glossary_labels = compact_labels(record.get("glossary_hits", []), 5)
    links = record.get("links", {}) if isinstance(record.get("links"), dict) else {}
    next_actions = [
        "Read the source text first and mark any exact quote as OCR-derived until scan checked.",
        "Add or refine page/scan anchors before promoting direct claims.",
        "Separate Steinmetz wording, modern interpretation, mathematical reconstruction, and interpretive reading.",
    ]
    if int(record.get("equation_count") or 0):
        next_actions.append("Triage equation candidates into false-positive, needs-review, and canonical-candidate groups.")
    if int(record.get("figure_count") or 0):
        next_actions.append("Locate figures in the scan, crop originals, add checksum manifests, and prepare redraw notes.")
    if glossary_labels:
        next_actions.append("Promote unusual terms into glossary pages only with source-location evidence.")
    if "field" in lane or "ether" in " ".join(top_themes).lower():
        next_actions.append("Keep ether-field reading visibly interpretive unless Steinmetz explicitly says the term.")

    return {
        "section_id": record.get("id"),
        "source_id": record.get("source_id"),
        "source_title": record.get("source_title"),
        "year": record.get("year"),
        "label": record.get("label"),
        "location": record.get("location"),
        "status": "candidate-promotion",
        "promotion_score": score,
        "promotion_lane": lane,
        "lane_note": lane_note,
        "route_memberships": memberships,
        "source_curated_page_count": curated_count,
        "counts": {
            "words": record.get("word_count", 0),
            "equations": record.get("equation_count", 0),
            "figures": record.get("figure_count", 0),
            "quotes": record.get("quote_count", 0),
        },
        "top_themes": top_themes,
        "top_concepts": concept_labels,
        "glossary_terms": glossary_labels,
        "opening_excerpt": record.get("opening_excerpt", "")[:850],
        "links": {
            "source_text": links.get("source_text"),
            "workbench": links.get("workbench") or f"{BASE_URL}/chapter-workbench/{record.get('source_id')}/{record.get('slug')}/",
            "source_index": links.get("source_index"),
            "curated_source": links.get("curated_source"),
            "github_text": links.get("github_text"),
            "archive": links.get("archive"),
            "raw_pdf": links.get("raw_pdf"),
        },
        "next_actions": next_actions,
    }


def build_queue(root: Path) -> dict[str, Any]:
    workbench = load_json(root / "processed" / "chapter_workbench.json", {})
    records = workbench.get("records", []) if isinstance(workbench, dict) else []
    memberships = route_memberships(root)
    source_curated_counts = {
        str(source_id): count_curated_source_pages(root, str(source_id))
        for source_id in workbench.get("source_counts", {}).keys()
    }
    promotions = [
        build_promotion_record(record, memberships.get(str(record.get("id")), []), source_curated_counts.get(str(record.get("source_id")), 0))
        for record in records
    ]
    promotions.sort(key=lambda item: (-int(item["promotion_score"]), str(item["source_id"]), str(item["section_id"])))

    balanced: list[dict[str, Any]] = []
    per_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in promotions:
        per_source[str(item["source_id"])].append(item)
    for source_id, items in sorted(per_source.items()):
        for item in items[:5]:
            balanced.append(item)
    balanced.sort(key=lambda item: (-int(item["promotion_score"]), str(item["source_id"]), str(item["section_id"])))

    lane_counts = Counter(item["promotion_lane"] for item in promotions)
    source_counts = Counter(item["source_id"] for item in promotions)
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Deep-decoding promotion queue. It prioritizes sections for richer public writing; it does not certify exact OCR, equations, figures, or interpretations.",
        "total_sections_ranked": len(promotions),
        "balanced_queue_count": len(balanced),
        "lane_counts": dict(sorted(lane_counts.items())),
        "source_counts": dict(sorted(source_counts.items())),
        "records": promotions,
        "balanced_source_queue": balanced,
        "page_blueprint": {
            "required_layers": [
                "Source custody and scan/OCR status",
                "Steinmetz original wording and source location",
                "Plain-English reading",
                "Modern engineering or physics interpretation",
                "Mathematical reconstruction with original notation preserved",
                "Diagram/figure evidence with original crop and redraw when available",
                "Historical context",
                "Tesla-era comparison only where source-relevant",
                "Ether-field interpretive reading clearly labeled as interpretation",
                "Open questions and verification tasks",
            ],
            "promotion_rule": "A queued section becomes a mature deep-decoding page only after source text, scan, equation, diagram, and interpretation boundaries are explicitly labeled.",
        },
    }


def build_queue_table(items: list[dict[str, Any]], limit: int) -> str:
    rows = []
    for index, item in enumerate(items[:limit], start=1):
        links = item.get("links", {})
        source_url = links.get("source_text") or ""
        workbench_url = links.get("workbench") or ""
        title = md_escape(item.get("label"))
        source = md_escape(item.get("source_title"))
        title_cell = f"[{title}]({source_url})" if source_url else title
        workbench = f"[workbench]({workbench_url})" if workbench_url else ""
        counts = item.get("counts", {})
        count_text = f"eq {counts.get('equations', 0)}, fig {counts.get('figures', 0)}, quote {counts.get('quotes', 0)}"
        concepts = ", ".join(item.get("top_concepts", [])[:4])
        rows.append(
            f"| {index} | {title_cell} | {source} | `{item['promotion_lane']}` | {item['promotion_score']} | {md_escape(count_text)} | {md_escape(concepts)} | {workbench} |"
        )
    return "\n".join(rows)


def build_public_page(queue: dict[str, Any]) -> str:
    lane_rows = [
        f"| `{md_escape(lane)}` | {count} |"
        for lane, count in queue["lane_counts"].items()
    ]
    blueprint_rows = "\n".join(f"- {md_escape(layer)}" for layer in queue["page_blueprint"]["required_layers"])
    global_table = build_queue_table(queue["records"], 60)
    balanced_table = build_queue_table(queue["balanced_source_queue"], 55)
    top = queue["records"][0] if queue["records"] else {}
    top_links = top.get("links", {}) if isinstance(top, dict) else {}

    return f"""---
title: Deep Decoding Promotion Queue
description: Generated editorial queue for converting covered Steinmetz sections into richer deep-reading pages.
---

{GENERATED_NOTE}

## Deep Decoding Promotion Queue

The archive now covers the processed corpus broadly. This queue points to the next sections that should become richer, hand-curated decoding pages. It is intentionally conservative: high score means "promote this next," not "this is already verified."

<div class=\"source-text-warning\" data-layer=\"source\">
  <strong>Promotion rule:</strong> source text first, scan verification second, interpretation last. A queued section is a work target, not a finished scholarly claim.
</div>

<div class=\"codex-signal\">
  <div><strong>{queue['total_sections_ranked']}</strong><p>Processed sections ranked.</p></div>
  <div><strong>{queue['balanced_queue_count']}</strong><p>Balanced source-priority candidates.</p></div>
  <div><strong>{html_escape(top.get('promotion_score', 0))}</strong><p>Highest current promotion score.</p></div>
</div>

## Top Candidate

<div class=\"source-access\" data-layer=\"source\">
  <strong>{html_escape(top.get('label', 'No candidate'))}</strong>
  <p>{html_escape(top.get('source_title', ''))} - {html_escape(top.get('location', ''))} - lane: <code>{html_escape(top.get('promotion_lane', ''))}</code></p>
  <p>{html_escape(top.get('lane_note', ''))}</p>
  <div class=\"source-access-actions\">
    <a href=\"{html_escape(top_links.get('source_text', '#'))}\">Read source text</a>
    <a href=\"{html_escape(top_links.get('workbench', '#'))}\">Research review</a>
  </div>
</div>

## Promotion Lanes

| Lane | Sections |
| --- | ---: |
{chr(10).join(lane_rows)}

## Required Deep Page Layers

{blueprint_rows}

## Global Priority Queue

| Rank | Section | Source | Lane | Score | Counts | Concepts | Research Review |
| ---: | --- | --- | --- | ---: | --- | --- | --- |
{global_table}

## Balanced Source Queue

This keeps the next editing pass from over-serving one book while other processed sources remain thin.

| Rank | Section | Source | Lane | Score | Counts | Concepts | Research Review |
| ---: | --- | --- | --- | ---: | --- | --- | --- |
{balanced_table}

## How To Use This Queue

1. Choose a section from the balanced queue unless a specific source has become urgent.
2. Open source text and workbench before writing commentary.
3. Pull exact terms, equations, figures, and quote candidates into a new curated page only with review labels.
4. Add scan crops, equation verification cards, glossary pages, and concept links as the section matures.
5. Leave open questions visible instead of smoothing uncertainty away.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate deep-decoding promotion queue.")
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    queue = build_queue(root)
    write_json(root / "processed" / "deep_decoding_promotion_queue.json", queue)
    write_text(root / "site" / "src" / "content" / "docs" / "roadmap" / "deep-decoding-promotion-queue.mdx", build_public_page(queue))


if __name__ == "__main__":
    main()
