#!/usr/bin/env python3
"""Generate crosslinked math, visual, source, and concept research surfaces.

This script exists to keep the public site from treating a single index page
as the whole feature. It joins the equation atlas, figure candidate atlas,
recreated visual index, and concept dossiers into:

- source-level visual maps under diagrams/source-visuals/
- source-level formula maps under mathematics/source-formula-maps/
- generated math/visual evidence bridges appended to curated concept pages

All outputs remain candidate/review layers unless the underlying source record
is already a promoted crop or canonical equation.
"""

from __future__ import annotations

import argparse
import html
import json
import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = "/Charles-Proteus-Steinmetz-Texts-AI-Decoded"
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_crosslinked_research_surfaces.py. Do not edit by hand. */}"
BEGIN_BRIDGE = "{/* BEGIN GENERATED MATH VISUAL BRIDGE */}"
END_BRIDGE = "{/* END GENERATED MATH VISUAL BRIDGE */}"

FAMILY_LABELS = {
    "apparatus-systems": "Apparatus, Machines, And Power Systems",
    "engineering-math": "Engineering Mathematics Foundations",
    "general-equation-candidates": "General Equation Candidates",
    "impedance-admittance": "Impedance, Reactance, And Admittance",
    "inductance-capacity": "Inductance, Capacity, And Stored Energy",
    "magnetism-hysteresis": "Magnetism, Hysteresis, And Core Loss",
    "power-energy": "Power, Energy, Work, And Efficiency",
    "symbolic-ac": "Symbolic AC And Complex Quantities",
    "transients-oscillation": "Transients, Oscillation, And Damping",
    "waves-radiation": "Waves, Lines, Radiation, And Frequency",
}

CONCEPT_RULES = {
    "admittance": {
        "families": ["impedance-admittance", "symbolic-ac"],
        "keywords": ["admittance", "conductance", "susceptance", "reciprocal"],
        "visual_terms": ["admittance", "conductance", "susceptance", "symbolic-method"],
    },
    "complex-quantities": {
        "families": ["symbolic-ac", "engineering-math"],
        "keywords": ["complex", "imaginary", "quadrature", "j", "vector"],
        "visual_terms": ["complex-quantities", "number", "symbolic-method"],
    },
    "conductance": {
        "families": ["impedance-admittance"],
        "keywords": ["conductance", "admittance", "susceptance"],
        "visual_terms": ["conductance", "admittance"],
    },
    "dielectric-loss": {
        "families": ["inductance-capacity", "power-energy", "magnetism-hysteresis"],
        "keywords": ["dielectric", "capacity", "condenser", "loss", "energy"],
        "visual_terms": ["dielectric-field", "energy-storage"],
    },
    "distributed-constants": {
        "families": ["waves-radiation", "transients-oscillation", "inductance-capacity"],
        "keywords": ["distributed", "line", "capacity", "inductance", "wave", "propagation"],
        "visual_terms": ["distributed-constants", "capacity", "inductance", "waves"],
    },
    "electric-waves": {
        "families": ["waves-radiation", "transients-oscillation"],
        "keywords": ["electric wave", "wave", "radiation", "frequency", "wavelength", "line"],
        "visual_terms": ["waves", "traveling-wave", "distributed-constants"],
    },
    "ether": {
        "families": ["waves-radiation"],
        "keywords": ["ether", "field", "radiation", "wave", "medium"],
        "visual_terms": ["ether", "field-language", "energy-field", "relativity"],
    },
    "harmonics-wave-shape": {
        "families": ["symbolic-ac", "waves-radiation", "engineering-math"],
        "keywords": ["harmonic", "wave shape", "sine", "frequency", "fourier"],
        "visual_terms": ["harmonics", "wave-shape", "fourier-analysis"],
    },
    "hysteresis": {
        "families": ["magnetism-hysteresis", "power-energy"],
        "keywords": ["hysteresis", "magnetic", "loss", "effective resistance"],
        "visual_terms": ["hysteresis", "magnetic-loss", "effective-resistance"],
    },
    "illumination": {
        "families": ["waves-radiation", "power-energy"],
        "keywords": ["illumination", "light", "flux", "photometry", "radiation"],
        "visual_terms": ["waves", "radiation", "harmonics"],
    },
    "impedance": {
        "families": ["impedance-admittance", "symbolic-ac"],
        "keywords": ["impedance", "reactance", "resistance", "phase"],
        "visual_terms": ["admittance", "symbolic-method", "phase"],
    },
    "inductance-capacity": {
        "families": ["inductance-capacity", "transients-oscillation"],
        "keywords": ["inductance", "capacity", "condenser", "magnetic", "dielectric"],
        "visual_terms": ["inductance", "capacity", "dielectric-field", "magnetic-field", "energy-storage"],
    },
    "lightning-surges": {
        "families": ["transients-oscillation", "waves-radiation", "apparatus-systems"],
        "keywords": ["lightning", "surge", "impulse", "traveling wave", "discharge"],
        "visual_terms": ["lightning-surges", "impulse-current", "traveling-wave"],
    },
    "oscillation-damping": {
        "families": ["transients-oscillation"],
        "keywords": ["oscillation", "damping", "decrement", "period", "transient"],
        "visual_terms": ["harmonics", "wave-shape", "traveling-wave"],
    },
    "power-factor": {
        "families": ["impedance-admittance", "power-energy", "symbolic-ac"],
        "keywords": ["power factor", "wattless", "phase", "reactive", "effective"],
        "visual_terms": ["admittance", "phase", "reactance"],
    },
    "power-limiting-reactors": {
        "families": ["apparatus-systems", "impedance-admittance", "power-energy"],
        "keywords": ["reactor", "reactance", "short circuit", "synchronism", "station"],
        "visual_terms": ["power-limiting-reactors", "reactance", "synchronizing-power"],
    },
    "radiation": {
        "families": ["waves-radiation"],
        "keywords": ["radiation", "light", "frequency", "wave length", "spectrum"],
        "visual_terms": ["waves", "radiation", "distributed-constants"],
    },
    "reactance": {
        "families": ["impedance-admittance", "inductance-capacity", "apparatus-systems"],
        "keywords": ["reactance", "inductance", "capacity", "wattless", "impedance"],
        "visual_terms": ["reactance", "admittance", "power-limiting-reactors"],
    },
    "susceptance": {
        "families": ["impedance-admittance"],
        "keywords": ["susceptance", "admittance", "conductance", "capacity"],
        "visual_terms": ["susceptance", "admittance"],
    },
    "symbolic-method": {
        "families": ["symbolic-ac", "engineering-math", "impedance-admittance"],
        "keywords": ["symbolic", "complex", "j", "quadrature", "rectangular", "vector"],
        "visual_terms": ["symbolic-method", "phase", "complex-quantities", "number"],
    },
    "synchronizing-power": {
        "families": ["apparatus-systems", "power-energy", "impedance-admittance"],
        "keywords": ["synchronizing", "synchronism", "reactor", "station", "power"],
        "visual_terms": ["synchronizing-power", "power-limiting-reactors", "reactance"],
    },
    "transient-phenomena": {
        "families": ["transients-oscillation", "waves-radiation"],
        "keywords": ["transient", "temporary", "oscillation", "damping", "surge", "impulse"],
        "visual_terms": ["traveling-wave", "lightning-surges", "distributed-constants"],
    },
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def clean(value: Any, limit: int | None = None) -> str:
    text = "" if value is None else str(value)
    text = re.sub(r"\s+", " ", text).strip()
    if limit and len(text) > limit:
        return text[: limit - 3].rstrip() + "..."
    return text


def md_escape(value: Any) -> str:
    return (
        clean(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )


def html_escape(value: Any) -> str:
    text = html.escape(clean(value), quote=True)
    return (
        text.replace("\\", "&#92;")
        .replace("*", "&#42;")
        .replace("_", "&#95;")
        .replace("~", "&#126;")
        .replace("`", "&#96;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )


def yaml_quote(value: Any) -> str:
    text = clean(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def normalize_token(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "-", clean(value).lower()).strip("-")


def source_title(source: dict[str, Any]) -> str:
    return str(source.get("title") or source.get("source_title") or source.get("source_id") or "")


def source_links(source_id: str) -> dict[str, str]:
    return {
        "coverage": f"{BASE_URL}/book-coverage/{source_id}/",
        "source_text": f"{BASE_URL}/source-texts/{source_id}/",
        "workbench": f"{BASE_URL}/chapter-workbench/{source_id}/",
        "visual_map": f"{BASE_URL}/diagrams/source-visuals/{source_id}/",
        "formula_map": f"{BASE_URL}/mathematics/source-formula-maps/{source_id}/",
    }


def records_by_source(records: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        source_id = str(record.get("source_id") or "")
        if source_id:
            grouped[source_id].append(record)
    return grouped


def visual_matches_terms(record: dict[str, Any], terms: list[str]) -> bool:
    haystack = " ".join(
        [
            clean(record.get("title")),
            clean(record.get("subtitle")),
            " ".join(clean(item) for item in record.get("concepts") or []),
            " ".join(clean(item) for item in record.get("sources") or []),
        ]
    ).lower()
    return any(term.lower() in haystack or normalize_token(term) in haystack for term in terms)


def text_matches_keywords(record: dict[str, Any], keywords: list[str]) -> bool:
    haystack = " ".join(
        [
            clean(record.get("original_form")),
            clean(record.get("caption")),
            clean(record.get("section_label")),
            clean(record.get("source_title")),
        ]
    ).lower()
    return any(keyword.lower() in haystack for keyword in keywords)


def family_link(family: str) -> str:
    return f"{BASE_URL}/mathematics/equation-atlas/{family}/"


def source_card_grid(source: dict[str, Any], fig_count: int, eq_count: int, visual_count: int, promoted_count: int) -> str:
    source_id = str(source.get("source_id"))
    title = html_escape(source_title(source))
    links = source_links(source_id)
    return f"""<div class="evidence-source-card">
  <h3>{title}</h3>
  <p><strong>{eq_count}</strong> formula candidates, <strong>{fig_count}</strong> figure candidates, <strong>{promoted_count}</strong> promoted crops, <strong>{visual_count}</strong> modern guide diagrams.</p>
  <p><a href="{links['visual_map']}">visual map</a> - <a href="{links['formula_map']}">formula map</a> - <a href="{links['source_text']}">source text</a> - <a href="{links['workbench']}">workbench</a></p>
</div>"""


def formula_rows(records: list[dict[str, Any]], limit: int = 12) -> str:
    rows = []
    sorted_records = sorted(records, key=lambda item: (-int(item.get("quality_score") or 0), str(item.get("id"))))
    for record in sorted_records[:limit]:
        links = record.get("links") or {}
        source_text = links.get("source_text") or links.get("source_text_index") or "#"
        workbench = links.get("workbench") or links.get("workbench_index") or "#"
        rows.append(
            "<tr>"
            f"<td><code>{html_escape(record.get('id'))}</code><br/><small>{html_escape(record.get('quality_band'))}</small></td>"
            f"<td>{html_escape(record.get('family'))}</td>"
            f"<td><code>{html_escape(clean(record.get('original_form'), 180))}</code></td>"
            f"<td><a href=\"{html_escape(source_text)}\">source</a><br/><a href=\"{html_escape(workbench)}\">workbench</a></td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="4">No formula candidates routed here yet.</td></tr>')
    return "\n".join(rows)


def figure_rows(records: list[dict[str, Any]], limit: int = 14) -> str:
    rows = []
    sorted_records = sorted(records, key=lambda item: (int(item.get("line_start") or 9999999), int(item.get("figure_number") or 9999999)))
    for record in sorted_records[:limit]:
        links = record.get("links") or {}
        source_text = links.get("source_text") or links.get("source_text_index") or "#"
        workbench = links.get("workbench") or links.get("workbench_index") or "#"
        fig_no = record.get("figure_number")
        figure_label = f"Fig. {fig_no}" if fig_no is not None else "Figure candidate"
        rows.append(
            "<tr>"
            f"<td><code>{html_escape(record.get('id'))}</code><br/><small>{html_escape(figure_label)}</small></td>"
            f"<td>{html_escape(clean(record.get('caption'), 220))}</td>"
            f"<td>{html_escape(record.get('section_label'))}</td>"
            f"<td><a href=\"{html_escape(source_text)}\">source</a><br/><a href=\"{html_escape(workbench)}\">workbench</a></td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="4">No figure candidates routed here yet.</td></tr>')
    return "\n".join(rows)


def promoted_cards(records: list[dict[str, Any]]) -> str:
    cards = []
    for record in records:
        cards.append(
            f"""<div class="codex-visual-card">
  <img src="{html_escape(record.get('public_url'))}" alt="Promoted Steinmetz scan crop {html_escape(record.get('id'))}" />
  <div>
    <strong>{html_escape(record.get('id'))}</strong>
    <p>{html_escape(record.get('source_location'))}</p>
    <p><a href="{html_escape(record.get('public_url'))}">Open crop</a> - <a href="{BASE_URL}/roadmap/figure-verification-queue/">verification queue</a></p>
  </div>
</div>"""
        )
    if not cards:
        return '<p>No promoted original crops are attached to this source yet. Use the figure candidates below as crop targets.</p>'
    return "\n".join(cards)


def recreated_cards(records: list[dict[str, Any]], compact: bool = False) -> str:
    cards = []
    for record in records:
        image_line = ""
        if not compact:
            image_line = f'  <img src="{html_escape(record.get("public_url"))}" alt="{html_escape(record.get("title"))}" />\n'
        concepts = ", ".join(clean(item) for item in record.get("concepts") or [])
        cards.append(
            f"""<div class="codex-visual-card">
{image_line}  <div>
    <strong>{html_escape(record.get('title'))}</strong>
    <p>{html_escape(record.get('subtitle'))}</p>
    <p><small>{html_escape(concepts)}</small></p>
    <p><a href="{html_escape(record.get('public_url'))}">Open SVG</a> - <a href="{BASE_URL}/diagrams/recreated-visual-index/">recreated visual index</a></p>
  </div>
</div>"""
        )
    if not cards:
        return '<p>No modern guide diagrams are currently keyed to this source.</p>'
    return "\n".join(cards)


def extracted_cards(records: list[dict[str, Any]]) -> str:
    cards = []
    for record in records[:12]:
        cards.append(
            f"""<div class="codex-visual-card extracted-visual-card">
  <img src="{html_escape(record.get('public_url'))}" alt="Extracted scan-image candidate for page {html_escape(record.get('pdf_page_number'))}" />
  <div>
    <strong>PDF page {html_escape(record.get('pdf_page_number'))}</strong>
    <p>Extracted review image - not a final figure crop.</p>
    <p><a href="{html_escape(record.get('public_url'))}">Open image</a> - <a href="{BASE_URL}/diagrams/extracted-visual-candidates/{html_escape(record.get('source_id'))}/">source gallery</a></p>
  </div>
</div>"""
        )
    if not cards:
        return '<p>No extracted visual candidates are promoted for this source yet.</p>'
    return "\n".join(cards)


def build_source_meta(equation_atlas: dict[str, Any], figure_atlas: dict[str, Any]) -> dict[str, dict[str, Any]]:
    sources: dict[str, dict[str, Any]] = {}
    for source in equation_atlas.get("source_summaries") or []:
        source_id = str(source.get("source_id"))
        sources[source_id] = {
            "source_id": source_id,
            "title": source.get("title"),
            "year": source.get("year"),
        }
    for source in figure_atlas.get("source_summaries") or []:
        source_id = str(source.get("source_id"))
        sources.setdefault(source_id, {"source_id": source_id})
        sources[source_id]["title"] = sources[source_id].get("title") or source.get("title")
        sources[source_id]["year"] = sources[source_id].get("year") or source.get("year")
    return sources


def source_formula_page(source: dict[str, Any], equations: list[dict[str, Any]]) -> str:
    source_id = str(source.get("source_id"))
    title = source_title(source)
    links = source_links(source_id)
    family_counts = Counter(str(record.get("family") or "general-equation-candidates") for record in equations)
    family_rows = "\n".join(
        f"| [{md_escape(FAMILY_LABELS.get(family, family))}]({family_link(family)}) | {count} |"
        for family, count in family_counts.most_common()
    ) or "| No formula families yet. | 0 |"
    strong_count = sum(1 for record in equations if record.get("quality_band") == "strong-formula-candidate")
    reviewable_count = sum(1 for record in equations if "reviewable" in str(record.get("quality_band")))
    return f"""---
title: {yaml_quote(title + " Formula Map")}
description: {yaml_quote("Source-routed formula candidates for " + title + ".")}
---

{GENERATED_NOTE}

## Formula Map

<div class="source-text-warning" data-layer="source">
  <strong>Review layer:</strong> these are OCR/PDF-text formula candidates. Promote only after scan verification, mathematical transcription, and notation review.
</div>

<div class="codex-signal">
  <div><strong>{len(equations)}</strong><p>Formula and equation candidates.</p></div>
  <div><strong>{strong_count}</strong><p>Strong formula candidates.</p></div>
  <div><strong>{reviewable_count}</strong><p>Reviewable relation candidates.</p></div>
</div>

<div class="source-matrix">
  <a href="{links['source_text']}">Read source text<span>Open the processed text reader for this source.</span></a>
  <a href="{links['workbench']}">Use chapter workbench<span>See equations beside concepts, figures, glossary hits, and source snippets.</span></a>
  <a href="{links['visual_map']}">Open visual map<span>See promoted crops, figure candidates, and modern guide diagrams for the same source.</span></a>
  <a href="{BASE_URL}/mathematics/equation-atlas/">Open equation atlas<span>Compare this source against the full formula-family map.</span></a>
</div>

## Formula Families

| Family | Candidates |
| --- | ---: |
{family_rows}

## Highest-Priority Candidates

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>Family</th><th>OCR/PDF text</th><th>Routes</th></tr>
  </thead>
  <tbody>
{formula_rows(equations, 30)}
  </tbody>
</table>
"""


def source_visual_page(
    source: dict[str, Any],
    figures: list[dict[str, Any]],
    promoted: list[dict[str, Any]],
    visuals: list[dict[str, Any]],
    equations: list[dict[str, Any]],
    extracted: list[dict[str, Any]],
) -> str:
    source_id = str(source.get("source_id"))
    title = source_title(source)
    links = source_links(source_id)
    return f"""---
title: {yaml_quote(title + " Visual Map")}
description: {yaml_quote("Diagram, figure, and visual-guide routing map for " + title + ".")}
---

{GENERATED_NOTE}

## Visual Map

<div class="source-text-warning" data-layer="source">
  <strong>Review layer:</strong> candidate figure references are OCR/PDF-text leads. Promoted crops are documentary scan crops that still need second-pass bibliographic and crop-coordinate review. Modern guide diagrams are explanatory reconstructions, not historical figure evidence.
</div>

<div class="codex-signal">
  <div><strong>{len(promoted)}</strong><p>Promoted original crops.</p></div>
  <div><strong>{len(extracted)}</strong><p>Extracted visual-review images.</p></div>
  <div><strong>{len(figures)}</strong><p>Candidate figure references.</p></div>
  <div><strong>{len(visuals)}</strong><p>Modern guide diagrams keyed here.</p></div>
</div>

<div class="source-matrix">
  <a href="{links['source_text']}">Read source text<span>Open the processed text reader for this source.</span></a>
  <a href="{links['workbench']}">Use chapter workbench<span>See figure references beside equations, concepts, and glossary hits.</span></a>
  <a href="{links['formula_map']}">Open formula map<span>Read the matching source-routed math layer.</span></a>
  <a href="{BASE_URL}/diagrams/extracted-visual-candidates/{source_id}/">Open extracted visuals<span>Bounded scan-image review candidates for this source.</span></a>
  <a href="{BASE_URL}/diagrams/figure-candidate-atlas/">Open full figure atlas<span>Compare this source against the whole visual candidate layer.</span></a>
</div>

## Promoted Original Crops

<div class="codex-visual-grid">
{promoted_cards(promoted)}
</div>

## Extracted Visual Review Candidates

<div class="codex-visual-grid extracted-visual-grid">
{extracted_cards(extracted)}
</div>

## Modern Guide Diagrams Keyed To This Source

<div class="codex-visual-grid">
{recreated_cards(visuals)}
</div>

## Candidate Figure References

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>Caption lead</th><th>Section</th><th>Routes</th></tr>
  </thead>
  <tbody>
{figure_rows(figures, 60)}
  </tbody>
</table>
"""


def source_formula_index(
    sources: list[dict[str, Any]],
    equations_by_source: dict[str, list[dict[str, Any]]],
    figures_by_source: dict[str, list[dict[str, Any]]],
    promoted_by_source: dict[str, list[dict[str, Any]]],
    visuals_by_source: dict[str, list[dict[str, Any]]],
) -> str:
    cards = "\n".join(
        source_card_grid(
            source,
            len(figures_by_source.get(str(source.get("source_id")), [])),
            len(equations_by_source.get(str(source.get("source_id")), [])),
            len(visuals_by_source.get(str(source.get("source_id")), [])),
            len(promoted_by_source.get(str(source.get("source_id")), [])),
        )
        for source in sources
    )
    return f"""---
title: Source Formula Maps
description: Source-by-source equation and formula routing for the processed Steinmetz corpus.
---

{GENERATED_NOTE}

## Source Formula Maps

This index prevents the math layer from hiding inside one giant equation page. Each source below has its own formula map with family counts, top OCR/PDF-text candidates, and links back to source text, workbench, and visual maps.

<div class="source-text-warning" data-layer="source">
  <strong>Use rule:</strong> formula candidates are review leads, not final transcriptions. Use them to find passages, then verify against scans before canonical use.
</div>

<div class="evidence-source-grid">
{cards}
</div>
"""


def source_visual_index(
    sources: list[dict[str, Any]],
    equations_by_source: dict[str, list[dict[str, Any]]],
    figures_by_source: dict[str, list[dict[str, Any]]],
    promoted_by_source: dict[str, list[dict[str, Any]]],
    visuals_by_source: dict[str, list[dict[str, Any]]],
) -> str:
    cards = "\n".join(
        source_card_grid(
            source,
            len(figures_by_source.get(str(source.get("source_id")), [])),
            len(equations_by_source.get(str(source.get("source_id")), [])),
            len(visuals_by_source.get(str(source.get("source_id")), [])),
            len(promoted_by_source.get(str(source.get("source_id")), [])),
        )
        for source in sources
    )
    return f"""---
title: Source Visual Maps
description: Source-by-source visual routing for Steinmetz diagrams, figure candidates, and guide diagrams.
---

{GENERATED_NOTE}

## Source Visual Maps

This index expands the diagram archive from a gallery into a source-by-source research system. Every processed source gets a visual map, even when it has no promoted scan crop yet, so readers can see what still needs extraction.

<div class="source-text-warning" data-layer="source">
  <strong>Use rule:</strong> candidate figure captions are OCR/PDF-text leads. Modern guide diagrams are explanatory reconstructions. Only promoted scan crops are documentary image assets, and even those still require second-pass review.
</div>

<div class="evidence-source-grid">
{cards}
</div>
"""


def build_concept_bridge(
    dossier: dict[str, Any],
    equations_by_source: dict[str, list[dict[str, Any]]],
    figures_by_source: dict[str, list[dict[str, Any]]],
    visuals: list[dict[str, Any]],
) -> dict[str, Any]:
    page_slug = str(dossier.get("page_slug"))
    rule = CONCEPT_RULES.get(page_slug, {"families": [], "keywords": [page_slug.replace("-", " ")], "visual_terms": [page_slug]})
    source_ids = [str(source.get("source_id")) for source in dossier.get("sources") or [] if source.get("source_id")]
    keyword_terms = list(rule.get("keywords") or [])
    families = set(rule.get("families") or [])

    equation_records: list[dict[str, Any]] = []
    for source_id in source_ids:
        for record in equations_by_source.get(source_id, []):
            if str(record.get("family")) in families or text_matches_keywords(record, keyword_terms):
                equation_records.append(record)

    figure_records: list[dict[str, Any]] = []
    for source_id in source_ids:
        for record in figures_by_source.get(source_id, []):
            if text_matches_keywords(record, keyword_terms):
                figure_records.append(record)
    if not figure_records:
        for source_id in source_ids[:4]:
            figure_records.extend(figures_by_source.get(source_id, [])[:3])

    visual_terms = list(rule.get("visual_terms") or [])
    visual_records = [
        record
        for record in visuals
        if visual_matches_terms(record, visual_terms if visual_terms else keyword_terms)
    ]
    formula_source_counts = Counter(str(record.get("source_id")) for record in equation_records)
    figure_source_counts = Counter(str(record.get("source_id")) for record in figure_records)

    return {
        "page_slug": page_slug,
        "page_title": dossier.get("page_title"),
        "source_ids": source_ids,
        "families": sorted(families),
        "keywords": keyword_terms,
        "formula_candidate_count": len(equation_records),
        "figure_candidate_count": len(figure_records),
        "modern_visual_count": len(visual_records),
        "top_formula_candidates": sorted(equation_records, key=lambda item: -int(item.get("quality_score") or 0))[:8],
        "top_figure_candidates": figure_records[:8],
        "modern_visuals": visual_records[:6],
        "formula_source_counts": dict(formula_source_counts),
        "figure_source_counts": dict(figure_source_counts),
    }


def concept_bridge_markdown(bridge: dict[str, Any]) -> str:
    visual_cards = recreated_cards(bridge["modern_visuals"], compact=True)
    family_links = " - ".join(
        f"[{md_escape(FAMILY_LABELS.get(family, family))}]({family_link(family)})"
        for family in bridge.get("families") or []
    ) or "No formula family rule assigned yet."

    source_map_links = []
    source_ids = bridge.get("source_ids") or []
    for source_id in source_ids[:6]:
        source_map_links.append(
            f'<a href="{BASE_URL}/diagrams/source-visuals/{html_escape(source_id)}/">{html_escape(source_id)} visuals</a>'
        )
        source_map_links.append(
            f'<a href="{BASE_URL}/mathematics/source-formula-maps/{html_escape(source_id)}/">{html_escape(source_id)} formulas</a>'
        )
    source_link_text = " - ".join(source_map_links) if source_map_links else "No source maps are linked yet."

    formula_preview = formula_rows(bridge["top_formula_candidates"], 8)
    figure_preview = figure_rows(bridge["top_figure_candidates"], 8)
    return f"""{BEGIN_BRIDGE}

## Math And Visual Evidence Map

<div class="source-text-warning" data-layer="source">
  <strong>Generated bridge:</strong> this section crosslinks the concept page with the formula atlas, figure atlas, source visual maps, and source formula maps. It is a routing layer, not final interpretation.
</div>

<div class="codex-signal">
  <div><strong>{bridge['formula_candidate_count']}</strong><p>Formula candidates routed to this concept.</p></div>
  <div><strong>{bridge['figure_candidate_count']}</strong><p>Figure candidates routed to this concept.</p></div>
  <div><strong>{bridge['modern_visual_count']}</strong><p>Modern guide diagrams related to this concept.</p></div>
</div>

### Formula Families To Review

{family_links}

### Source Maps For This Concept

<div class="evidence-inline-links">
  {source_link_text}
</div>

### Related Modern Guide Diagrams

<div class="codex-visual-grid">
{visual_cards}
</div>

### Highest-Priority Formula Leads

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>Family</th><th>OCR/PDF text</th><th>Routes</th></tr>
  </thead>
  <tbody>
{formula_preview}
  </tbody>
</table>

### Highest-Priority Figure Leads

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>Caption lead</th><th>Section</th><th>Routes</th></tr>
  </thead>
  <tbody>
{figure_preview}
  </tbody>
</table>

{END_BRIDGE}
"""


def replace_bridge(existing: str, generated: str) -> str:
    pattern = re.compile(re.escape(BEGIN_BRIDGE) + r".*?" + re.escape(END_BRIDGE), flags=re.DOTALL)
    if pattern.search(existing):
        return pattern.sub(lambda _match: generated.strip(), existing).rstrip() + "\n"
    return existing.rstrip() + "\n\n" + generated.strip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate source and concept crosslinked math/visual surfaces.")
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    equation_atlas = load_json(root / "processed" / "equation_atlas.json", {})
    figure_atlas = load_json(root / "processed" / "figure_candidate_atlas.json", {})
    visual_index = load_json(root / "processed" / "recreated_visual_index.json", {})
    dossier_index = load_json(root / "processed" / "concept_page_dossiers.json", {})
    extracted_index = load_json(root / "processed" / "extracted_visual_review_index.json", {})

    equations = list(equation_atlas.get("records") or [])
    figures = list(figure_atlas.get("candidate_records") or [])
    promoted = list(figure_atlas.get("promoted_original_figures") or [])
    visuals = list(visual_index.get("records") or [])
    equations_by_source = records_by_source(equations)
    figures_by_source = records_by_source(figures)
    promoted_by_source = records_by_source(promoted)
    visuals_by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for visual in visuals:
        for source_id in visual.get("sources") or []:
            visuals_by_source[str(source_id)].append(visual)
    extracted_by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for source_record in extracted_index.get("sources") or []:
        source_id = str(source_record.get("source_id") or "")
        if source_id:
            extracted_by_source[source_id].extend(source_record.get("records") or [])

    sources = sorted(build_source_meta(equation_atlas, figure_atlas).values(), key=lambda item: source_title(item))
    visual_root = root / "site" / "src" / "content" / "docs" / "diagrams" / "source-visuals"
    formula_root = root / "site" / "src" / "content" / "docs" / "mathematics" / "source-formula-maps"

    for source in sources:
        source_id = str(source.get("source_id"))
        write_text(
            visual_root / f"{source_id}.mdx",
            source_visual_page(
                source,
                figures_by_source.get(source_id, []),
                promoted_by_source.get(source_id, []),
                visuals_by_source.get(source_id, []),
                equations_by_source.get(source_id, []),
                extracted_by_source.get(source_id, []),
            ),
        )
        write_text(
            formula_root / f"{source_id}.mdx",
            source_formula_page(source, equations_by_source.get(source_id, [])),
        )

    write_text(
        visual_root / "index.mdx",
        source_visual_index(sources, equations_by_source, figures_by_source, promoted_by_source, visuals_by_source),
    )
    write_text(
        formula_root / "index.mdx",
        source_formula_index(sources, equations_by_source, figures_by_source, promoted_by_source, visuals_by_source),
    )

    bridges = []
    docs_concepts = root / "site" / "src" / "content" / "docs" / "concepts"
    for dossier in dossier_index.get("dossiers") or []:
        page_slug = str(dossier.get("page_slug") or "")
        path = docs_concepts / f"{page_slug}.mdx"
        if not page_slug or not path.exists():
            continue
        bridge = build_concept_bridge(dossier, equations_by_source, figures_by_source, visuals)
        existing = path.read_text(encoding="utf-8")
        write_text(path, replace_bridge(existing, concept_bridge_markdown(bridge)))
        bridges.append(bridge)

    output = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Crosslinked research surfaces route source, math, visual, and concept evidence. Candidate records require scan and editorial verification.",
        "source_count": len(sources),
        "concept_bridge_count": len(bridges),
        "total_formula_candidates": len(equations),
        "total_figure_candidates": len(figures),
        "total_promoted_crops": len(promoted),
        "total_modern_visual_guides": len(visuals),
        "total_extracted_visual_candidates": sum(len(records) for records in extracted_by_source.values()),
        "sources": [
            {
                "source_id": source.get("source_id"),
                "title": source_title(source),
                "year": source.get("year"),
                "formula_candidates": len(equations_by_source.get(str(source.get("source_id")), [])),
                "figure_candidates": len(figures_by_source.get(str(source.get("source_id")), [])),
                "promoted_crops": len(promoted_by_source.get(str(source.get("source_id")), [])),
                "extracted_visual_candidates": len(extracted_by_source.get(str(source.get("source_id")), [])),
                "modern_visual_guides": len(visuals_by_source.get(str(source.get("source_id")), [])),
                "links": source_links(str(source.get("source_id"))),
            }
            for source in sources
        ],
        "concept_bridges": [
            {
                "page_slug": bridge.get("page_slug"),
                "page_title": bridge.get("page_title"),
                "formula_candidate_count": bridge.get("formula_candidate_count"),
                "figure_candidate_count": bridge.get("figure_candidate_count"),
                "modern_visual_count": bridge.get("modern_visual_count"),
                "families": bridge.get("families"),
                "keywords": bridge.get("keywords"),
            }
            for bridge in bridges
        ],
    }
    write_json(root / "processed" / "crosslinked_research_surfaces.json", output)
    write_json(root / "site" / "public" / "data" / "crosslinked_research_surfaces.json", output)
    print(
        f"Generated {len(sources)} source visual maps, {len(sources)} source formula maps, and {len(bridges)} concept bridges."
    )


if __name__ == "__main__":
    main()
