#!/usr/bin/env python3
"""Generate the Steinmetz corpus completion matrix.

This is an authority and completion layer, not another summary page. It joins
the bibliography intake manifest, official source expansion manifest, seeded
source catalog, processed artifacts, and patent register so the project can see
exactly which Steinmetz works are processed, which are only registered, and
which must be acquired before the archive can honestly call itself complete.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_corpus_completion_matrix.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def frontmatter_string(value: Any) -> str:
    return json.dumps("" if value is None else str(value), ensure_ascii=False)


def count_records(path: Path) -> int:
    data = load_json(path, [])
    return len(data) if isinstance(data, list) else 0


def processed_counts(root: Path, source_id: str | None) -> dict[str, int]:
    if not source_id:
        return {key: 0 for key in ["chapters", "equations", "figures", "concepts", "glossary", "quotes"]}
    base = root / "processed" / source_id
    return {
        "chapters": count_records(base / "chapters.json"),
        "equations": count_records(base / "equations.json"),
        "figures": count_records(base / "figures.json"),
        "concepts": count_records(base / "concepts.json"),
        "glossary": count_records(base / "glossary.json"),
        "quotes": count_records(base / "quotes.json"),
    }


def normalized_priority(priority: Any) -> str:
    value = str(priority or "unranked").lower()
    if value in {"critical", "high", "medium", "low"}:
        return value
    return "unranked"


def sort_key(record: dict[str, Any]) -> tuple[int, int, int, str]:
    priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "unranked": 4}
    state_order = {
        "processed-corpus": 0,
        "ocr-seeded-corpus": 1,
        "registered-authority-target": 2,
        "planned-acquisition": 3,
        "archival-target": 4,
        "patent-corpus-target": 5,
        "secondary-context": 6,
    }
    year = record.get("year")
    year_value = int(year) if isinstance(year, int) else 9999
    return (
        priority_order.get(record["priority"], 9),
        state_order.get(record["coverage_state"], 9),
        year_value,
        str(record["title"]).lower(),
    )


def first_authority_url(entry: dict[str, Any]) -> str | None:
    for ref in entry.get("external_refs", []) or []:
        url = ref.get("url")
        if url:
            return str(url)
    for ref in entry.get("authority_refs", []) or []:
        url = ref.get("url")
        if url:
            return str(url)
    return None


def source_link(source_id: str | None, kind: str = "source") -> str | None:
    if not source_id:
        return None
    if kind == "text":
        return f"{BASE_URL}/source-texts/{source_id}/"
    if kind == "workbench":
        return f"{BASE_URL}/chapter-workbench/{source_id}/"
    if kind == "coverage":
        return f"{BASE_URL}/book-coverage/{source_id}/"
    return f"{BASE_URL}/sources/{source_id}/"


def classify_record(entry: dict[str, Any], source_ids: set[str]) -> tuple[str, str, list[str]]:
    status = str(entry.get("status", "")).lower()
    source_type = str(entry.get("source_type", "")).lower()
    local_source = entry.get("related_local_source_id")
    priority = normalized_priority(entry.get("priority"))
    actions: list[str] = []

    if local_source in source_ids:
        if "ocr" in status:
            coverage_state = "ocr-seeded-corpus"
        else:
            coverage_state = "processed-corpus"
        completion_class = "seeded-source"
        actions.append("Scan-check title page, edition statement, page starts, equations, and figure references.")
        actions.append("Promote strongest passages into concept, math, diagram, and glossary pages.")
        return coverage_state, completion_class, actions

    if "patent" in source_type or "patent" in status or "patents" in str(entry.get("title", "")).lower():
        return (
            "patent-corpus-target",
            "patent-authority",
            [
                "Expand beyond examples into the full authority-checked patent corpus.",
                "Attach PDF, drawings, claims, apparatus interpretation, and theory links to each patent.",
            ],
        )

    if "archival" in source_type or "archival" in status:
        return (
            "archival-target",
            "archival-custody",
            [
                "Record finding-aid metadata and request or link public finding-aid authority.",
                "Do not treat archival content as quoted text until scans or transcriptions are in custody.",
            ],
        )

    if "registered" in status:
        actions.append("Acquire primary scan, publisher PDF, or public page-image source.")
        actions.append("Create raw custody manifest, OCR, page map, candidate equations, figures, concepts, glossary, and quotes.")
        return "registered-authority-target", "critical-frontier" if priority == "critical" else "authority-target", actions

    if "planned" in status or "verification" in status:
        actions.append("Locate the best public-domain or institutional authority copy.")
        actions.append("Run the standard source pipeline before any claims are promoted.")
        return "planned-acquisition", "planned-source", actions

    if "posthumous" in status or priority == "low":
        return (
            "secondary-context",
            "context-or-late-source",
            [
                "Verify chronology and authorship before using for historical interpretation.",
                "Keep late/posthumous status visible on public pages.",
            ],
        )

    actions.append("Review against authority portals and decide whether to process, defer, or explicitly exclude.")
    return "planned-acquisition", "unclassified-intake", actions


def merge_official_metadata(entries: list[dict[str, Any]], official_records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    official_by_id = {record.get("work_id"): record for record in official_records if isinstance(record, dict)}
    merged = []
    for entry in entries:
        record = dict(entry)
        official = official_by_id.get(entry.get("work_id"))
        if official:
            record.setdefault("authority_refs", official.get("authority_refs", []))
            record.setdefault("repo_action", official.get("repo_action"))
            record.setdefault("why_it_matters", official.get("why_it_matters"))
            if "priority" not in record and "priority" in official:
                record["priority"] = official["priority"]
            if official.get("related_local_source_id") and not record.get("related_local_source_id"):
                record["related_local_source_id"] = official["related_local_source_id"]
        merged.append(record)
    return merged


def build_matrix(root: Path) -> dict[str, Any]:
    bibliography = load_json(root / "sources" / "steinmetz_bibliography_manifest.json", {})
    official = load_json(root / "sources" / "official_source_intake_manifest.json", {})
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    patent_register = load_json(root / "sources" / "steinmetz_patents" / "patent_register.json", {})

    entries = bibliography.get("entries", []) if isinstance(bibliography, dict) else []
    official_records = official.get("records", []) if isinstance(official, dict) else []
    entries = merge_official_metadata(entries, official_records)

    source_ids = {str(source.get("source_id")) for source in source_catalog if isinstance(source, dict)}
    source_by_id = {str(source.get("source_id")): source for source in source_catalog if isinstance(source, dict)}
    records: list[dict[str, Any]] = []

    for entry in entries:
        local_source = entry.get("related_local_source_id")
        if not local_source and str(entry.get("work_id")) in source_ids:
            local_source = str(entry.get("work_id"))
        if local_source not in source_ids:
            local_source = None
        coverage_state, completion_class, next_actions = classify_record(entry, source_ids)
        counts = processed_counts(root, str(local_source) if local_source else None)
        record = {
            "work_id": entry.get("work_id"),
            "title": entry.get("title"),
            "year": entry.get("year"),
            "source_type": entry.get("source_type"),
            "priority": normalized_priority(entry.get("priority")),
            "manifest_status": entry.get("status"),
            "coverage_state": coverage_state,
            "completion_class": completion_class,
            "related_local_source_id": local_source,
            "processed_counts": counts,
            "processed_sections": counts["chapters"],
            "authority_url": first_authority_url(entry),
            "why_it_matters": entry.get("why_it_matters") or entry.get("processing_intent"),
            "repo_action": entry.get("repo_action"),
            "next_actions": next_actions,
            "links": {
                "source": source_link(local_source, "source"),
                "source_text": source_link(local_source, "text"),
                "workbench": source_link(local_source, "workbench"),
                "coverage": source_link(local_source, "coverage"),
            },
        }
        if local_source and local_source in source_by_id:
            record["catalog_status"] = source_by_id[local_source].get("processed_status")
        records.append(record)

    records.sort(key=sort_key)
    state_counts = Counter(record["coverage_state"] for record in records)
    priority_counts = Counter(record["priority"] for record in records)
    type_counts = Counter(str(record["source_type"]) for record in records)

    critical_frontier = [
        record for record in records
        if record["priority"] == "critical" and record["coverage_state"] not in {"processed-corpus", "ocr-seeded-corpus"}
    ]
    article_frontier = [
        record for record in records
        if "article" in str(record["source_type"]) or "paper" in str(record["source_type"])
    ]
    book_frontier = [
        record for record in records
        if any(token in str(record["source_type"]) for token in ["book", "lecture", "pamphlet", "volume"])
    ]

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Authority and completion matrix. This is a control layer, not a claim that unprocessed works have been decoded.",
        "basis": {
            "bibliography_manifest": "sources/steinmetz_bibliography_manifest.json",
            "official_source_intake_manifest": "sources/official_source_intake_manifest.json",
            "source_catalog": "sources/source_catalog.json",
            "patent_register": "sources/steinmetz_patents/patent_register.json",
            "external_authority_baselines": [
                {
                    "label": "Wikipedia bibliography and patent examples",
                    "url": "https://en.wikipedia.org/wiki/Charles_Proteus_Steinmetz#Bibliography",
                    "use": "Initial public checklist only; every entry needs primary-source verification.",
                },
                {
                    "label": "Online Books Page author listing",
                    "url": "https://onlinebooks.library.upenn.edu/webbin/book/lookupname?key=Steinmetz%2C+Charles+Proteus%2C+1865-1923",
                    "use": "Book and HathiTrust trail discovery.",
                },
                {
                    "label": "Open Library author record",
                    "url": "https://openlibrary.org/authors/OL164263A/Charles_Proteus_Steinmetz",
                    "use": "Edition and Internet Archive identifier cross-checking.",
                },
                {
                    "label": "Google Patents inventor query",
                    "url": "https://patents.google.com/?inventor=Charles+Proteus+Steinmetz",
                    "use": "Patent discovery before authority normalization.",
                },
            ],
        },
        "summary": {
            "bibliography_records": len(records),
            "seeded_source_catalog_records": len(source_catalog),
            "patent_seed_records": len(patent_register.get("patents", []) if isinstance(patent_register, dict) else []),
            "coverage_state_counts": dict(sorted(state_counts.items())),
            "priority_counts": dict(sorted(priority_counts.items())),
            "source_type_counts": dict(sorted(type_counts.items())),
            "critical_frontier_count": len(critical_frontier),
            "article_or_paper_records": len(article_frontier),
            "book_lecture_pamphlet_records": len(book_frontier),
            "completion_rule": "Steinmetz completion requires every critical work to be either processed with visible custody or explicitly deferred with a public reason; patents require a separate authority pass beyond the seeded examples.",
        },
        "critical_frontier": critical_frontier,
        "records": records,
    }


def status_badge(record: dict[str, Any]) -> str:
    labels = {
        "processed-corpus": "Processed Corpus",
        "ocr-seeded-corpus": "OCR-Seeded Corpus",
        "registered-authority-target": "Registered Authority Target",
        "planned-acquisition": "Planned Acquisition",
        "archival-target": "Archival Target",
        "patent-corpus-target": "Patent Corpus Target",
        "secondary-context": "Secondary Context",
    }
    label = labels.get(str(record["coverage_state"]), str(record["coverage_state"]).replace("-", " ").title())
    return f"<span class=\"corpus-status corpus-{html_escape(record['coverage_state'])}\">{html_escape(label)}</span>"


def record_card(record: dict[str, Any]) -> str:
    work_url = f"{BASE_URL}/source-library/corpus-completion/works/{record['work_id']}/"
    source_link_html = ""
    if record["links"].get("source_text"):
        source_link_html = f"<a href=\"{html_escape(record['links']['source_text'])}\">Read source text</a>"
    elif record.get("authority_url"):
        source_link_html = f"<a href=\"{html_escape(record['authority_url'])}\">Authority trail</a>"
    return f"""<div class=\"source-section-card\">
  {status_badge(record)}
  <strong><a href=\"{html_escape(work_url)}\">{html_escape(record['title'])}</a></strong>
  <em>{html_escape(record.get('year') or 'undated')} - {html_escape(record.get('source_type'))}</em>
  <p>{html_escape(record.get('why_it_matters') or 'Registered source record awaiting review.')}</p>
  <small>{source_link_html}</small>
</div>"""


def build_index_page(matrix: dict[str, Any]) -> str:
    summary = matrix["summary"]
    critical_cards = "\n".join(record_card(record) for record in matrix["critical_frontier"][:12])
    rows = []
    for record in matrix["records"]:
        work_url = f"{BASE_URL}/source-library/corpus-completion/works/{record['work_id']}/"
        authority = f"<a href=\"{html_escape(record['authority_url'])}\">authority</a>" if record.get("authority_url") else "registered"
        source = f"<a href=\"{html_escape(record['links']['source_text'])}\">reader</a>" if record["links"].get("source_text") else authority
        rows.append(
            "<tr>"
            f"<td><a href=\"{html_escape(work_url)}\">{html_escape(record['title'])}</a></td>"
            f"<td>{html_escape(record.get('year') or '')}</td>"
            f"<td>{html_escape(record['priority'])}</td>"
            f"<td>{html_escape(record.get('source_type'))}</td>"
            f"<td>{status_badge(record)}</td>"
            f"<td>{source}</td>"
            "</tr>"
        )
    return f"""---
title: Steinmetz Corpus Completion Matrix
description: The authority layer for every processed, registered, and still-missing Steinmetz work.
---

{GENERATED_NOTE}

## Why This Exists

The site now has a large processed corpus, but a definitive Steinmetz archive must also know what it has not processed yet. This matrix keeps every major work, paper, edition, archive, and patent-frontier item visible so the project cannot mistake broad coverage for completion.

<div class=\"coverage-stat-grid\">
  <div><strong>{summary['bibliography_records']}</strong><p>Bibliography records</p><span>Registered Steinmetz works and source targets in the control manifest.</span></div>
  <div><strong>{summary['seeded_source_catalog_records']}</strong><p>Processed source records</p><span>Sources with source catalog entries and generated reading surfaces.</span></div>
  <div><strong>{summary['critical_frontier_count']}</strong><p>Critical frontier items</p><span>High-value Steinmetz works that must be acquired or explicitly deferred before completion.</span></div>
  <div><strong>{summary['patent_seed_records']}</strong><p>Seeded patent examples</p><span>Patent examples currently registered before the full 200-plus authority pass.</span></div>
</div>

## Completion Rule

{summary['completion_rule']}

## Critical Acquisition Frontier

These are not optional decorations. They are the works most likely to change the depth of the archive: hysteresis, complex quantities, magnetic force language, general circuit equations, lightning, impulse currents, cable discharge, and cumulative surges.

<div class=\"source-section-grid\">
{critical_cards}
</div>

## Full Source Matrix

<table class=\"codex-status-table corpus-completion-table\">
  <thead>
    <tr>
      <th>Work</th>
      <th>Year</th>
      <th>Priority</th>
      <th>Type</th>
      <th>State</th>
      <th>Open</th>
    </tr>
  </thead>
  <tbody>
    {''.join(rows)}
  </tbody>
</table>

## Authority Baselines

- [Wikipedia bibliography and patent examples](https://en.wikipedia.org/wiki/Charles_Proteus_Steinmetz#Bibliography) are used only as an intake checklist.
- [Online Books Page author listing](https://onlinebooks.library.upenn.edu/webbin/book/lookupname?key=Steinmetz%2C+Charles+Proteus%2C+1865-1923) is used for book and HathiTrust trails.
- [Open Library author record](https://openlibrary.org/authors/OL164263A/Charles_Proteus_Steinmetz) is used for edition and Internet Archive cross-checking.
- [Google Patents inventor search](https://patents.google.com/?inventor=Charles+Proteus+Steinmetz) is used only as the patent discovery front door before authority normalization.
"""


def build_critical_page(matrix: dict[str, Any]) -> str:
    rows = []
    for record in matrix["critical_frontier"]:
        work_url = f"{BASE_URL}/source-library/corpus-completion/works/{record['work_id']}/"
        actions = "<br />".join(html_escape(action) for action in record["next_actions"])
        authority = f"<a href=\"{html_escape(record['authority_url'])}\">Authority</a>" if record.get("authority_url") else "Authority pending"
        rows.append(
            "<tr>"
            f"<td><a href=\"{html_escape(work_url)}\">{html_escape(record['title'])}</a></td>"
            f"<td>{html_escape(record.get('year') or '')}</td>"
            f"<td>{html_escape(record.get('source_type'))}</td>"
            f"<td>{status_badge(record)}</td>"
            f"<td>{html_escape(record.get('why_it_matters') or '')}</td>"
            f"<td>{actions}</td>"
            f"<td>{authority}</td>"
            "</tr>"
        )
    return f"""---
title: Critical Steinmetz Source Frontier
description: The high-priority unprocessed works that remain before the Steinmetz corpus can be called complete.
---

{GENERATED_NOTE}

## The Frontier

This page is the no-shortcuts list. These records are critical because they bear directly on Steinmetz's defining contributions: hysteresis, complex quantities, general circuit equations, lightning and impulse currents, magnetic forces, distributed cable discharge, and cumulative surges.

<table class=\"codex-status-table corpus-completion-table\">
  <thead>
    <tr>
      <th>Work</th>
      <th>Year</th>
      <th>Type</th>
      <th>State</th>
      <th>Why It Matters</th>
      <th>Next Actions</th>
      <th>Trail</th>
    </tr>
  </thead>
  <tbody>
    {''.join(rows)}
  </tbody>
</table>
"""


def build_work_page(record: dict[str, Any]) -> str:
    source_links = []
    for label, key in [
        ("Source overview", "source"),
        ("Source text reader", "source_text"),
        ("Chapter workbench", "workbench"),
        ("Book coverage", "coverage"),
    ]:
        url = record["links"].get(key)
        if url:
            source_links.append(f'<a href="{html_escape(url)}">{html_escape(label)}</a>')
    if record.get("authority_url"):
        source_links.append(f'<a href="{html_escape(record["authority_url"])}">Authority trail</a>')
    links_html = "\n".join(source_links) if source_links else "<span>No public source link registered yet.</span>"
    counts = record["processed_counts"]
    action_items = "\n".join(f"<li>{html_escape(action)}</li>" for action in record["next_actions"])
    return f"""---
title: {frontmatter_string(record['title'])}
description: {frontmatter_string(f"Source completion record for {record['title']}.")}
---

{GENERATED_NOTE}

<div class=\"source-status-hero\">
  <p>{status_badge(record)}</p>
  <h2>{html_escape(record['title'])}</h2>
  <span>{html_escape(record.get('year') or 'undated')} - {html_escape(record.get('source_type'))} - priority: {html_escape(record['priority'])}</span>
</div>

## Why This Work Matters

{md_escape(record.get('why_it_matters') or 'This work is registered in the Steinmetz bibliography intake and awaits source-specific review.')}

## Current Archive State

| Field | Value |
| --- | --- |
| Work ID | `{md_escape(record['work_id'])}` |
| Manifest status | `{md_escape(record.get('manifest_status'))}` |
| Coverage state | `{md_escape(record['coverage_state'])}` |
| Completion class | `{md_escape(record['completion_class'])}` |
| Related local source | `{md_escape(record.get('related_local_source_id') or 'none yet')}` |
| Processed sections | {counts['chapters']} |
| Equation candidates | {counts['equations']} |
| Figure candidates | {counts['figures']} |
| Concept candidates | {counts['concepts']} |
| Glossary candidates | {counts['glossary']} |
| Quote candidates | {counts['quotes']} |

## Open This Record

<div class=\"source-matrix\">
{links_html}
</div>

## Required Next Work

<ul>
{action_items}
</ul>

## Editorial Boundary

This page does not claim the work has been decoded unless a local source reader, page map, and candidate artifacts are present. Registered authority targets are part of the completion plan, not evidence for technical claims by themselves.
"""


def write_pages(root: Path, matrix: dict[str, Any]) -> None:
    docs = root / "site" / "src" / "content" / "docs" / "source-library" / "corpus-completion"
    write_text(docs / "index.mdx", build_index_page(matrix))
    write_text(docs / "critical-frontier.mdx", build_critical_page(matrix))
    works_dir = docs / "works"
    for record in matrix["records"]:
        write_text(works_dir / f"{record['work_id']}.mdx", build_work_page(record))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    root = args.root.resolve()
    matrix = build_matrix(root)
    write_json(root / "processed" / "steinmetz_corpus_completion_matrix.json", matrix)
    write_pages(root, matrix)
    print(
        "Generated corpus completion matrix for "
        f"{matrix['summary']['bibliography_records']} bibliography records; "
        f"{matrix['summary']['critical_frontier_count']} critical frontier records."
    )


if __name__ == "__main__":
    main()
