#!/usr/bin/env python3
"""Promote a bounded visual-review gallery from extracted PDF images.

The raw PDF image extraction can produce thousands of page-image candidates.
This generator keeps the public site usable by selecting a small, source-routed
set of review images, copying those assets into `site/public`, and generating
Starlight pages that clearly label them as scan/image custody leads.
"""

from __future__ import annotations

import html
import json
import shutil
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
MAX_PER_SOURCE = 24
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_extracted_visual_review_gallery.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def clean(value: Any) -> str:
    return "" if value is None else str(value).strip()


def esc(value: Any) -> str:
    return html.escape(clean(value), quote=True).replace("{", "&#123;").replace("}", "&#125;")


def slug(value: Any) -> str:
    text = clean(value).lower()
    out = []
    previous_dash = False
    for char in text:
        if char.isalnum():
            out.append(char)
            previous_dash = False
        elif not previous_dash:
            out.append("-")
            previous_dash = True
    return "".join(out).strip("-") or "visual"


def source_titles(root: Path) -> dict[str, str]:
    catalog = load_json(root / "sources" / "source_catalog.json", [])
    return {
        str(source.get("source_id")): str(source.get("title") or source.get("source_id"))
        for source in catalog
        if isinstance(source, dict) and source.get("source_id")
    }


def score_record(record: dict[str, Any]) -> tuple[int, int]:
    width = int(record.get("width") or 0)
    height = int(record.get("height") or 0)
    page = int(record.get("pdf_page_number") or 0)
    area = width * height
    # Prefer full, readable page images and spread the selected records across the book.
    return (area, -abs((page % 12) - 6))


def select_records(records: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    if len(records) <= limit:
        return sorted(records, key=lambda item: int(item.get("pdf_page_number") or 0))
    by_page: dict[int, dict[str, Any]] = {}
    for record in records:
        page = int(record.get("pdf_page_number") or 0)
        if page not in by_page or score_record(record) > score_record(by_page[page]):
            by_page[page] = record
    page_records = sorted(by_page.values(), key=lambda item: int(item.get("pdf_page_number") or 0))
    step = max(1, len(page_records) // limit)
    sampled = page_records[::step][:limit]
    if len(sampled) < limit:
        for record in page_records:
            if record not in sampled:
                sampled.append(record)
            if len(sampled) >= limit:
                break
    return sorted(sampled, key=lambda item: int(item.get("pdf_page_number") or 0))


def copy_record(root: Path, record: dict[str, Any]) -> dict[str, Any] | None:
    source_id = str(record.get("source_id") or "")
    source_path = root / str(record.get("path") or "")
    if not source_id or not source_path.exists():
        return None
    ext = source_path.suffix.lower() or ".png"
    filename = f"page-{int(record.get('pdf_page_number') or 0):04d}-{slug(record.get('id'))}{ext}"
    public_path = root / "site" / "public" / "diagrams" / "extracted-candidates" / source_id / filename
    public_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, public_path)
    return {
        **record,
        "public_path": str(public_path.relative_to(root / "site" / "public")).replace("\\", "/"),
        "public_url": f"{BASE_URL}/diagrams/extracted-candidates/{source_id}/{filename}",
        "source_visual_map": f"{BASE_URL}/diagrams/source-visuals/{source_id}/",
        "source_text": f"{BASE_URL}/source-texts/{source_id}/",
        "status": "extracted-review-image",
    }


def gather(root: Path) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for manifest_path in sorted(root.glob("processed/*/image_extraction/manifest.json")):
        manifest = load_json(manifest_path, {})
        records = manifest.get("records", []) if isinstance(manifest, dict) else []
        selected = select_records([record for record in records if isinstance(record, dict)], MAX_PER_SOURCE)
        for record in selected:
            copied = copy_record(root, record)
            if copied:
                grouped[str(copied["source_id"])].append(copied)
    return grouped


def image_card(record: dict[str, Any]) -> str:
    page = record.get("pdf_page_number")
    dims = f"{record.get('width')} x {record.get('height')}"
    return f"""<article class="codex-visual-card extracted-visual-card">
  <img src="{esc(record.get('public_url'))}" alt="Extracted scan image candidate from page {esc(page)}" />
  <div>
    <strong>PDF page {esc(page)}</strong>
    <p>{esc(record.get('asset_type'))} - {esc(dims)} - {esc(record.get('status'))}</p>
    <p><small>{esc(record.get('note'))}</small></p>
    <p><a href="{esc(record.get('public_url'))}">Open image</a> - <a href="{esc(record.get('source_text'))}">read source</a> - <a href="{esc(record.get('source_visual_map'))}">source visual map</a></p>
  </div>
</article>"""


def source_page(source_id: str, title: str, records: list[dict[str, Any]]) -> str:
    cards = "\n".join(image_card(record) for record in records)
    return f"""---
title: "{esc(title)} Extracted Visual Review"
description: "Bounded extracted scan-image review gallery for {esc(title)}."
---

{GENERATED_NOTE}

## Extracted Visual Review

This page promotes a bounded set of extracted PDF image candidates for visual review. These are not final diagrams, not corrected crops, and not figure transcriptions. They are source-custody leads that help researchers quickly see where visual material may exist in the scan.

<div class="source-text-warning" data-layer="source">
  <strong>Verification rule:</strong> cite the original scan or a promoted crop, not this review candidate. Use these images to choose pages for exact figure cropping, caption verification, and diagram explanation.
</div>

<div class="source-text-toolbar">
  <a href="{BASE_URL}/diagrams/extracted-visual-candidates/">Back to extracted visual candidates</a>
  <a href="{BASE_URL}/diagrams/source-visuals/{source_id}/">Open source visual map</a>
  <a href="{BASE_URL}/source-texts/{source_id}/">Read source text</a>
</div>

<div class="codex-visual-grid extracted-visual-grid">
{cards}
</div>
"""


def index_page(grouped: dict[str, list[dict[str, Any]]], titles: dict[str, str]) -> str:
    cards = []
    total = 0
    for source_id, records in sorted(grouped.items(), key=lambda item: titles.get(item[0], item[0])):
        total += len(records)
        cards.append(
            f"""<a href="{BASE_URL}/diagrams/extracted-visual-candidates/{source_id}/">
  <strong>{esc(titles.get(source_id, source_id))}</strong>
  <span>{len(records)} bounded image-review candidates promoted from local PDF extraction.</span>
  <small>Use for visual discovery; verify before citation.</small>
</a>"""
        )
    return f"""---
title: Extracted Visual Candidates
description: Bounded review galleries promoted from local Steinmetz PDF image extraction.
---

{GENERATED_NOTE}

The extracted visual candidates give the archive a broader visual browsing layer without pretending every page image is a finished diagram. They are especially useful for finding likely figure pages in sources that have not yet received hand-cropped, caption-verified diagrams.

<div class="codex-signal">
  <div><strong>{total}</strong><p>promoted review images</p></div>
  <div><strong>{len(grouped)}</strong><p>sources represented</p></div>
  <div><strong>{MAX_PER_SOURCE}</strong><p>maximum per source</p></div>
</div>

<div class="source-text-warning" data-layer="source">
  <strong>Layer rule:</strong> this is an image-custody layer. Final diagram pages still require exact scan checking, cropping, caption transcription, concept routing, and explanatory annotation.
</div>

<div class="reading-route-index visual-topic-index">
{chr(10).join(cards)}
</div>
"""


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    titles = source_titles(root)
    public_root = root / "site" / "public" / "diagrams" / "extracted-candidates"
    docs_root = root / "site" / "src" / "content" / "docs" / "diagrams" / "extracted-visual-candidates"
    if public_root.exists():
        shutil.rmtree(public_root)
    if docs_root.exists():
        shutil.rmtree(docs_root)
    grouped = gather(root)
    docs_root.mkdir(parents=True, exist_ok=True)
    for source_id, records in grouped.items():
        write_text(docs_root / source_id / "index.mdx", source_page(source_id, titles.get(source_id, source_id), records))
    write_text(docs_root / "index.mdx", index_page(grouped, titles))
    payload = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Bounded extracted visual candidates. Use for visual discovery; verify against scans before citation.",
        "max_per_source": MAX_PER_SOURCE,
        "source_count": len(grouped),
        "record_count": sum(len(records) for records in grouped.values()),
        "sources": [
            {
                "source_id": source_id,
                "title": titles.get(source_id, source_id),
                "record_count": len(records),
                "page": f"{BASE_URL}/diagrams/extracted-visual-candidates/{source_id}/",
                "records": records,
            }
            for source_id, records in sorted(grouped.items(), key=lambda item: titles.get(item[0], item[0]))
        ],
    }
    write_json(root / "processed" / "extracted_visual_review_index.json", payload)
    write_json(root / "site" / "public" / "data" / "extracted_visual_review_index.json", payload)
    print(f"Generated extracted visual review gallery with {payload['record_count']} images.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
