#!/usr/bin/env python3
"""Generate a strict claim-attribution ledger for source isolation.

This ledger is designed for the long-term codex architecture. It keeps
Steinmetz source facts, OCR candidates, modern engineering translations,
mathematical reconstructions, patent authority seeds, and future interpretive
layers from being flattened into one voice.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_claim_attribution_ledger.py. Do not edit by hand. */}"

LAYER_DEFINITIONS = [
    {
        "layer": "source_custody",
        "meaning": "A source, edition, scan, OCR file, or custody pointer exists.",
        "rule": "Use as a source pointer, not as proof that every page claim is verified.",
    },
    {
        "layer": "steinmetz_original_wording",
        "meaning": "A candidate direct wording or close source passage from Steinmetz.",
        "rule": "Requires scan verification before quotation as a settled text.",
    },
    {
        "layer": "mathematical_source_candidate",
        "meaning": "A formula, equation, derivation, or numerical relation found in OCR/PDF text.",
        "rule": "Check typography, symbols, signs, subscripts, and surrounding definitions before canonical use.",
    },
    {
        "layer": "modern_engineering_interpretation",
        "meaning": "A modern translation of a Steinmetz expression or concept.",
        "rule": "Keep visibly downstream from the source form it translates.",
    },
    {
        "layer": "concept_index_candidate",
        "meaning": "A source-text occurrence or concept-routing signal.",
        "rule": "Use to find passages, not as a final concept definition.",
    },
    {
        "layer": "glossary_candidate",
        "meaning": "A historical term or obsolete-language signal requiring definition work.",
        "rule": "Promote only after exact source usage and modern equivalent are checked.",
    },
    {
        "layer": "source_scan_asset",
        "meaning": "A crop or image derived from an original source scan.",
        "rule": "Review page number, figure label, crop completeness, and checksum before canonical diagram use.",
    },
    {
        "layer": "diagram_candidate",
        "meaning": "A figure, diagram, waveform, or geometric representation candidate.",
        "rule": "Connect to original scan asset where possible before explaining it.",
    },
    {
        "layer": "patent_authority_candidate",
        "meaning": "A patent record with authority URL/PDF seed data.",
        "rule": "Extract claims and drawings before using the patent as technical evidence.",
    },
    {
        "layer": "interpretive_reading",
        "meaning": "Ether-field, Wheeler-style, Tesla-era, or other interpretive synthesis.",
        "rule": "Must never be presented as what Steinmetz explicitly said unless independently sourced.",
    },
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def site_url(path: str | None) -> str | None:
    if not path:
        return None
    if path.startswith("http"):
        return path
    if path.startswith(BASE_URL):
        return path
    if path.startswith("/"):
        return f"{BASE_URL}{path}"
    return f"{BASE_URL}/{path}"


def classify_evidence(record: dict[str, Any]) -> tuple[str, str, str, bool]:
    record_type = str(record.get("record_type", "unknown"))
    confidence = str(record.get("confidence", ""))
    if record_type == "source":
        return (
            "source_custody_record",
            "source_custody",
            "Use as a custody/source pointer. Edition and page claims still need local verification.",
            False,
        )
    if record_type == "quote":
        return (
            "source_quote_candidate",
            "steinmetz_original_wording",
            "Use as a quote lead only after scan verification and exact transcription.",
            True,
        )
    if record_type == "equation":
        return (
            "equation_candidate",
            "mathematical_source_candidate",
            "Use as an equation lead only after scan verification and notation review.",
            True,
        )
    if record_type == "promoted_original_figure" or confidence == "scan-crop-promoted":
        return (
            "scan_derived_diagram_asset",
            "source_scan_asset",
            "Use as a scan-derived asset after crop, page, and label review.",
            True,
        )
    if record_type == "figure":
        return (
            "figure_candidate",
            "diagram_candidate",
            "Use as a figure lead until an original crop or scan page is attached.",
            True,
        )
    if record_type == "glossary":
        return (
            "historical_term_candidate",
            "glossary_candidate",
            "Use to locate historical language; promote after exact usage and modern equivalent are checked.",
            True,
        )
    if record_type == "concept":
        return (
            "concept_occurrence_candidate",
            "concept_index_candidate",
            "Use to route reading; promote only after exact source passages are selected.",
            True,
        )
    return (
        "unclassified_candidate",
        "concept_index_candidate",
        "Use only as a review lead until classified.",
        True,
    )


def evidence_claim(record: dict[str, Any]) -> dict[str, Any]:
    claim_type, layer, allowed_use, needs_verification = classify_evidence(record)
    return {
        "id": f"evidence::{record.get('id')}",
        "person": record.get("person", "Charles Proteus Steinmetz"),
        "collection": record.get("collection", "steinmetz"),
        "source_id": record.get("source_id"),
        "source_title": record.get("source_title"),
        "year": record.get("year"),
        "claim_type": claim_type,
        "interpretation_layer": layer,
        "record_type": record.get("record_type"),
        "record_id": record.get("record_id"),
        "label": record.get("label"),
        "status": record.get("status"),
        "confidence": record.get("confidence"),
        "verification_required": needs_verification,
        "allowed_use": allowed_use,
        "source_trace": {
            "site_path": site_url(record.get("site_path")),
            "evidence": record.get("evidence", {}),
        },
    }


def equation_queue_lookup(root: Path) -> dict[str, dict[str, Any]]:
    queue = load_json(root / "processed" / "equation_verification_queue.json", {})
    records = queue.get("records", []) if isinstance(queue, dict) else []
    return {str(record.get("id")): record for record in records if record.get("id")}


def canonical_equation_claims(root: Path) -> list[dict[str, Any]]:
    equations = load_json(root / "processed" / "canonical_equations.json", {}).get("records", [])
    queue = equation_queue_lookup(root)
    claims = []
    for equation in equations if isinstance(equations, list) else []:
        equation_id = str(equation.get("id"))
        queue_record = queue.get(equation_id, {})
        base = {
            "person": "Charles Proteus Steinmetz",
            "collection": "steinmetz",
            "source_id": equation.get("source_id"),
            "source_title": equation.get("source_title"),
            "year": None,
            "record_type": "canonical_equation",
            "record_id": equation_id,
            "label": equation.get("title"),
            "status": equation.get("status"),
            "verification_required": True,
            "source_trace": {
                "source_ref": equation.get("source_ref", {}),
                "equation_page": site_url(equation.get("site_path")),
                "verification_queue_status": queue_record.get("verification_status", "not-in-verification-queue"),
                "verification_queue": f"{BASE_URL}/roadmap/equation-verification-queue/",
                "source_texts": queue_record.get("links", {}).get("source_texts", []),
                "chapter_workbenches": queue_record.get("links", {}).get("chapter_workbenches", []),
            },
        }
        claims.append(
            {
                **base,
                "id": f"canonical-equation-original::{equation_id}",
                "claim_type": "source_located_mathematical_claim",
                "interpretation_layer": "mathematical_source_candidate",
                "claim_text": equation.get("original_form"),
                "confidence": "source-located candidate; needs scan verification",
                "allowed_use": "Use as Steinmetz-form equation candidate after scan typography check.",
            }
        )
        claims.append(
            {
                **base,
                "id": f"canonical-equation-modern::{equation_id}",
                "claim_type": "modern_engineering_translation",
                "interpretation_layer": "modern_engineering_interpretation",
                "claim_text": equation.get("modern_form"),
                "confidence": "modern translation candidate; depends on source-form verification",
                "allowed_use": "Use as a modern translation only beside the original source form and review state.",
            }
        )
    return claims


def patent_claims(root: Path) -> list[dict[str, Any]]:
    queue = load_json(root / "processed" / "patent_verification_queue.json", {})
    records = queue.get("records", []) if isinstance(queue, dict) else []
    claims = []
    for patent in records if isinstance(records, list) else []:
        number = patent.get("patent_number")
        claims.append(
            {
                "id": f"patent-authority::{number}",
                "person": "Charles Proteus Steinmetz",
                "collection": "steinmetz",
                "source_id": "steinmetz-patents",
                "source_title": "Steinmetz Patents",
                "year": str(patent.get("publication_date", ""))[:4] or None,
                "claim_type": "patent_authority_record_seed",
                "interpretation_layer": "patent_authority_candidate",
                "record_type": "patent",
                "record_id": number,
                "label": patent.get("title"),
                "status": patent.get("research_status"),
                "confidence": "authority URL/PDF seed; claims and drawings not extracted",
                "verification_required": True,
                "allowed_use": "Use as patent authority lead; extract claims and drawings before technical citation.",
                "source_trace": {
                    "patent_url": patent.get("patent_url"),
                    "pdf_url": patent.get("pdf_url"),
                    "verification_status": patent.get("verification_status"),
                    "patent_queue": f"{BASE_URL}/roadmap/patent-verification-queue/",
                    "concept_links": patent.get("concept_links", []),
                    "diagram_targets": patent.get("diagram_targets", []),
                },
            }
        )
    return claims


def build_ledger(root: Path) -> dict[str, Any]:
    evidence = load_json(root / "processed" / "evidence_ledger.json", {})
    records = evidence.get("records", []) if isinstance(evidence, dict) else []
    claims = [evidence_claim(record) for record in records if isinstance(record, dict)]
    claims.extend(canonical_equation_claims(root))
    claims.extend(patent_claims(root))

    layer_counts = Counter(str(claim.get("interpretation_layer")) for claim in claims)
    claim_type_counts = Counter(str(claim.get("claim_type")) for claim in claims)
    source_counts = Counter(str(claim.get("source_id")) for claim in claims)
    verification_counts = Counter("needs_verification" if claim.get("verification_required") else "custody_pointer" for claim in claims)

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Claim attribution ledger. It classifies review-state records by source, layer, and allowed use; it does not certify claims.",
        "person": "Charles Proteus Steinmetz",
        "collection": "steinmetz",
        "record_count": len(claims),
        "layer_definitions": LAYER_DEFINITIONS,
        "layer_counts": dict(sorted(layer_counts.items())),
        "claim_type_counts": dict(sorted(claim_type_counts.items())),
        "source_counts": dict(sorted(source_counts.items())),
        "verification_counts": dict(sorted(verification_counts.items())),
        "records": claims,
    }


def count_rows(counts: dict[str, int]) -> str:
    return "\n".join(f"| `{md_escape(key)}` | `{value}` |" for key, value in counts.items())


def build_page(ledger: dict[str, Any]) -> str:
    layer_rows = "\n".join(
        f"| `{md_escape(item['layer'])}` | {md_escape(item['meaning'])} | {md_escape(item['rule'])} |"
        for item in ledger["layer_definitions"]
    )
    sample_priority = [
        "source_located_mathematical_claim",
        "modern_engineering_translation",
        "scan_derived_diagram_asset",
        "patent_authority_record_seed",
        "source_quote_candidate",
    ]
    samples = []
    for claim_type in sample_priority:
        for record in ledger["records"]:
            if record.get("claim_type") == claim_type:
                trace = record.get("source_trace", {})
                link = trace.get("equation_page") or trace.get("site_path") or trace.get("patent_url") or ""
                link_text = f"[open]({link})" if link else "not linked"
                samples.append(
                    f"| `{md_escape(record['claim_type'])}` | {md_escape(record.get('label'))} | `{md_escape(record.get('interpretation_layer'))}` | `{md_escape(record.get('confidence'))}` | {link_text} |"
                )
                break
    return f"""---
title: Claim Attribution Ledger
description: Source-isolation ledger for facts, candidates, translations, diagrams, patents, and interpretive boundaries.
---

{GENERATED_NOTE}

## Claim Attribution Ledger

This ledger is the guardrail that lets the archive grow without mixing layers. Every exported record should be readable as one of these: source custody, Steinmetz wording, mathematical candidate, modern translation, concept index, glossary candidate, scan asset, diagram candidate, patent authority seed, or explicitly labeled interpretation.

<div class="codex-signal">
  <div><strong>{ledger['record_count']} records</strong><p>Evidence, equation, and patent records classified by layer.</p></div>
  <div><strong>{ledger['verification_counts'].get('needs_verification', 0)} need review</strong><p>Records that cannot be cited as settled fact yet.</p></div>
  <div><strong>{len(ledger['layer_counts'])} layers</strong><p>Current attribution layers in the Steinmetz collection.</p></div>
</div>

## Layer Rules

| Layer | Meaning | Rule |
| --- | --- | --- |
{layer_rows}

## Claim Type Counts

| Claim Type | Count |
| --- | ---: |
{count_rows(ledger['claim_type_counts'])}

## Layer Counts

| Layer | Count |
| --- | ---: |
{count_rows(ledger['layer_counts'])}

## Sample Records

| Claim Type | Label | Layer | Confidence | Link |
| --- | --- | --- | --- | --- |
{chr(10).join(samples)}

## Source-Isolation Rule

When the archive later adds Tesla, Dollard, Russell, Wheeler, or any wider research collection, every record must keep its `person`, `collection`, `source_id`, `claim_type`, `interpretation_layer`, `confidence`, and `verification_required` fields. Comparison pages may synthesize across people only after each source layer is independently visible.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Repository root")
    args = parser.parse_args()
    root = args.root.resolve()

    ledger = build_ledger(root)
    write_json(root / "processed" / "claim_attribution_ledger.json", ledger)
    write_text(root / "site" / "src" / "content" / "docs" / "roadmap" / "claim-attribution-ledger.mdx", build_page(ledger))


if __name__ == "__main__":
    main()
