#!/usr/bin/env python3
"""Generate a source-routed equation and formula atlas.

The first math pages promote a small canonical seed set. This atlas exposes the
larger equation-candidate layer without pretending OCR formula lines are final
transcriptions. It scores, classifies, and routes candidates back to the source
reader and chapter workbench so mathematical review can move source by source.
"""

from __future__ import annotations

import argparse
import html
import json
import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = "/Charles-Proteus-Steinmetz-Texts-AI-Decoded"
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_equation_atlas.py. Do not edit by hand. */}"

FAMILIES: dict[str, dict[str, Any]] = {
    "symbolic-ac": {
        "label": "Symbolic AC And Complex Quantities",
        "patterns": ["symbolic", "complex", "imaginary", "phase", "vector", "quadrature"],
        "why": "Routes equations where Steinmetz turns alternating quantities into symbolic algebra.",
    },
    "impedance-admittance": {
        "label": "Impedance, Reactance, And Admittance",
        "patterns": ["impedance", "reactance", "admittance", "conductance", "susceptance"],
        "why": "Routes the formulas that became the everyday language of AC circuit calculation.",
    },
    "inductance-capacity": {
        "label": "Inductance, Capacity, And Stored Energy",
        "patterns": ["inductance", "capacity", "condenser", "dielectric", "magnetic"],
        "why": "Routes equations involving field storage, charge, discharge, and frequency-dependent opposition.",
    },
    "transients-oscillation": {
        "label": "Transients, Oscillation, And Damping",
        "patterns": ["transient", "temporary", "oscillation", "damping", "decrement", "period", "e-", "e^"],
        "why": "Routes time-domain formulas that separate permanent terms from natural or temporary terms.",
    },
    "waves-radiation": {
        "label": "Waves, Lines, Radiation, And Frequency",
        "patterns": ["wave", "radiation", "frequency", "wave length", "wavelength", "velocity", "lambda", "line"],
        "why": "Routes equations connecting electric waves, propagation, light, transmission lines, and frequency.",
    },
    "magnetism-hysteresis": {
        "label": "Magnetism, Hysteresis, And Core Loss",
        "patterns": ["hysteresis", "magnetic", "flux", "permeability", "reluctance", "magnetization"],
        "why": "Routes formulas for magnetic materials, flux, loss, effective resistance, and hysteresis behavior.",
    },
    "power-energy": {
        "label": "Power, Energy, Work, And Efficiency",
        "patterns": ["power", "energy", "work", "efficiency", "loss", "joule", "watt", "volt-ampere"],
        "why": "Routes equations where electrical quantities become work, heat, output, loss, or system performance.",
    },
    "engineering-math": {
        "label": "Engineering Mathematics Foundations",
        "patterns": ["number", "logarithm", "function", "differential", "integral", "series", "coordinate"],
        "why": "Routes the mathematical language Steinmetz used to train engineers in calculation itself.",
    },
    "apparatus-systems": {
        "label": "Apparatus, Machines, And Power Systems",
        "patterns": ["motor", "generator", "transformer", "station", "synchronous", "reactor", "system"],
        "why": "Routes formulas tied to machines, apparatus, synchronism, and operating power systems.",
    },
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def clean_text(value: Any, limit: int | None = None) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\u00a0": " ",
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\ufeff": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"\s+", " ", text).strip()
    if limit and len(text) > limit:
        text = text[: limit - 3].rstrip() + "..."
    return text


def html_escape(value: Any) -> str:
    text = html.escape(clean_text(value), quote=True)
    return (
        text.replace("\\", "&#92;")
        .replace("`", "&#96;")
        .replace("$", "&#36;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("*", "&#42;")
        .replace("~", "&#126;")
        .replace("_", "&#95;")
        .replace("[", "&#91;")
        .replace("]", "&#93;")
    )


def html_math_escape(value: Any) -> str:
    return (
        html.escape(clean_text(value), quote=True)
        .replace("`", "&#96;")
        .replace("$", "&#36;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("*", "&#42;")
        .replace("~", "&#126;")
        .replace("_", "&#95;")
        .replace("[", "&#91;")
        .replace("]", "&#93;")
    )


def latex_candidate(value: Any) -> str:
    text = clean_text(value, 220)
    text = html.unescape(text)
    replacements = {
        "—": "-",
        "–": "-",
        "π": r"\pi",
        "λ": r"\lambda",
        "ω": r"\omega",
        "θ": r"\theta",
        "φ": r"\phi",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"\bpi\b", r"\\pi", text, flags=re.I)
    text = re.sub(r"\blambda\b", r"\\lambda", text, flags=re.I)
    text = re.sub(r"\bomega\b", r"\\omega", text, flags=re.I)
    text = re.sub(r"\btheta\b", r"\\theta", text, flags=re.I)
    text = re.sub(r"\bphi\b", r"\\phi", text, flags=re.I)
    text = re.sub(r"\b(sin|cos|tan|log)\b", lambda match: "\\" + match.group(1).lower(), text, flags=re.I)
    text = re.sub(r"\bdeg\.?", r"^\\circ", text, flags=re.I)
    text = re.sub(r"\be\.?m\.?f\.?", r"\\mathrm{e.m.f.}", text, flags=re.I)
    text = text.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#").replace("$", r"\$")
    return text


def md_escape(value: Any) -> str:
    return (
        clean_text(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )


def site_url(path: str | None) -> str:
    if not path:
        return ""
    if path.startswith(BASE_URL):
        return path
    if path.startswith("/"):
        return f"{BASE_URL}{path}"
    return f"{BASE_URL}/{path}"


def find_section(workbench_records: list[dict[str, Any]], source_id: str, line: int | None) -> dict[str, Any] | None:
    if line is None:
        return None
    for record in workbench_records:
        if record.get("source_id") != source_id:
            continue
        start = record.get("line_start")
        end = record.get("line_end")
        if isinstance(start, int) and isinstance(end, int) and start <= line <= end:
            return record
    return None


def formula_score(text: str) -> tuple[int, list[str]]:
    raw = clean_text(text)
    lower = raw.lower()
    signals: list[str] = []
    score = 0

    if "=" in raw:
        score += 34
        signals.append("contains equals sign")
    if re.search(r"\b[a-zA-Z][a-zA-Z0-9_']{0,3}\s*=", raw):
        score += 12
        signals.append("left-hand symbol")
    if re.search(r"[+\-*/^()]", raw):
        score += 10
        signals.append("operator characters")
    if re.search(r"\b(sin|cos|tan|log|sqrt|exp|differential|integral)\b", lower):
        score += 12
        signals.append("function/calculus language")
    if re.search(r"\b(pi|omega|lambda|theta|phi|j|e\.m\.f|e.m.f|rms)\b", lower):
        score += 12
        signals.append("technical symbol language")
    if re.search(r"\d", raw) and re.search(r"[+\-*/=^]", raw):
        score += 10
        signals.append("numeric relation")
    if re.search(r"\b(where|let|if|then|therefore|hence)\b", lower) and "=" in raw:
        score += 8
        signals.append("equation explanation context")
    if re.search(r"\b(fig|figure)\.?\s*\d+", lower):
        score -= 18
        signals.append("figure reference contamination")
    if re.match(r"^\d+\.\s+[A-Z][^.]+\.?\s+\d{1,4}\.?$", raw) and "=" not in raw:
        score -= 32
        signals.append("table-of-contents-like")
    words = re.findall(r"[A-Za-z]{3,}", raw)
    tokens = max(1, len(re.findall(r"\S+", raw)))
    if len(words) / tokens > 0.72 and "=" not in raw:
        score -= 18
        signals.append("mostly prose")
    if len(raw) > 190:
        score -= 12
        signals.append("long OCR line")
    if len(raw) < 4:
        score -= 20
        signals.append("too short")

    return max(0, score), signals


def quality_band(score: int) -> str:
    if score >= 58:
        return "strong-formula-candidate"
    if score >= 36:
        return "reviewable-relation-candidate"
    if score >= 22:
        return "weak-math-or-definition-candidate"
    return "low-confidence-noise-candidate"


def word_hits(lower: str, patterns: list[str]) -> int:
    hits = 0
    for pattern in patterns:
        escaped = re.escape(pattern.lower()).replace("\\ ", r"\s+")
        hits += len(re.findall(rf"\b{escaped}\b", lower))
    return hits


def classify_family(text: str, section_label: str = "", source_id: str = "", source_title: str = "") -> str:
    lower = f" {clean_text(text).lower()} {clean_text(section_label).lower()} {clean_text(source_title).lower()} "

    if source_id == "engineering-mathematics":
        return "engineering-math"
    if "commonwealth-edison" in source_id:
        return "apparatus-systems"
    if "transient" in source_id or "discharges-waves-impulses" in source_id:
        return "transients-oscillation"
    if re.search(r"(^|[^a-z])j([^a-z]|$)", lower) or "complex" in lower or "imaginary" in lower or "quadrature" in lower:
        return "symbolic-ac"
    if re.search(r"\b(cos|sin|tan)\b", lower) and ("phase" in lower or "=" in text):
        return "symbolic-ac"

    best_family = "general-equation-candidates"
    best_score = 0
    for family_id, family in FAMILIES.items():
        score = word_hits(lower, family["patterns"])
        if score > best_score:
            best_score = score
            best_family = family_id
    return best_family


def enrich_record(record: dict[str, Any], workbench_records: list[dict[str, Any]]) -> dict[str, Any]:
    source_ref = record.get("source_ref") or {}
    source_id = str(record.get("source_id") or source_ref.get("source_id") or "")
    line = source_ref.get("line_start")
    line_number = line if isinstance(line, int) else None
    section = find_section(workbench_records, source_id, line_number)
    section_label = section.get("label") if section else ""
    score, signals = formula_score(str(record.get("original_form") or ""))
    family = classify_family(
        str(record.get("original_form") or ""),
        str(section_label),
        source_id,
        str(record.get("source_title") or ""),
    )

    links = {
        "source_overview": f"{BASE_URL}/sources/{source_id}/",
        "source_text_index": f"{BASE_URL}/source-texts/{source_id}/",
        "workbench_index": f"{BASE_URL}/chapter-workbench/{source_id}/",
        "equation_verification_queue": f"{BASE_URL}/roadmap/equation-verification-queue/",
    }
    if section:
        links.update(
            {
                "source_text": site_url(section.get("links", {}).get("source_text")),
                "workbench": f"{BASE_URL}/chapter-workbench/{source_id}/{section.get('slug')}/",
                "book_coverage": f"{BASE_URL}/book-coverage/{source_id}/",
            }
        )

    return {
        "id": record.get("id"),
        "source_id": source_id,
        "source_title": record.get("source_title"),
        "original_form": clean_text(record.get("original_form"), 360),
        "modern_form": clean_text(record.get("modern_form"), 260),
        "status": record.get("status"),
        "source_ref": source_ref,
        "line_start": line_number,
        "line_end": source_ref.get("line_end"),
        "verification": source_ref.get("verification"),
        "section_id": section.get("id") if section else None,
        "section_label": section_label,
        "section_slug": section.get("slug") if section else None,
        "quality_score": score,
        "quality_band": quality_band(score),
        "signals": signals,
        "family": family,
        "links": links,
    }


def build_atlas(root: Path) -> dict[str, Any]:
    equation_index = load_json(root / "processed" / "equation_index.json", {})
    workbench = load_json(root / "processed" / "chapter_workbench.json", {})
    workbench_records = list(workbench.get("records") or [])
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    source_meta = {
        str(source.get("source_id")): {
            "source_id": source.get("source_id"),
            "title": source.get("title"),
            "year": source.get("year"),
            "coverage": f"{BASE_URL}/book-coverage/{source.get('source_id')}/",
            "source_text": f"{BASE_URL}/source-texts/{source.get('source_id')}/",
            "workbench": f"{BASE_URL}/chapter-workbench/{source.get('source_id')}/",
        }
        for source in source_catalog
        if isinstance(source, dict)
    }

    records = [enrich_record(record, workbench_records) for record in equation_index.get("records", [])]
    records.sort(key=lambda item: (-int(item.get("quality_score") or 0), str(item.get("source_title")), int(item.get("line_start") or 999999999)))

    by_family: dict[str, list[dict[str, Any]]] = defaultdict(list)
    by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        by_family[str(record["family"])].append(record)
        by_source[str(record["source_id"])].append(record)

    source_summaries = []
    for source_id, source_records in sorted(by_source.items(), key=lambda item: len(item[1]), reverse=True):
        strong = [item for item in source_records if int(item.get("quality_score") or 0) >= 36]
        source_summaries.append(
            {
                **source_meta.get(source_id, {"source_id": source_id, "title": source_id}),
                "candidate_count": len(source_records),
                "reviewable_relation_count": len(strong),
                "section_linked_count": sum(1 for item in source_records if item.get("section_id")),
                "top_families": Counter(str(item.get("family")) for item in strong).most_common(5),
            }
        )

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Equation atlas records are OCR/PDF-text candidates. Promote only after scan verification, mathematical transcription, and notation review.",
        "total_candidate_records": len(records),
        "reviewable_relation_count": sum(1 for item in records if int(item.get("quality_score") or 0) >= 36),
        "strong_formula_count": sum(1 for item in records if int(item.get("quality_score") or 0) >= 58),
        "source_count": len(by_source),
        "family_counts": {family_id: len(items) for family_id, items in sorted(by_family.items())},
        "source_summaries": source_summaries,
        "records": records,
    }


def card(record: dict[str, Any], rank: int | None = None) -> str:
    rank_html = f"<span>#{rank}</span>" if rank is not None else ""
    line = record.get("line_start")
    section = record.get("section_label") or "source index"
    source_link = record.get("links", {}).get("source_text") or record.get("links", {}).get("source_text_index")
    workbench_link = record.get("links", {}).get("workbench") or record.get("links", {}).get("workbench_index")
    original = record.get("original_form")
    latex = latex_candidate(original)
    return f"""<article class="equation-candidate-card" data-layer="math-candidate">
  <header>
    {rank_html}
    <strong>{html_escape(record.get("source_title"))}</strong>
    <small>{html_escape(section)}{html_escape(" - line " + str(line) if line else "")}</small>
  </header>
  <span class="equation-render">\\({html_math_escape(latex)}\\)</span>
  <details class="equation-source-line"><summary>OCR source line</summary><code>{html_escape(original)}</code></details>
  <footer>
    <small>{html_escape(record.get("quality_band"))} - score {html_escape(record.get("quality_score"))} - {html_escape(FAMILIES.get(str(record.get("family")), {}).get("label", "General candidates"))}</small>
    <nav>
      <a href="{html_escape(source_link)}">source text</a>
      <a href="{html_escape(workbench_link)}">workbench</a>
      <a href="{BASE_URL}/roadmap/equation-verification-queue/">verification queue</a>
    </nav>
  </footer>
</article>"""


def source_rows(atlas: dict[str, Any]) -> str:
    rows = []
    for source in atlas.get("source_summaries", []):
        rows.append(
            "<tr>"
            f"<td><a href=\"{html_escape(source.get('coverage'))}\">{html_escape(source.get('title'))}</a></td>"
            f"<td>{html_escape(source.get('year') or '')}</td>"
            f"<td>{html_escape(source.get('candidate_count'))}</td>"
            f"<td>{html_escape(source.get('reviewable_relation_count'))}</td>"
            f"<td>{html_escape(source.get('section_linked_count'))}</td>"
            f"<td><a href=\"{html_escape(source.get('source_text'))}\">source</a> - <a href=\"{html_escape(source.get('workbench'))}\">workbench</a></td>"
            "</tr>"
        )
    return "\n".join(rows)


def family_cards(atlas: dict[str, Any]) -> str:
    family_counts = atlas.get("family_counts", {})
    parts = []
    for family_id, family in FAMILIES.items():
        parts.append(
            f'<a href="{BASE_URL}/mathematics/equation-atlas/{family_id}/">{html_escape(family["label"])}'
            f'<span>{html_escape(family_counts.get(family_id, 0))} candidates. {html_escape(family["why"])}</span></a>'
        )
    parts.append(
        f'<a href="{BASE_URL}/mathematics/equation-atlas/general-equation-candidates/">General Equation Candidates'
        f'<span>{html_escape(family_counts.get("general-equation-candidates", 0))} candidates awaiting classification.</span></a>'
    )
    return "\n".join(parts)


def build_index_page(atlas: dict[str, Any]) -> str:
    top_records = [record for record in atlas["records"] if int(record.get("quality_score") or 0) >= 36][:36]
    return f"""---
title: Equation Atlas
description: Source-routed equation, formula, and notation candidate atlas across the Steinmetz corpus.
---

{GENERATED_NOTE}

This atlas exposes the mathematical breadth already present in the processed corpus. It is a review map, not a final equation canon: OCR formula lines can contain wrong symbols, missing fractions, page headers, figure references, or broken typography.

<div class="source-text-warning" data-layer="math-candidate">
  <strong>Use rule:</strong> read these as formula candidates. A formula becomes canonical only after scan verification, notation cleanup, variable definition, derivation review, and physical-meaning review.
</div>

<div class="codex-signal">
  <div><strong>{html_escape(atlas.get("total_candidate_records"))}</strong><p>equation and formula candidates in the corpus.</p></div>
  <div><strong>{html_escape(atlas.get("reviewable_relation_count"))}</strong><p>reviewable relation candidates after OCR scoring.</p></div>
  <div><strong>{html_escape(atlas.get("strong_formula_count"))}</strong><p>strong formula candidates to prioritize.</p></div>
  <div><strong>{html_escape(atlas.get("source_count"))}</strong><p>processed sources with mathematical records.</p></div>
</div>

## Formula Families

<div class="source-matrix">
{family_cards(atlas)}
</div>

## Highest-Priority Formula Candidates

<div class="equation-card-grid">
{chr(10).join(card(record, index + 1) for index, record in enumerate(top_records))}
</div>

## Source-Level Math Coverage

<table class="codex-status-table equation-source-summary">
  <thead>
    <tr>
      <th>Source</th>
      <th>Year</th>
      <th>All Candidates</th>
      <th>Reviewable Relations</th>
      <th>Section-Linked</th>
      <th>Open</th>
    </tr>
  </thead>
  <tbody>
{source_rows(atlas)}
  </tbody>
</table>

## Promotion Standard

1. Open the source text and workbench.
2. Check the scan or source PDF for exact typography.
3. Preserve Steinmetz's original notation before translating it.
4. Define every variable.
5. Add the modern equivalent only as a labeled translation.
6. Add a worked example only after the formula is mathematically reviewed.
"""


def build_family_page(family_id: str, atlas: dict[str, Any]) -> str:
    family = FAMILIES.get(
        family_id,
        {
            "label": "General Equation Candidates",
            "why": "Candidates not yet classified into a stronger mathematical family.",
        },
    )
    records = [record for record in atlas["records"] if record.get("family") == family_id]
    records.sort(key=lambda item: (-int(item.get("quality_score") or 0), str(item.get("source_title")), int(item.get("line_start") or 999999999)))
    shown = records[:72]
    return f"""---
title: "{html_escape(family["label"])}"
description: "Equation candidates for {html_escape(family["label"])}."
---

{GENERATED_NOTE}

<div class="source-text-toolbar" data-layer="math-candidate">
  <a href="{BASE_URL}/mathematics/equation-atlas/">Back to equation atlas</a>
  <a href="{BASE_URL}/mathematics/canonical-equation-canon/">Canonical seed set</a>
  <a href="{BASE_URL}/roadmap/equation-verification-queue/">Verification queue</a>
</div>

## Why This Family Matters

{md_escape(family["why"])}

<div class="codex-signal">
  <div><strong>{len(records)}</strong><p>candidate records in this family.</p></div>
  <div><strong>{sum(1 for record in records if int(record.get("quality_score") or 0) >= 36)}</strong><p>reviewable relation candidates.</p></div>
  <div><strong>{len({record.get("source_id") for record in records})}</strong><p>sources represented.</p></div>
</div>

## Candidate Formula Cards

<div class="equation-card-grid">
{chr(10).join(card(record, index + 1) for index, record in enumerate(shown))}
</div>
"""


def write_pages(root: Path, atlas: dict[str, Any]) -> None:
    docs = root / "site" / "src" / "content" / "docs" / "mathematics" / "equation-atlas"
    docs.mkdir(parents=True, exist_ok=True)
    write_text(docs / "index.mdx", build_index_page(atlas))
    family_ids = set(FAMILIES) | {"general-equation-candidates"}
    for family_id in sorted(family_ids):
        write_text(docs / family_id / "index.mdx", build_family_page(family_id, atlas))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    atlas = build_atlas(root)
    write_json(root / "processed" / "equation_atlas.json", atlas)
    write_json(root / "site" / "public" / "data" / "equation_atlas.json", atlas)
    write_pages(root, atlas)
    print(
        "Generated equation atlas with "
        f"{atlas['total_candidate_records']} candidates and "
        f"{atlas['reviewable_relation_count']} reviewable relations."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
