#!/usr/bin/env python3
"""Generate a source-grounded passage atlas and research map.

This layer addresses a practical reader problem: after hundreds of source
sections are available, people need a way to find the passages that look
conceptually dense without pretending OCR snippets are final quotations.

The script is extractive. It scores source paragraphs by theme density and
review signals, then publishes short candidate passages with source/workbench
links and verification warnings.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_passage_atlas.py. Do not edit by hand. */}"

THEMES: dict[str, dict[str, Any]] = {
    "field-language": {
        "label": "Field Language",
        "patterns": [
            "field of force",
            "field",
            "magnetic field",
            "electric field",
            "electrostatic field",
            "stress",
            "strain",
            "pressure",
            "tension",
        ],
        "concept": "concept-concordance/electric-field",
        "why": "This passage may help distinguish Steinmetz's explicit field language from later interpretation.",
    },
    "ether-and-relativity": {
        "label": "Ether And Relativity",
        "patterns": ["ether", "aether", "relativity", "space", "Faraday", "Maxwell"],
        "concept": "concepts/ether",
        "why": "This passage may clarify exactly how Steinmetz uses, revises, or abandons ether language in context.",
    },
    "symbolic-ac": {
        "label": "Symbolic AC Method",
        "patterns": [
            "symbolic",
            "complex quantity",
            "imaginary",
            "impedance",
            "reactance",
            "admittance",
            "conductance",
            "susceptance",
            "phase",
            "vector",
        ],
        "concept": "concepts/symbolic-method",
        "why": "This passage may show how Steinmetz turns phase geometry into calculable electrical algebra.",
    },
    "transients-waves-surges": {
        "label": "Transients, Waves, And Surges",
        "patterns": [
            "transient",
            "temporary",
            "oscillation",
            "damping",
            "decrement",
            "wave",
            "standing wave",
            "traveling wave",
            "travelling wave",
            "surge",
            "lightning",
            "impulse",
            "discharge",
        ],
        "concept": "concepts/transient-phenomena",
        "why": "This passage may expose the time-domain behavior hidden by steady-state circuit language.",
    },
    "magnetism-hysteresis": {
        "label": "Magnetism And Hysteresis",
        "patterns": [
            "hysteresis",
            "magnetic",
            "magnetism",
            "magnetization",
            "flux",
            "permeability",
            "reluctance",
            "magnetic lag",
        ],
        "concept": "concepts/hysteresis",
        "why": "This passage may preserve Steinmetz's magnetic material vocabulary and loss reasoning.",
    },
    "dielectric-capacity": {
        "label": "Dielectricity And Capacity",
        "patterns": [
            "dielectric",
            "electrostatic",
            "capacity",
            "condenser",
            "condensers",
            "displacement",
            "charge",
            "discharge",
        ],
        "concept": "concepts/inductance-capacity",
        "why": "This passage may show how capacity, charge, displacement, or dielectric storage enter circuit theory.",
    },
    "radiation-light": {
        "label": "Radiation, Light, And Illumination",
        "patterns": [
            "radiation",
            "light",
            "illumination",
            "spectrum",
            "wave length",
            "wavelength",
            "frequency",
            "visible",
            "ultra-violet",
            "x-rays",
        ],
        "concept": "concepts/radiation",
        "why": "This passage may connect physical radiation, waves, visible light, measurement, and illumination practice.",
    },
    "power-systems": {
        "label": "Power Systems And Apparatus",
        "patterns": [
            "generator",
            "motor",
            "transformer",
            "station",
            "transmission",
            "distribution",
            "short circuit",
            "synchronism",
            "synchronizing",
            "reactor",
        ],
        "concept": "concepts/power-limiting-reactors",
        "why": "This passage may connect Steinmetz's mathematics to real apparatus, stations, protection, and operation.",
    },
    "engineering-philosophy": {
        "label": "Engineering Philosophy",
        "patterns": [
            "engineer",
            "engineering",
            "science",
            "industrial",
            "civilization",
            "society",
            "co-operation",
            "competition",
            "knowledge",
        ],
        "concept": "who-was-steinmetz",
        "why": "This passage may show Steinmetz as a thinker about engineering, society, education, or scientific method.",
    },
}

SIGNAL_PATTERNS = [
    ("definition", re.compile(r"\b(is|are|means|called|defined as|known as)\b", re.I), 18),
    ("distinction", re.compile(r"\b(not|not merely|not only|rather|different from|distinguish)\b", re.I), 18),
    ("causal-logic", re.compile(r"\b(hence|therefore|thus|thereby|consequently|it follows)\b", re.I), 16),
    ("physical-meaning", re.compile(r"\b(energy|force|power|work|storage|dissipation|loss)\b", re.I), 14),
    ("historical-language", re.compile(r"\b(ether|Faraday|Maxwell|Hertz|Tesla|Newton|relativity)\b", re.I), 18),
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "untitled"


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def clean_text(value: Any, limit: int | None = None) -> str:
    text = "" if value is None else str(value)
    replacements = {
        "\u00a0": " ",
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\ufeff": "",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"\s+", " ", text).strip()
    if limit and len(text) > limit:
        return text[: limit - 3].rstrip() + "..."
    return text


def md_escape(value: Any) -> str:
    return (
        clean_text(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("|", "\\|")
    )


def html_escape(value: Any) -> str:
    return (
        clean_text(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def source_page_slug(record: dict[str, Any]) -> str:
    path = Path(str(record.get("text_path") or ""))
    return slugify(path.stem or str(record.get("id") or record.get("title") or "section"))


def source_text_url(source_id: str, record: dict[str, Any]) -> str:
    return f"{BASE_URL}/source-texts/{source_id}/{source_page_slug(record)}/"


def workbench_url(source_id: str, record: dict[str, Any]) -> str:
    return f"{BASE_URL}/chapter-workbench/{source_id}/{source_page_slug(record)}/"


def chapter_label(record: dict[str, Any]) -> str:
    kind = str(record.get("kind") or "section").replace("-", " ").title()
    number = record.get("number") or record.get("sequence")
    title = clean_text(record.get("title") or "Untitled")
    if number:
        return f"{kind} {number}: {title}"
    return f"{kind}: {title}"


def paragraph_blocks(text: str) -> list[tuple[int, int, str]]:
    blocks: list[tuple[int, int, str]] = []
    current: list[str] = []
    start_line = 1
    for index, line in enumerate(text.splitlines(), start=1):
        if line.strip():
            if not current:
                start_line = index
            current.append(line.strip())
        elif current:
            paragraph = clean_text(" ".join(current))
            blocks.append((start_line, index - 1, paragraph))
            current = []
    if current:
        paragraph = clean_text(" ".join(current))
        blocks.append((start_line, len(text.splitlines()), paragraph))
    return blocks


def theme_hits(text: str) -> dict[str, int]:
    lower = f" {text.lower()} "
    counts: dict[str, int] = {}
    for theme_id, theme in THEMES.items():
        count = 0
        for pattern in theme["patterns"]:
            pattern_lower = pattern.lower()
            count += lower.count(pattern_lower)
            if "-" in pattern_lower:
                count += lower.count(pattern_lower.replace("-", " "))
        if count:
            counts[theme_id] = count
    return counts


def signal_hits(text: str) -> list[str]:
    hits = []
    for label, pattern, _weight in SIGNAL_PATTERNS:
        if pattern.search(text):
            hits.append(label)
    return hits


def score_passage(text: str, themes: dict[str, int], signals: list[str]) -> int:
    word_count = len(re.findall(r"[A-Za-z][A-Za-z'-]*", text))
    if word_count < 45 or word_count > 260:
        return 0
    score = 0
    for theme_id, count in themes.items():
        score += min(count, 10) * (16 if theme_id in {"ether-and-relativity", "field-language"} else 12)
    for label, _pattern, weight in SIGNAL_PATTERNS:
        if label in signals:
            score += weight
    if len(themes) >= 2:
        score += 18
    if len(themes) >= 3:
        score += 20
    if 70 <= word_count <= 170:
        score += 12
    return score


def lane_for(themes: dict[str, int], signals: list[str]) -> str:
    ranked = [theme for theme, _count in Counter(themes).most_common()]
    if "ether-and-relativity" in themes:
        return "ether-field-boundary"
    if "symbolic-ac" in themes:
        return "mathematical-language"
    if "transients-waves-surges" in themes:
        return "transient-and-wave-reasoning"
    if "field-language" in themes or "dielectric-capacity" in themes:
        return "field-language"
    if "magnetism-hysteresis" in themes:
        return "magnetic-material-language"
    if "definition" in signals or "distinction" in signals:
        return "definition-or-distinction"
    return ranked[0] if ranked else "general-reader-gem"


def why_review(themes: dict[str, int], lane: str) -> str:
    if not themes:
        return "Candidate passage selected for editorial review; verify against scan before promotion."
    top_theme = max(themes, key=themes.get)
    theme = THEMES[top_theme]
    return str(theme.get("why") or f"Candidate passage for the {lane} lane.")


def collect_passages(root: Path) -> list[dict[str, Any]]:
    catalog = load_json(root / "sources" / "source_catalog.json", [])
    if not isinstance(catalog, list):
        return []

    records: list[dict[str, Any]] = []
    for source in catalog:
        source_id = str(source.get("source_id") or "")
        if not source_id:
            continue
        chapters = load_json(root / "processed" / source_id / "chapters.json", [])
        if not isinstance(chapters, list):
            continue
        for chapter in chapters:
            if not isinstance(chapter, dict):
                continue
            text_path = root / str(chapter.get("text_path") or "")
            if not text_path.exists():
                continue
            text = text_path.read_text(encoding="utf-8", errors="replace")
            for local_start, local_end, paragraph in paragraph_blocks(text):
                themes = theme_hits(paragraph)
                if not themes:
                    continue
                signals = signal_hits(paragraph)
                score = score_passage(paragraph, themes, signals)
                if score <= 0:
                    continue
                source_line_start = int(chapter.get("line_start") or 0) + local_start - 1
                source_line_end = int(chapter.get("line_start") or 0) + local_end - 1
                lane = lane_for(themes, signals)
                record_id = f"{source_id}-{source_page_slug(chapter)}-passage-{local_start}"
                records.append(
                    {
                        "id": record_id,
                        "source_id": source_id,
                        "source_title": source.get("title"),
                        "year": source.get("year"),
                        "section_id": chapter.get("id"),
                        "section_label": chapter_label(chapter),
                        "section_slug": source_page_slug(chapter),
                        "line_start": source_line_start,
                        "line_end": source_line_end,
                        "local_line_start": local_start,
                        "local_line_end": local_end,
                        "score": score,
                        "lane": lane,
                        "themes": sorted(themes, key=lambda item: (-themes[item], item)),
                        "theme_counts": themes,
                        "signals": signals,
                        "passage": clean_text(paragraph, 920),
                        "why_review": why_review(themes, lane),
                        "status": "ocr-derived-passage-candidate",
                        "verification": "needs scan verification before exact quotation",
                        "links": {
                            "source_text": source_text_url(source_id, chapter),
                            "workbench": workbench_url(source_id, chapter),
                            "source_overview": f"{BASE_URL}/sources/{source_id}/",
                            "book_coverage": f"{BASE_URL}/book-coverage/{source_id}/",
                        },
                    }
                )
    records.sort(key=lambda item: (-int(item["score"]), str(item["source_title"]), str(item["section_label"])))
    return records


def balanced_subset(records: list[dict[str, Any]], limit_per_source: int = 10, global_limit: int = 180) -> list[dict[str, Any]]:
    counts: Counter[str] = Counter()
    selected: list[dict[str, Any]] = []
    for record in records:
        source_id = str(record["source_id"])
        if counts[source_id] >= limit_per_source:
            continue
        selected.append(record)
        counts[source_id] += 1
        if len(selected) >= global_limit:
            break
    return selected


def theme_subsets(records: list[dict[str, Any]], limit: int = 36) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        for theme in record["themes"]:
            if len(grouped[theme]) < limit:
                grouped[theme].append(record)
    return dict(grouped)


def render_passage_card(record: dict[str, Any], rank: int | None = None) -> str:
    themes = ", ".join(THEMES[theme]["label"] for theme in record["themes"][:4] if theme in THEMES)
    rank_text = f"<span>#{rank}</span>" if rank else ""
    passage = md_escape(record["passage"])
    return f"""<article class="passage-card" data-layer="source">
  <header>
    {rank_text}
    <strong>{md_escape(record["section_label"])}</strong>
    <small>{md_escape(record["source_title"])} ({md_escape(record["year"])}) - lines {md_escape(record["line_start"])}-{md_escape(record["line_end"])}</small>
  </header>
  <p>{passage}</p>
  <footer>
    <em>{md_escape(record["why_review"])}</em>
    <small>Themes: {md_escape(themes)} - Lane: <code>{md_escape(record["lane"])}</code></small>
    <nav>
      <a href="{html_escape(record["links"]["source_text"])}">Read source</a>
      <a href="{html_escape(record["links"]["workbench"])}">Research review</a>
    </nav>
  </footer>
</article>"""


def render_signal_stats(records: list[dict[str, Any]]) -> str:
    source_count = len({record["source_id"] for record in records})
    theme_count = len({theme for record in records for theme in record["themes"]})
    return f"""<div class="codex-signal">
  <div><strong>{len(records)}</strong><p>ranked passage candidates in the balanced public atlas.</p></div>
  <div><strong>{source_count}</strong><p>processed Steinmetz sources represented.</p></div>
  <div><strong>{theme_count}</strong><p>source-grounded themes routing the passages.</p></div>
</div>"""


def build_atlas_index(records: list[dict[str, Any]], grouped: dict[str, list[dict[str, Any]]]) -> str:
    theme_cards = []
    for theme_id, theme in THEMES.items():
        count = len(grouped.get(theme_id, []))
        theme_cards.append(
            f'<a href="{BASE_URL}/passage-atlas/{theme_id}/">{html_escape(theme["label"])}<span>{count} top candidate passages. {html_escape(theme["why"])}</span></a>'
        )
    cards = "\n".join(render_passage_card(record, index + 1) for index, record in enumerate(records[:24]))
    return f"""---
title: Passage Atlas
description: Source-grounded candidate passage atlas across processed Steinmetz texts.
---

{GENERATED_NOTE}

The passage atlas is a discovery layer for the now-large Steinmetz corpus. It surfaces dense source-text passages for review without turning OCR snippets into finished quotations.

<div class="source-text-warning" data-layer="source">
  <strong>Use rule:</strong> every passage below is an OCR/PDF-text candidate. Open the source scan before quoting, interpreting, or promoting it into a concept page.
</div>

{render_signal_stats(records)}

## Theme Doors

<div class="source-matrix">
{chr(10).join(theme_cards)}
</div>

## Highest-Value Candidate Passages

<div class="passage-card-grid">
{cards}
</div>
"""


def build_theme_page(theme_id: str, theme: dict[str, Any], records: list[dict[str, Any]]) -> str:
    cards = "\n".join(render_passage_card(record, index + 1) for index, record in enumerate(records[:36]))
    related = theme.get("concept", "")
    return f"""---
title: {yaml_quote(str(theme["label"]) + " Passage Atlas")}
description: {yaml_quote("Candidate source passages for " + str(theme["label"]))}
---

{GENERATED_NOTE}

<div class="source-text-warning" data-layer="source">
  <strong>Candidate evidence only.</strong>
  <p>These passages are ranked from OCR/PDF text and must be checked against the scan before exact quotation.</p>
</div>

<div class="source-text-toolbar" data-layer="source">
  <a href="{BASE_URL}/passage-atlas/">Back to passage atlas</a>
  <a href="{BASE_URL}/{html_escape(related)}/">Related concept or route</a>
</div>

## Why This Theme Matters

{md_escape(theme["why"])}

## Candidate Passages

<div class="passage-card-grid">
{cards}
</div>
"""


def build_hidden_gems_page(records: list[dict[str, Any]]) -> str:
    cards = "\n".join(render_passage_card(record, index + 1) for index, record in enumerate(records[:42]))
    return f"""---
title: Hidden Gems
description: Overlooked passages and technically rich conceptual moments.
---

{GENERATED_NOTE}

Hidden gems are not quote cards until the wording and page reference have been checked against the scan. This page now uses the passage atlas to expose candidate gems across the processed corpus while keeping review status visible.

<div class="source-text-warning" data-layer="source">
  <strong>Review rule:</strong> read the source first, verify the scan second, then promote the passage into a finished hidden-gem entry with exact wording, page reference, modern reading, and interpretation boundaries.
</div>

<div class="source-matrix">
  <a href="{BASE_URL}/passage-atlas/">Open full passage atlas<span>Browse ranked candidate passages by theme.</span></a>
  <a href="{BASE_URL}/roadmap/deep-decoding-promotion-queue/">Open deep-decoding queue<span>See which sections should become full hand-curated pages next.</span></a>
  <a href="{BASE_URL}/source-texts/">Read source text directly<span>Go back to Steinmetz before reading commentary.</span></a>
</div>

## Seed Themes To Promote

<div class="research-passages">
  <section data-layer="source"><h3>Radiation Is Not Heat</h3><p>Promote the opening radiation passage only after checking the printed text around Lecture I.</p></section>
  <section data-layer="source"><h3>Symbolic Method As Physical Translation</h3><p>Prioritize the AC symbolic-method passages where Steinmetz moves from vector geometry to algebra.</p></section>
  <section data-layer="source"><h3>Transients Reveal Stored Energy</h3><p>Prioritize passages where permanent and temporary terms, damping, and oscillation are distinguished.</p></section>
  <section data-layer="source"><h3>Ether And Field Boundary</h3><p>Promote only exact source wording; keep modern physics and ether-field interpretation separate.</p></section>
</div>

## Candidate Hidden Gems

<div class="passage-card-grid">
{cards}
</div>
"""


def route_records(
    records: list[dict[str, Any]],
    themes: list[str],
    limit: int = 6,
    source_ids: list[str] | None = None,
    required_themes: list[str] | None = None,
    exclude_lanes: list[str] | None = None,
    preferred_sections: list[tuple[str, str]] | None = None,
) -> list[dict[str, Any]]:
    selected = []
    seen_sections = set()
    source_ids = source_ids or []
    required_themes = required_themes or []
    exclude_lanes = exclude_lanes or []
    preferred_sections = preferred_sections or []

    for preferred_source, preferred_slug in preferred_sections:
        for record in records:
            if record["section_id"] in seen_sections:
                continue
            if record["source_id"] == preferred_source and record["section_slug"] == preferred_slug:
                selected.append(record)
                seen_sections.add(record["section_id"])
                break
        if len(selected) >= limit:
            return selected

    for record in records:
        record_themes = record["themes"]
        if record["section_id"] in seen_sections:
            continue
        if source_ids and record["source_id"] not in source_ids:
            continue
        if record["lane"] in exclude_lanes:
            continue
        if required_themes and not all(theme in record_themes for theme in required_themes):
            continue
        if any(theme in record_themes[:4] for theme in themes):
            selected.append(record)
            seen_sections.add(record["section_id"])
        if len(selected) >= limit:
            break
    return selected


def build_research_map(records: list[dict[str, Any]]) -> str:
    routes = [
        {
            "id": "first-reader",
            "title": "A First Reader's Path",
            "themes": ["radiation-light", "engineering-philosophy"],
            "source_ids": ["radiation-light-and-illumination", "general-lectures-electrical-engineering"],
            "exclude_lanes": ["ether-field-boundary"],
            "preferred_sections": [
                ("radiation-light-and-illumination", "lecture-01"),
                ("radiation-light-and-illumination", "lecture-06"),
                ("general-lectures-electrical-engineering", "lecture-07"),
            ],
            "why": "Start with readable source passages before moving into AC and transient mathematics.",
        },
        {
            "id": "ac-mathematics",
            "title": "AC Mathematics And Symbolic Method",
            "themes": ["symbolic-ac", "power-systems"],
            "required_themes": ["symbolic-ac"],
            "why": "Follow vectors, complex quantities, reactance, impedance, admittance, and apparatus.",
        },
        {
            "id": "field-and-ether",
            "title": "Field Language And Ether Boundaries",
            "themes": ["field-language", "ether-and-relativity", "dielectric-capacity"],
            "why": "Separate explicit Steinmetz wording, modern field theory, and later ether-field interpretation.",
        },
        {
            "id": "transient-science",
            "title": "Transients, Waves, Surges",
            "themes": ["transients-waves-surges", "dielectric-capacity", "power-systems"],
            "required_themes": ["transients-waves-surges"],
            "why": "Study the time-domain and line phenomena that steady-state teaching often hides.",
        },
        {
            "id": "magnetic-materials",
            "title": "Magnetism, Hysteresis, Material Loss",
            "themes": ["magnetism-hysteresis", "field-language", "symbolic-ac"],
            "required_themes": ["magnetism-hysteresis"],
            "why": "Trace field, flux, permeability, hysteresis, and effective resistance across sources.",
        },
    ]
    route_blocks = []
    for route in routes:
        selected = route_records(
            records,
            route["themes"],
            5,
            source_ids=route.get("source_ids"),
            required_themes=route.get("required_themes"),
            exclude_lanes=route.get("exclude_lanes"),
            preferred_sections=route.get("preferred_sections"),
        )
        cards = "\n".join(
            f"""<li>
  <a href="{html_escape(record["links"]["source_text"])}">{md_escape(record["section_label"])}</a>
  <span>{md_escape(record["source_title"])} - {md_escape(record["lane"])}</span>
</li>"""
            for record in selected
        )
        route_blocks.append(
            f"""<section class="research-map-route" id="{html_escape(route["id"])}">
  <h2>{md_escape(route["title"])}</h2>
  <p>{md_escape(route["why"])}</p>
  <ul class="study-link-list">
    {cards}
  </ul>
</section>"""
        )
    return f"""---
title: Research Map
description: A reader-facing map across Steinmetz sources, concepts, passages, and verification layers.
---

{GENERATED_NOTE}

The research map is the public orientation layer for a large, scholarly archive. It keeps the academic structure intact, but gives ordinary readers and serious researchers a shorter path into the material.

<div class="source-matrix">
  <a href="{BASE_URL}/start-reading/">Start reading<span>A simple first doorway for new readers.</span></a>
  <a href="{BASE_URL}/book-coverage/">Browse all processed books<span>Every source represented with section counts and source links.</span></a>
  <a href="{BASE_URL}/passage-atlas/">Open passage atlas<span>Dense source passages ranked for review.</span></a>
  <a href="{BASE_URL}/concepts/dossier-index/">Open concept dossiers<span>Source-grounded concept pages and concordance links.</span></a>
</div>

## Research Routes

<div class="research-map-grid">
{chr(10).join(route_blocks)}
</div>

## How To Read Without Getting Lost

1. Begin with a source passage, not a theory about the passage.
2. Use the workbench page to see equations, diagrams, concepts, glossary terms, and review tasks.
3. Move to concept pages only after the source language is visible.
4. Treat modern engineering explanations and ether-field readings as labeled layers, not as substitutes for Steinmetz's wording.
"""


def build_curriculum(records: list[dict[str, Any]]) -> str:
    levels = [
        ("Hour 1", ["radiation-light"], "Meet Steinmetz through readable radiation and light passages."),
        ("Day 1", ["symbolic-ac"], "Add the first AC symbolic-method passages."),
        ("Week 1", ["transients-waves-surges"], "Move into impedance, admittance, temporary terms, and oscillations."),
        ("Month 1", ["magnetism-hysteresis", "dielectric-capacity", "field-language"], "Build the deeper field, material, and energy-storage vocabulary."),
        ("Contributor Track", ["ether-and-relativity", "power-systems"], "Verify exact passages, promote figures/equations, and prepare review notes."),
    ]
    blocks = []
    for label, themes, why in levels:
        selected = route_records(
            records,
            themes,
            8,
            source_ids=["radiation-light-and-illumination", "general-lectures-electrical-engineering"]
            if label == "Hour 1"
            else None,
            required_themes=themes if label in {"Day 1", "Week 1"} else None,
            exclude_lanes=["ether-field-boundary"] if label == "Hour 1" else None,
            preferred_sections=[
                ("radiation-light-and-illumination", "lecture-01"),
                ("radiation-light-and-illumination", "lecture-06"),
                ("general-lectures-electrical-engineering", "lecture-07"),
            ]
            if label == "Hour 1"
            else None,
        )
        links = "\n".join(
            f"- [{md_escape(record['section_label'])}]({record['links']['source_text']}) - {md_escape(record['source_title'])}"
            for record in selected
        )
        blocks.append(f"## {label}\n\n{why}\n\n{links}\n")
    return f"""---
title: Steinmetz Study Curriculum
description: A staged source-first curriculum through the current Steinmetz corpus.
---

{GENERATED_NOTE}

This curriculum is a source-first path through the processed corpus. It is not a simplified replacement for the archive; it is a path through it.

{chr(10).join(blocks)}
"""


def write_pages(root: Path, records: list[dict[str, Any]], grouped: dict[str, list[dict[str, Any]]]) -> None:
    docs = root / "site" / "src" / "content" / "docs"
    atlas_dir = docs / "passage-atlas"
    if atlas_dir.exists():
        shutil.rmtree(atlas_dir)
    atlas_dir.mkdir(parents=True, exist_ok=True)
    write_text(atlas_dir / "index.mdx", build_atlas_index(records, grouped))
    for theme_id, theme in THEMES.items():
        write_text(atlas_dir / theme_id / "index.mdx", build_theme_page(theme_id, theme, grouped.get(theme_id, [])))
    write_text(docs / "hidden-gems" / "index.mdx", build_hidden_gems_page(records))
    research_map_dir = docs / "research-map"
    research_map_dir.mkdir(parents=True, exist_ok=True)
    write_text(research_map_dir / "index.mdx", build_research_map(records))
    write_text(research_map_dir / "study-curriculum.mdx", build_curriculum(records))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()
    root = Path(args.root).resolve()

    all_records = collect_passages(root)
    balanced = balanced_subset(all_records)
    grouped = theme_subsets(balanced)
    payload = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Passage atlas records are OCR/PDF-text discovery aids. Exact quotation and claims require scan verification.",
        "total_candidate_records": len(all_records),
        "public_balanced_records": len(balanced),
        "theme_counts": {theme: len(records) for theme, records in grouped.items()},
        "records": balanced,
    }
    write_json(root / "processed" / "passage_atlas.json", payload)
    write_json(root / "site" / "public" / "data" / "passage_atlas.json", payload)
    write_pages(root, balanced, grouped)
    print(f"Generated passage atlas with {len(balanced)} public records from {len(all_records)} candidates.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
