#!/usr/bin/env python3
"""Generate a public figure candidate atlas.

This atlas is a visual-research routing layer. It does not claim that OCR
figure captions are exact, but it gives readers and reviewers one place to see
which original scan crops are already promoted and where the remaining figure
candidates occur in the processed source text.
"""

from __future__ import annotations

import html
import json
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_figure_candidate_atlas.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def html_escape(value: Any) -> str:
    text = html.escape("" if value is None else str(value), quote=True)
    # MDX still parses markdown emphasis in raw HTML text nodes. Candidate OCR
    # captions frequently contain characters such as `*`, `_`, and backticks.
    # Convert those to entities so the atlas stays a literal verification table.
    return (
        text.replace("\\", "&#92;")
        .replace("*", "&#42;")
        .replace("_", "&#95;")
        .replace("`", "&#96;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
    )


def site_url(path: str | None) -> str:
    if not path:
        return ""
    if path.startswith(BASE_URL):
        return path
    if path.startswith("/"):
        return f"{BASE_URL}{path}"
    return f"{BASE_URL}/{path}"


def clean_caption(value: Any) -> str:
    text = re.sub(r"\s+", " ", "" if value is None else str(value)).strip()
    return text[:420] + " ..." if len(text) > 420 else text


def find_section(records: list[dict[str, Any]], source_id: str, line: int | None) -> dict[str, Any] | None:
    if line is None:
        return None
    for record in records:
        if record.get("source_id") != source_id:
            continue
        start = record.get("line_start")
        end = record.get("line_end")
        if isinstance(start, int) and isinstance(end, int) and start <= line <= end:
            return record
    return None


def build_source_meta(workbench_records: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    meta: dict[str, dict[str, Any]] = {}
    for record in workbench_records:
        source_id = str(record.get("source_id", ""))
        if not source_id or source_id in meta:
            continue
        meta[source_id] = {
            "source_id": source_id,
            "title": record.get("source_title") or source_id,
            "year": record.get("year"),
            "source_overview": f"{BASE_URL}/sources/{source_id}/",
            "source_text_index": f"{BASE_URL}/source-texts/{source_id}/",
            "workbench_index": f"{BASE_URL}/chapter-workbench/{source_id}/",
            "book_coverage": f"{BASE_URL}/book-coverage/{source_id}/",
        }
    return meta


def enriched_candidate(candidate: dict[str, Any], workbench_records: list[dict[str, Any]]) -> dict[str, Any]:
    source_ref = candidate.get("source_ref") or {}
    source_id = str(candidate.get("source_id") or source_ref.get("source_id") or "")
    line = source_ref.get("line_start")
    line_number = line if isinstance(line, int) else None
    section = find_section(workbench_records, source_id, line_number)
    links: dict[str, str] = {
        "source_overview": f"{BASE_URL}/sources/{source_id}/",
        "source_text_index": f"{BASE_URL}/source-texts/{source_id}/",
        "workbench_index": f"{BASE_URL}/chapter-workbench/{source_id}/",
    }
    if section:
        links.update(
            {
                "source_text": section.get("links", {}).get("source_text", ""),
                "workbench": f"{BASE_URL}/chapter-workbench/{source_id}/{section.get('slug')}/",
                "book_coverage": f"{BASE_URL}/book-coverage/{source_id}/",
            }
        )
    return {
        "id": candidate.get("id"),
        "source_id": source_id,
        "source_title": candidate.get("source_title"),
        "figure_number": candidate.get("figure_number"),
        "caption": clean_caption(candidate.get("caption")),
        "status": candidate.get("status"),
        "verification": source_ref.get("verification"),
        "line_start": line_number,
        "section_id": section.get("id") if section else None,
        "section_label": section.get("label") if section else None,
        "section_slug": section.get("slug") if section else None,
        "links": links,
    }


def enriched_promoted(record: dict[str, Any], source_meta: dict[str, dict[str, Any]]) -> dict[str, Any]:
    source_id = str(record.get("source_id", ""))
    meta = source_meta.get(source_id, {})
    return {
        "id": record.get("id"),
        "source_id": source_id,
        "source_title": meta.get("title") or source_id,
        "status": record.get("status"),
        "source_location": record.get("source_location"),
        "output_path": record.get("output_path"),
        "manifest_path": record.get("manifest_path"),
        "public_url": site_url(record.get("public_path") or record.get("public_url")),
        "width": record.get("width"),
        "height": record.get("height"),
        "sha256": record.get("sha256"),
        "quality_note": record.get("quality_note"),
        "links": {
            "source_overview": meta.get("source_overview") or f"{BASE_URL}/sources/{source_id}/",
            "diagram_archive": f"{BASE_URL}/diagrams/",
            "figure_queue": f"{BASE_URL}/roadmap/figure-verification-queue/",
        },
    }


def build_atlas(root: Path) -> dict[str, Any]:
    figure_index = load_json(root / "processed" / "figure_index.json", {})
    workbench = load_json(root / "processed" / "chapter_workbench.json", {})
    workbench_records = list(workbench.get("records") or [])
    source_meta = build_source_meta(workbench_records)

    candidates = [
        enriched_candidate(candidate, workbench_records)
        for candidate in figure_index.get("candidate_records", [])
    ]
    promoted = [
        enriched_promoted(record, source_meta)
        for record in figure_index.get("promoted_original_figures", [])
    ]

    candidates_by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for candidate in candidates:
        candidates_by_source[str(candidate.get("source_id"))].append(candidate)
        source_id = str(candidate.get("source_id"))
        if source_id and source_id not in source_meta:
            source_meta[source_id] = {
                "source_id": source_id,
                "title": candidate.get("source_title") or source_id,
                "year": None,
                "source_overview": f"{BASE_URL}/sources/{source_id}/",
                "source_text_index": f"{BASE_URL}/source-texts/{source_id}/",
                "workbench_index": f"{BASE_URL}/chapter-workbench/{source_id}/",
                "book_coverage": f"{BASE_URL}/book-coverage/{source_id}/",
            }

    promoted_by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in promoted:
        promoted_by_source[str(record.get("source_id"))].append(record)

    source_summaries = []
    for source_id, meta in sorted(source_meta.items(), key=lambda item: str(item[1].get("title"))):
        source_candidates = candidates_by_source.get(source_id, [])
        source_promoted = promoted_by_source.get(source_id, [])
        source_summaries.append(
            {
                **meta,
                "candidate_count": len(source_candidates),
                "promoted_crop_count": len(source_promoted),
                "candidate_figures_with_section_links": sum(1 for item in source_candidates if item.get("section_id")),
                "first_candidate_ids": [item.get("id") for item in source_candidates[:8]],
            }
        )

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": (
            "Figure captions are OCR/PDF-text candidates unless a scan crop and manifest are present. "
            "Use this atlas as a routing and verification aid, not as final diagram canon."
        ),
        "candidate_total_records": len(candidates),
        "promoted_original_figure_count": len(promoted),
        "source_count": len(source_summaries),
        "source_summaries": source_summaries,
        "promoted_original_figures": promoted,
        "candidate_records": candidates,
    }


def candidate_sort_key(record: dict[str, Any]) -> tuple[int, int, str]:
    fig = record.get("figure_number")
    line = record.get("line_start")
    return (
        int(line) if isinstance(line, int) else 999999999,
        int(fig) if isinstance(fig, int) else 999999999,
        str(record.get("id", "")),
    )


def promoted_card(record: dict[str, Any]) -> str:
    public_url = html_escape(record.get("public_url"))
    return f"""  <div class="codex-visual-card">
    <img src="{public_url}" alt="Original Steinmetz scan crop {html_escape(record.get('id'))}" />
    <div>
      <strong>{html_escape(record.get('id'))}</strong>
      <p>{html_escape(record.get('source_title'))}</p>
      <p>{html_escape(record.get('source_location'))}</p>
      <p><a href="{public_url}">Open image</a> - <a href="{html_escape(record.get('links', {}).get('figure_queue'))}">verification card</a></p>
    </div>
  </div>"""


def source_summary_rows(source_summaries: list[dict[str, Any]]) -> str:
    rows = []
    for source in sorted(source_summaries, key=lambda item: item.get("candidate_count", 0), reverse=True):
        rows.append(
            "<tr>"
            f"<td><a href=\"{html_escape(source.get('book_coverage'))}\">{html_escape(source.get('title'))}</a></td>"
            f"<td>{html_escape(source.get('year') or '')}</td>"
            f"<td>{html_escape(source.get('candidate_count'))}</td>"
            f"<td>{html_escape(source.get('promoted_crop_count'))}</td>"
            f"<td>{html_escape(source.get('candidate_figures_with_section_links'))}</td>"
            f"<td><a href=\"{html_escape(source.get('source_text_index'))}\">source text</a> - <a href=\"{html_escape(source.get('workbench_index'))}\">research review</a></td>"
            "</tr>"
        )
    return "\n".join(rows)


def candidate_table(records: list[dict[str, Any]]) -> str:
    rows = []
    for record in sorted(records, key=candidate_sort_key):
        line = record.get("line_start")
        section_link = record.get("links", {}).get("source_text") or record.get("links", {}).get("source_text_index")
        workbench_link = record.get("links", {}).get("workbench") or record.get("links", {}).get("workbench_index")
        section = record.get("section_label") or "source index"
        fig = record.get("figure_number")
        fig_label = f"Fig. {fig}" if fig else record.get("id")
        rows.append(
            "<tr>"
            f"<td>{html_escape(fig_label)}</td>"
            f"<td>{html_escape(record.get('caption'))}</td>"
            f"<td>{html_escape('line ' + str(line) if line else '')}</td>"
            f"<td>{html_escape(section)}</td>"
            f"<td><a href=\"{html_escape(section_link)}\">text</a> - <a href=\"{html_escape(workbench_link)}\">research review</a></td>"
            f"<td>{html_escape(record.get('verification') or record.get('status'))}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def build_page(atlas: dict[str, Any]) -> str:
    promoted = atlas.get("promoted_original_figures", [])
    candidates = atlas.get("candidate_records", [])
    by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for candidate in candidates:
        by_source[str(candidate.get("source_id"))].append(candidate)

    meta_by_source = {source["source_id"]: source for source in atlas.get("source_summaries", [])}
    source_sections = []
    for source_id, records in sorted(by_source.items(), key=lambda item: len(item[1]), reverse=True):
        meta = meta_by_source.get(source_id, {"title": source_id})
        open_attr = " open" if len(source_sections) < 3 else ""
        source_sections.append(
            f"""<details class="figure-source-panel"{open_attr}>
  <summary>{html_escape(meta.get('title'))} <span>{len(records)} candidate figure references - {html_escape(meta.get('promoted_crop_count', 0))} promoted crops</span></summary>
  <div class="source-matrix figure-source-links">
    <a href="{html_escape(meta.get('book_coverage'))}">Book coverage<span>Open the section map for this source.</span></a>
    <a href="{html_escape(meta.get('source_text_index'))}">Source text<span>Read the OCR/PDF text around figure references.</span></a>
    <a href="{html_escape(meta.get('workbench_index'))}">Research review<span>Review concepts, equations, figures, snippets, and promotion actions.</span></a>
    <a href="{BASE_URL}/roadmap/figure-verification-queue/">Crop review queue<span>Open promoted scan-crop verification cards.</span></a>
  </div>
  <table class="codex-status-table figure-candidate-table">
    <thead>
      <tr>
        <th>Figure</th>
        <th>OCR/PDF-Text Caption Candidate</th>
        <th>Location</th>
        <th>Section</th>
        <th>Open</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
{candidate_table(records)}
    </tbody>
  </table>
</details>"""
        )

    return f"""---
title: "Figure Candidate Atlas"
description: "Visual routing atlas for original Steinmetz scan crops and candidate figure references."
---

{GENERATED_NOTE}

This atlas makes the visual side of the archive explicit. It separates original scan-derived crops from OCR/PDF-text figure references, then routes each candidate back to the source text and chapter workbench for verification.

<div class="coverage-hero figure-atlas-hero">
  <div>
    <p class="home-kicker">Diagram research layer</p>
    <h1>Original Crops, Candidate Figures, And Verification Routes</h1>
    <p>Use this page to see what is already visually promoted, what still needs cropping, and where each candidate figure reference appears in the processed corpus.</p>
  </div>
  <div class="coverage-stat-grid">
    <div><strong>{html_escape(atlas.get('promoted_original_figure_count'))}</strong><p>promoted scan crops</p><span>with manifests and checksums</span></div>
    <div><strong>{html_escape(atlas.get('candidate_total_records'))}</strong><p>figure references</p><span>OCR/PDF-text candidates needing review</span></div>
    <div><strong>{html_escape(atlas.get('source_count'))}</strong><p>sources represented</p><span>book and report-level visual routing</span></div>
    <div><strong>{html_escape(sum(1 for item in candidates if item.get('section_id')))}</strong><p>section-linked candidates</p><span>direct text/workbench routes</span></div>
  </div>
</div>

## Reader Routes

<div class="source-matrix">
  <a href="{BASE_URL}/diagrams/">Diagram archive<span>Open the curated visual gallery of original crops and recreated guide diagrams.</span></a>
  <a href="{BASE_URL}/roadmap/figure-verification-queue/">Figure verification queue<span>Review crop metadata, page references, labels, checksums, and legibility.</span></a>
  <a href="{BASE_URL}/book-coverage/">Book coverage atlas<span>Find visual density source by source, then open the sections that contain figures.</span></a>
  <a href="{BASE_URL}/chapter-workbench/">Research review<span>Use section pages to see figure candidates beside equations, concepts, glossary hits, and source snippets.</span></a>
</div>

## Promoted Original Scan Crops

These are not interpretive redraws. They are documentary scan crops with source-location and checksum records, still awaiting second-pass review before final canonical status.

<div class="codex-visual-grid figure-promoted-grid">
{chr(10).join(promoted_card(record) for record in promoted)}
</div>

## Source-Level Figure Coverage

<table class="codex-status-table figure-source-summary">
  <thead>
    <tr>
      <th>Source</th>
      <th>Year</th>
      <th>Candidate References</th>
      <th>Promoted Crops</th>
      <th>Section-Linked</th>
      <th>Open</th>
    </tr>
  </thead>
  <tbody>
{source_summary_rows(atlas.get('source_summaries', []))}
  </tbody>
</table>

## Candidate Figure References By Source

The rows below are OCR/PDF-text candidates. Captions may include nearby text, line breaks, OCR mistakes, or partial figure labels. Treat them as a locator for scan review, not a final caption.

{chr(10).join(source_sections)}

## Promotion Rule

Before any candidate becomes canonical, it needs a source-page check, a crop or extracted image where available, a manifest with checksum, a clean caption, links to the relevant concept/equation pages, and a clear separation between original figure, modern redraw, and interpretive annotation.
"""


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    atlas = build_atlas(root)
    write_json(root / "processed" / "figure_candidate_atlas.json", atlas)
    write_text(root / "site" / "src" / "content" / "docs" / "diagrams" / "figure-candidate-atlas.mdx", build_page(atlas))
    print(
        "Generated figure candidate atlas with "
        f"{atlas['promoted_original_figure_count']} promoted crops and "
        f"{atlas['candidate_total_records']} figure candidates."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
