#!/usr/bin/env python3
"""Generate a source-by-source completion audit for the Steinmetz archive.

This audit is deliberately conservative. It does not claim the archive is
complete because pages exist; it measures whether each source has custody,
structure, public readers, workbench coverage, candidate indexes, diagrams, and
curated pages needed before expert review can promote it toward canonical
status.
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_completion_audit.py. Do not edit by hand. */}"

CATALOG_FILES = {
    "chapters": "chapters.json",
    "concepts": "concepts.json",
    "equations": "equations.json",
    "figures": "figures.json",
    "glossary": "glossary.json",
    "quotes": "quotes.json",
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def count_records(path: Path) -> int:
    loaded = load_json(path, [])
    return len(loaded) if isinstance(loaded, list) else 0


def count_files(path: Path, pattern: str) -> int:
    if not path.exists():
        return 0
    return len([item for item in path.glob(pattern) if item.is_file()])


def count_recursive_files(path: Path, pattern: str) -> int:
    if not path.exists():
        return 0
    return len([item for item in path.rglob(pattern) if item.is_file()])


def count_curated_source_pages(root: Path, source_id: str) -> int:
    source_docs = root / "site" / "src" / "content" / "docs" / "sources" / source_id
    if not source_docs.exists():
        return 0
    pages = [path for path in source_docs.rglob("*.mdx") if path.is_file()]
    return len(pages)


def score_gate(passed: bool, partial: bool = False) -> str:
    if passed:
        return "pass"
    if partial:
        return "partial"
    return "missing"


def gate_score(status: str) -> int:
    if status == "pass":
        return 2
    if status == "partial":
        return 1
    return 0


def build_source_audit(root: Path, source: dict[str, Any]) -> dict[str, Any]:
    source_id = str(source["source_id"])
    processed_dir = root / "processed" / source_id
    source_dir = root / "sources" / source_id
    records = {key: count_records(processed_dir / filename) for key, filename in CATALOG_FILES.items()}
    raw_file_count = count_files(source_dir / "raw", "*")
    source_text_pages = max(0, count_files(root / "site" / "src" / "content" / "docs" / "source-texts" / source_id, "*.mdx") - 1)
    workbench_pages = max(0, count_files(root / "site" / "src" / "content" / "docs" / "chapter-workbench" / source_id, "*.mdx") - 1)
    curated_pages = count_curated_source_pages(root, source_id)
    original_crop_manifests = count_files(root / "diagrams" / "original" / source_id / "figures", "*.json")
    has_source_manifest = (source_dir / "source_manifest.json").exists()
    has_ocr_seed = (processed_dir / "cleaned_text" / "internet-archive-ocr.txt").exists()
    has_raw_or_archive = bool(source.get("local_raw_file") or source.get("internet_archive_id") or raw_file_count)

    gates = {
        "custody": score_gate(has_source_manifest and has_raw_or_archive, has_source_manifest or has_raw_or_archive),
        "structural_split": score_gate(records["chapters"] > 0),
        "public_source_text": score_gate(source_text_pages >= records["chapters"] and records["chapters"] > 0, source_text_pages > 0),
        "chapter_workbench": score_gate(workbench_pages >= records["chapters"] and records["chapters"] > 0, workbench_pages > 0),
        "concept_candidates": score_gate(records["concepts"] > 0),
        "equation_candidates": score_gate(records["equations"] > 0),
        "figure_candidates_or_crops": score_gate(records["figures"] > 0 or original_crop_manifests > 0),
        "glossary_candidates": score_gate(records["glossary"] > 0),
        "quote_candidates": score_gate(records["quotes"] > 0),
        "curated_public_pages": score_gate(curated_pages >= 2, curated_pages == 1),
        "original_scan_crops": score_gate(original_crop_manifests > 0),
    }
    max_score = len(gates) * 2
    total_score = sum(gate_score(status) for status in gates.values())
    readiness_percent = round((total_score / max_score) * 100, 1) if max_score else 0

    if readiness_percent >= 85:
        readiness = "strong-candidate-for-canonical-review"
    elif readiness_percent >= 65:
        readiness = "research-ready-needs-verification"
    elif readiness_percent >= 40:
        readiness = "foundation-started"
    else:
        readiness = "intake-only"

    next_actions: list[str] = []
    if gates["custody"] != "pass":
        next_actions.append("Complete source custody: raw file, public archive link, manifest, and checksum.")
    if gates["original_scan_crops"] != "pass" and records["figures"] > 0:
        next_actions.append("Promote at least one scan-derived figure crop with manifest and checksum.")
    if gates["curated_public_pages"] != "pass":
        next_actions.append("Add or deepen curated source pages beyond generated readers.")
    if gates["equation_candidates"] == "pass":
        next_actions.append("Triage equation candidates into canonical, false-positive, and needs-review groups.")
    if gates["glossary_candidates"] == "pass":
        next_actions.append("Promote high-value historical terms into glossary pages with exact source locations.")
    if not next_actions:
        next_actions.append("Begin expert canonical review: scan-check equations, figures, definitions, and hidden gems.")

    return {
        "source_id": source_id,
        "title": source.get("title"),
        "year": source.get("year"),
        "source_status": source.get("source_status"),
        "processed_status": source.get("processed_status"),
        "has_source_manifest": has_source_manifest,
        "has_ocr_seed": has_ocr_seed,
        "raw_file_count": raw_file_count,
        "record_counts": records,
        "source_text_pages": source_text_pages,
        "workbench_pages": workbench_pages,
        "curated_public_pages": curated_pages,
        "original_crop_manifests": original_crop_manifests,
        "gates": gates,
        "readiness_percent": readiness_percent,
        "readiness": readiness,
        "next_actions": next_actions,
        "links": {
            "source_page": f"{BASE_URL}{source.get('site_path', '')}",
            "source_text": f"{BASE_URL}/source-texts/{source_id}/",
            "workbench": f"{BASE_URL}/chapter-workbench/{source_id}/",
        },
    }


def build_project_gates(audits: list[dict[str, Any]], root: Path) -> dict[str, Any]:
    total_sources = len(audits)
    source_with_crops = sum(1 for audit in audits if audit["original_crop_manifests"] > 0)
    source_with_curated_pages = sum(1 for audit in audits if audit["curated_public_pages"] >= 2)
    pages = count_recursive_files(root / "site" / "src" / "content" / "docs", "*.mdx")
    concept_pages = count_recursive_files(root / "site" / "src" / "content" / "docs" / "concept-concordance", "*.mdx")
    source_text_pages = count_recursive_files(root / "site" / "src" / "content" / "docs" / "source-texts", "*.mdx")
    workbench_pages = count_recursive_files(root / "site" / "src" / "content" / "docs" / "chapter-workbench", "*.mdx")

    return {
        "site_pages_mdx": pages,
        "source_text_pages": source_text_pages,
        "chapter_workbench_pages": workbench_pages,
        "concept_concordance_pages": concept_pages,
        "sources_total": total_sources,
        "sources_with_original_crops": source_with_crops,
        "sources_with_curated_pages": source_with_curated_pages,
        "all_sources_have_text_and_workbench": all(
            audit["gates"]["public_source_text"] == "pass" and audit["gates"]["chapter_workbench"] == "pass"
            for audit in audits
        ),
        "all_sources_have_custody_or_archive": all(audit["gates"]["custody"] != "missing" for audit in audits),
        "definitive_archive_note": "The archive is broad and research-ready, but not definitive until source custody, scan verification, equations, diagrams, patents, and peer review gates pass for all priority sources.",
    }


def build_audit(root: Path) -> dict[str, Any]:
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    if not isinstance(source_catalog, list):
        source_catalog = []
    source_audits = [build_source_audit(root, source) for source in source_catalog]
    source_audits.sort(key=lambda item: (-item["readiness_percent"], str(item["source_id"])))
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Completion audit for project management. Scores are readiness indicators, not scholarly certification.",
        "source_audits": source_audits,
        "project_gates": build_project_gates(source_audits, root),
    }


def badge(status: str) -> str:
    labels = {
        "pass": "Pass",
        "partial": "Partial",
        "missing": "Missing",
    }
    return f"<span class=\"audit-badge audit-{html_escape(status)}\">{labels.get(status, status)}</span>"


def build_public_page(audit: dict[str, Any]) -> str:
    gates = audit["project_gates"]
    rows = []
    for item in audit["source_audits"]:
        rows.append(
            f"""<tr>
  <td><a href="{item['links']['source_page']}">{html_escape(item['title'])}</a><br /><code>{html_escape(item['source_id'])}</code></td>
  <td>{item['readiness_percent']}%<br /><code>{html_escape(item['readiness'])}</code></td>
  <td>{item['record_counts']['chapters']}</td>
  <td>{item['source_text_pages']} / {item['workbench_pages']}</td>
  <td>{item['record_counts']['equations']} / {item['record_counts']['figures']} / {item['record_counts']['glossary']}</td>
  <td>{item['original_crop_manifests']}</td>
  <td>{item['curated_public_pages']}</td>
</tr>"""
        )

    gate_rows = []
    for item in audit["source_audits"]:
        gate_rows.append(
            f"""<tr>
  <td>{html_escape(item['title'])}</td>
  <td>{badge(item['gates']['custody'])}</td>
  <td>{badge(item['gates']['structural_split'])}</td>
  <td>{badge(item['gates']['public_source_text'])}</td>
  <td>{badge(item['gates']['chapter_workbench'])}</td>
  <td>{badge(item['gates']['original_scan_crops'])}</td>
  <td>{badge(item['gates']['curated_public_pages'])}</td>
</tr>"""
        )

    action_items = []
    for item in audit["source_audits"]:
        action_items.append(
            f"<li><strong>{html_escape(item['title'])}:</strong> {html_escape(item['next_actions'][0])}</li>"
        )

    return f"""---
title: "Completion Audit"
description: "Generated readiness audit for the Steinmetz Decoded archive."
---

{GENERATED_NOTE}

## Completion Audit

This audit measures whether each seeded Steinmetz source has the infrastructure needed for final expert promotion: custody, structural split, public reader pages, chapter workbench coverage, candidate indexes, original figure crops, and curated source pages.

<div class="source-text-warning" data-layer="source">
  <strong>Important:</strong> this is a readiness audit, not a claim of scholarly completion. A source can be highly useful and still require scan verification before canonical status.
</div>

<div class="codex-signal">
  <div><strong>{gates['sources_total']} sources</strong><p>Seeded source records currently audited.</p></div>
  <div><strong>{gates['site_pages_mdx']} MDX pages</strong><p>Public content pages in the current source tree before build output.</p></div>
  <div><strong>{gates['sources_with_original_crops']} sources with crops</strong><p>Sources that already have original scan-derived figure manifests.</p></div>
</div>

## Source Readiness

<table class="codex-status-table">
  <thead>
    <tr>
      <th>Source</th>
      <th>Readiness</th>
      <th>Sections</th>
      <th>Text / Workbench</th>
      <th>Eq / Fig / Glossary</th>
      <th>Crops</th>
      <th>Curated Pages</th>
    </tr>
  </thead>
  <tbody>
{chr(10).join(rows)}
  </tbody>
</table>

## Gate Matrix

<table class="codex-status-table audit-table">
  <thead>
    <tr>
      <th>Source</th>
      <th>Custody</th>
      <th>Split</th>
      <th>Text</th>
      <th>Workbench</th>
      <th>Crops</th>
      <th>Curated</th>
    </tr>
  </thead>
  <tbody>
{chr(10).join(gate_rows)}
  </tbody>
</table>

## Next Source Actions

<ul>
{chr(10).join(action_items)}
</ul>

## Definitive-Archive Gate

The archive becomes definitive only when the readiness layer is followed by expert review:

- Priority sources have source custody, page maps, and checksums.
- Major equations are scan-verified, preserved in Steinmetz notation, and translated into modern notation.
- Major diagrams have original crops, modern redraws, and source-page references.
- Concept and glossary pages cite exact locations instead of relying on OCR occurrence counts.
- Tesla-era, ether-field, and other interpretive pages remain visibly separated from verified Steinmetz claims.
- Patents are authority-checked against official patent records and linked to drawings/PDFs where possible.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()
    audit = build_audit(root)
    write_json(root / "processed" / "completion_audit.json", audit)
    write_text(root / "site" / "src" / "content" / "docs" / "roadmap" / "completion-audit.mdx", build_public_page(audit))
    print(f"Generated completion audit for {len(audit['source_audits'])} sources.")


if __name__ == "__main__":
    main()
