#!/usr/bin/env python3
"""Generate publication-readiness control files and pages.

This script covers the remaining world-class apparatus that is not a source
parser: release levels, accessibility checks, edition comparison, and the
patent-to-theory bridge. These outputs are review aids, not declarations that
the archive is finished.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_publication_readiness.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("|", "\\|").replace("\n", " ")


def count_recursive(path: Path, pattern: str) -> int:
    if not path.exists():
        return 0
    return len([item for item in path.rglob(pattern) if item.is_file()])


def mdx_files(root: Path) -> list[Path]:
    docs = root / "site" / "src" / "content" / "docs"
    if not docs.exists():
        return []
    return sorted(path for path in docs.rglob("*.mdx") if path.is_file())


def build_accessibility_audit(root: Path) -> dict[str, Any]:
    pages = mdx_files(root)
    image_tag_count = 0
    image_tag_missing_alt = 0
    markdown_image_count = 0
    markdown_image_missing_alt = 0
    iframe_count = 0
    html_table_count = 0
    long_table_pages = []
    issue_pages = []

    for path in pages:
        text = path.read_text(encoding="utf-8")
        image_tags = re.findall(r"<img\b[^>]*>", text, flags=re.IGNORECASE)
        md_images = re.findall(r"!\[([^\]]*)\]\(", text)
        missing_html = [tag for tag in image_tags if not re.search(r"\balt\s*=", tag, flags=re.IGNORECASE)]
        missing_md = [alt for alt in md_images if not alt.strip()]
        tables = len(re.findall(r"<table\b", text, flags=re.IGNORECASE))

        image_tag_count += len(image_tags)
        image_tag_missing_alt += len(missing_html)
        markdown_image_count += len(md_images)
        markdown_image_missing_alt += len(missing_md)
        iframe_count += len(re.findall(r"<iframe\b", text, flags=re.IGNORECASE))
        html_table_count += tables
        if tables >= 3:
            long_table_pages.append(path.relative_to(root).as_posix())
        if missing_html or missing_md:
            issue_pages.append(
                {
                    "path": path.relative_to(root).as_posix(),
                    "missing_html_alt": len(missing_html),
                    "missing_markdown_alt": len(missing_md),
                }
            )

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Automated accessibility scan. It catches structural risks, but contrast, keyboard flow, mobile fit, and screen-reader behavior still need manual review.",
        "page_count": len(pages),
        "image_tag_count": image_tag_count,
        "image_tag_missing_alt": image_tag_missing_alt,
        "markdown_image_count": markdown_image_count,
        "markdown_image_missing_alt": markdown_image_missing_alt,
        "iframe_count": iframe_count,
        "html_table_count": html_table_count,
        "long_table_pages": long_table_pages[:50],
        "issue_pages": issue_pages,
        "gates": {
            "image_alt_text": "pass" if image_tag_missing_alt == 0 and markdown_image_missing_alt == 0 else "needs-review",
            "table_overflow": "needs-manual-mobile-review" if html_table_count else "pass",
            "color_contrast": "needs-manual-contrast-review",
            "keyboard_navigation": "needs-manual-keyboard-review",
            "math_readability": "needs-manual-katex-review",
        },
    }


def build_release_readiness(root: Path) -> dict[str, Any]:
    completion = load_json(root / "processed" / "completion_audit.json", {})
    project = completion.get("project_gates", {})
    equations = load_json(root / "processed" / "canonical_equations.json", {})
    diagrams = load_json(root / "processed" / "diagram_provenance_ledger.json", {})
    patents = load_json(root / "sources" / "steinmetz_patents" / "patent_register.json", {}).get("patents", [])
    data_manifest_exists = (root / "site" / "public" / "data" / "manifest.json").exists()

    levels = [
        {
            "id": "foundation-release",
            "title": "Foundation Release",
            "status": "pass" if project.get("site_pages_mdx", 0) > 100 and data_manifest_exists else "partial",
            "definition": "Public site, source corpus, generated readers, project tracker, and deployment workflow exist.",
        },
        {
            "id": "source-coverage-release",
            "title": "Source Coverage Release",
            "status": "pass" if project.get("all_sources_have_text_and_workbench") else "partial",
            "definition": "Every seeded source has public source-text and chapter-workbench coverage.",
        },
        {
            "id": "scan-verification-release",
            "title": "Scan Verification Release",
            "status": "partial" if project.get("sources_with_original_crops", 0) > 0 else "missing",
            "definition": "Priority source claims, equations, and diagrams are checked against scans.",
        },
        {
            "id": "equation-canon-release",
            "title": "Equation Canon Release",
            "status": "partial" if equations.get("total_records", 0) >= 12 else "missing",
            "definition": "Canonical equations have scan verification, notation ledger entries, derivations, and worked examples.",
        },
        {
            "id": "diagram-canon-release",
            "title": "Diagram Canon Release",
            "status": "partial" if diagrams.get("original_crop_count", 0) > 0 else "missing",
            "definition": "Major diagrams have original crops, provenance, captions, redraws, and linked explanations.",
        },
        {
            "id": "patent-authority-release",
            "title": "Patent Authority Release",
            "status": "started" if patents else "missing",
            "definition": "Steinmetz patents are authority-checked, downloaded, drawn, summarized, and linked to theory.",
        },
        {
            "id": "definitive-steinmetz-release",
            "title": "Definitive Steinmetz Release",
            "status": "future",
            "definition": "All priority books, papers, diagrams, equations, glossary terms, patents, and comparisons pass canonical review.",
        },
    ]
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Release levels are project-management gates, not scholarly certification by themselves.",
        "levels": levels,
    }


def build_edition_comparison(root: Path) -> dict[str, Any]:
    sources = load_json(root / "sources" / "source_catalog.json", [])
    records = []
    for source in sources if isinstance(sources, list) else []:
        processed_status = str(source.get("processed_status", ""))
        priority = "high" if "edition" in processed_status.lower() or "Alternating Current" in str(source.get("title")) else "normal"
        records.append(
            {
                "source_id": source.get("source_id"),
                "title": source.get("title"),
                "year": source.get("year"),
                "internet_archive_id": source.get("internet_archive_id"),
                "local_raw_file": source.get("local_raw_file"),
                "processed_status": processed_status,
                "edition_review_status": "needs edition comparison",
                "priority": priority,
                "review_actions": [
                    "Record exact edition, publisher, and title-page wording.",
                    "Compare chapter numbering and figure numbering against other editions.",
                    "Record equation or terminology differences before merging commentary.",
                ],
            }
        )
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Edition comparison index. It marks edition work to do; it does not claim editions have been collated.",
        "record_count": len(records),
        "records": records,
    }


def build_patent_theory_bridge(root: Path) -> dict[str, Any]:
    register = load_json(root / "sources" / "steinmetz_patents" / "patent_register.json", {})
    patents = register.get("patents", []) if isinstance(register, dict) else []
    concept_to_patents: dict[str, list[str]] = defaultdict(list)
    records = []
    for patent in patents if isinstance(patents, list) else []:
        number = patent.get("patent_number")
        for concept in patent.get("concept_links", []):
            concept_to_patents[str(concept)].append(number)
        records.append(
            {
                "patent_number": number,
                "title": patent.get("title"),
                "publication_date": patent.get("publication_date"),
                "patent_url": patent.get("patent_url"),
                "pdf_url": patent.get("pdf_url"),
                "domain_tags": patent.get("domain_tags", []),
                "concept_links": patent.get("concept_links", []),
                "diagram_targets": patent.get("diagram_targets", []),
                "research_status": patent.get("research_status"),
                "bridge_status": "seeded theory bridge; needs PDF, drawing, claim, and source-text verification",
            }
        )
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Patent-to-theory bridge. Patent records are seeded and must not be treated as complete until authority PDFs, drawings, and claims are checked.",
        "record_count": len(records),
        "scope_warning": register.get("scope_warning") if isinstance(register, dict) else None,
        "concept_to_patents": dict(sorted(concept_to_patents.items())),
        "records": records,
    }


def build_accessibility_page(audit: dict[str, Any]) -> str:
    issue_rows = []
    for item in audit["issue_pages"][:25]:
        issue_rows.append(f"| `{md_escape(item['path'])}` | {item['missing_html_alt']} | {item['missing_markdown_alt']} |")
    if not issue_rows:
        issue_rows.append("| No missing alt text detected by the structural scan. | 0 | 0 |")
    gate_rows = [f"| `{md_escape(key)}` | `{md_escape(value)}` |" for key, value in audit["gates"].items()]
    return f"""---
title: Accessibility Audit
description: Automated and manual accessibility-readiness controls for Steinmetz Decoded.
---

{GENERATED_NOTE}

## Accessibility Audit

The archive should be readable for serious long sessions. This automated pass checks structural risks; contrast, keyboard behavior, mobile layout, table overflow, and math readability still require human review.

<div class="codex-signal">
  <div><strong>{audit['page_count']} pages</strong><p>MDX pages scanned.</p></div>
  <div><strong>{audit['image_tag_missing_alt'] + audit['markdown_image_missing_alt']} missing alt</strong><p>Image-alt issues found by regex scan.</p></div>
  <div><strong>{audit['html_table_count']} tables</strong><p>Tables needing mobile overflow review.</p></div>
</div>

## Gates

| Gate | Status |
| --- | --- |
{chr(10).join(gate_rows)}

## Image Alt Findings

| Page | Missing HTML Alt | Missing Markdown Alt |
| --- | ---: | ---: |
{chr(10).join(issue_rows)}

## Manual Review Still Required

- Check light/dark contrast on pages with callouts, cards, and tables.
- Keyboard-test search, sidebar navigation, theme controls, filters, lightbox, and reader tools.
- Inspect KaTeX blocks and wide tables on mobile viewports.
- Confirm source-only filtering does not hide essential navigation or citation context.
"""


def build_release_page(readiness: dict[str, Any]) -> str:
    rows = [f"| `{md_escape(level['id'])}` | {md_escape(level['title'])} | `{md_escape(level['status'])}` | {md_escape(level['definition'])} |" for level in readiness["levels"]]
    return f"""---
title: Release Levels
description: Named release levels for the Steinmetz Decoded archive.
---

{GENERATED_NOTE}

## Release Levels

The archive should not jump from \"prototype\" to \"definitive\" in one vague step. Named release levels let readers know exactly what has been achieved and what remains under review.

| Release | Title | Status | Definition |
| --- | --- | --- | --- |
{chr(10).join(rows)}

## Release Rule

A release level can be public before it is complete. It must not be described as complete until its verification gates are met.
"""


def build_edition_page(index: dict[str, Any]) -> str:
    rows = []
    for record in index["records"]:
        rows.append(
            f"| `{md_escape(record['source_id'])}` | {md_escape(record['title'])} | {md_escape(record['year'])} | `{md_escape(record['priority'])}` | `{md_escape(record['edition_review_status'])}` |"
        )
    return f"""---
title: Edition Comparison Layer
description: Edition collation queue for Steinmetz sources.
---

{GENERATED_NOTE}

## Edition Comparison Layer

Steinmetz books often circulated through multiple editions. A serious archive must not silently merge editions when page numbers, figures, terminology, or equations may have changed.

| Source | Title | Year | Priority | Status |
| --- | --- | ---: | --- | --- |
{chr(10).join(rows)}

## Collation Rule

Record edition, publisher, title-page wording, chapter numbering, figure numbering, equation differences, and terminology changes before a later edition is allowed to stand in for an earlier one.
"""


def build_patent_page(bridge: dict[str, Any]) -> str:
    rows = []
    for record in bridge["records"]:
        concepts = ", ".join(record.get("concept_links", [])[:5])
        rows.append(
            f"| `{md_escape(record['patent_number'])}` | {md_escape(record['title'])} | {md_escape(concepts)} | [patent]({record.get('patent_url')}) | `{md_escape(record['bridge_status'])}` |"
        )
    return f"""---
title: Patent To Theory Bridge
description: Seeded bridge from Steinmetz patent records to concepts, diagrams, and source-theory review.
---

{GENERATED_NOTE}

## Patent To Theory Bridge

Patents are not textbooks. They are legal and apparatus documents. This bridge keeps them useful while preventing overinterpretation: a patent may suggest a theory connection, but the connection only becomes canonical after source-text and claim review.

<div class="source-text-warning" data-layer="source">
  <strong>Scope warning:</strong> {md_escape(bridge.get('scope_warning'))}
</div>

| Patent | Title | Concept Links | Authority Link | Status |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Bridge Rule

Every patent dossier should eventually include downloaded PDF custody, checksum, drawings, claim excerpts, apparatus explanation, concept links, and a clear boundary between patent language and Steinmetz's theoretical writings.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()

    accessibility = build_accessibility_audit(root)
    release = build_release_readiness(root)
    edition = build_edition_comparison(root)
    patent_bridge = build_patent_theory_bridge(root)

    write_json(root / "processed" / "accessibility_audit.json", accessibility)
    write_json(root / "processed" / "release_readiness.json", release)
    write_json(root / "processed" / "edition_comparison_index.json", edition)
    write_json(root / "processed" / "patent_theory_bridge.json", patent_bridge)

    docs = root / "site" / "src" / "content" / "docs" / "roadmap"
    write_text(docs / "accessibility-audit.mdx", build_accessibility_page(accessibility))
    write_text(docs / "release-levels.mdx", build_release_page(release))
    write_text(docs / "edition-comparison-layer.mdx", build_edition_page(edition))
    write_text(docs / "patent-to-theory-bridge.mdx", build_patent_page(patent_bridge))

    print(
        "Generated publication readiness artifacts: "
        f"{accessibility['page_count']} pages scanned, "
        f"{len(release['levels'])} release levels, "
        f"{edition['record_count']} edition records, "
        f"{patent_bridge['record_count']} patent bridge records."
    )


if __name__ == "__main__":
    main()
