#!/usr/bin/env python3
"""Generate book-level coverage atlas pages from chapter workbench records.

The source-text browser and chapter workbench are intentionally granular. This
script adds the missing book-level view: for each source, it summarizes every
processed section and exposes the direct path into source text, research
workbench, concepts, candidate equations, figures, and quotes.
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import quote


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_book_coverage_atlas.py. Do not edit by hand. */}"

THEME_LABELS = {
    "alternating-current": "Alternating current",
    "complex-quantities": "Complex quantities",
    "dielectricity": "Dielectricity / capacity",
    "ether": "Ether references",
    "fields": "Field language",
    "hysteresis": "Hysteresis",
    "impedance-reactance": "Impedance / reactance",
    "lightning-surges": "Lightning / surges",
    "magnetism": "Magnetism",
    "radiation-light": "Radiation / light",
    "transients": "Transients / damping",
    "waves-lines": "Waves / transmission lines",
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("$", "&#36;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def site_link(path: str | None) -> str:
    if not path:
        return ""
    if path.startswith("http"):
        return path
    if BASE_URL and path.startswith(BASE_URL):
        return path
    if path.startswith("/"):
        return f"{BASE_URL}{path}"
    return f"{BASE_URL}/{path}"


def slugify(value: Any) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def chip_href(item: dict[str, Any], kind: str) -> str:
    slug = slugify(item.get("id") or item.get("label"))
    if not slug:
        return ""
    if kind == "theme":
        return f"{BASE_URL}/theme-evidence/#{slug}"
    if kind == "concept":
        return f"{BASE_URL}/concept-concordance/{slug}/"
    if kind == "glossary":
        return f"{BASE_URL}/glossary/#{slug}"
    return ""


def focused_reader_url(url: str | None, term: str | None = None) -> str:
    if not url:
        return ""
    if not term:
        return url
    separator = "&" if "?" in url else "?"
    return f"{url}{separator}q={quote(term)}#source-text-reader"


def archive_url(source: dict[str, Any]) -> str:
    archive_id = source.get("internet_archive_id")
    if archive_id:
        return f"https://archive.org/details/{archive_id}"
    local_raw = source.get("local_raw_file")
    if local_raw:
        return f"https://github.com/TRUEMODELOFTHEWORLD/Steinmetz-Decoded/blob/main/{local_raw}"
    return site_link(source.get("site_path"))


def label_for(record: dict[str, Any]) -> str:
    return str(record.get("label") or record.get("title") or record.get("id") or "Untitled section")


def theme_label(theme: str) -> str:
    return THEME_LABELS.get(theme, theme.replace("-", " ").title())


def format_number(value: int) -> str:
    return f"{value:,}"


def sum_counter(counter: Counter[str], limit: int = 8) -> list[dict[str, Any]]:
    return [
        {
            "id": key,
            "label": theme_label(key),
            "count": count,
        }
        for key, count in counter.most_common(limit)
    ]


def aggregate_records(source: dict[str, Any], records: list[dict[str, Any]]) -> dict[str, Any]:
    theme_counter: Counter[str] = Counter()
    concept_counter: Counter[str] = Counter()
    glossary_counter: Counter[str] = Counter()
    concept_labels: dict[str, str] = {}
    glossary_labels: dict[str, str] = {}

    word_total = 0
    equation_total = 0
    figure_total = 0
    quote_total = 0
    section_rows: list[dict[str, Any]] = []

    for record in records:
        word_count = int(record.get("word_count") or 0)
        word_total += word_count
        equation_count = len(record.get("equations") or [])
        figure_count = len(record.get("figures") or [])
        quote_count = len(record.get("quotes") or [])
        equation_total += equation_count
        figure_total += figure_count
        quote_total += quote_count

        for theme, count in (record.get("theme_counts") or {}).items():
            theme_counter[str(theme)] += int(count or 0)
        for hit in record.get("concept_hits") or []:
            concept_id = str(hit.get("id") or hit.get("label") or "")
            if not concept_id:
                continue
            concept_counter[concept_id] += int(hit.get("count") or 0)
            concept_labels[concept_id] = str(hit.get("label") or concept_id)
        for hit in record.get("glossary_hits") or []:
            term_id = str(hit.get("id") or hit.get("term") or hit.get("label") or "")
            if not term_id:
                continue
            glossary_counter[term_id] += int(hit.get("count") or 0)
            glossary_labels[term_id] = str(hit.get("label") or hit.get("term") or term_id)

        links = record.get("links") or {}
        section_rows.append(
            {
                "id": record.get("id"),
                "label": label_for(record),
                "slug": record.get("slug"),
                "location": record.get("location"),
                "status": record.get("status"),
                "word_count": word_count,
                "top_themes": [theme_label(str(theme)) for theme in (record.get("top_themes") or [])[:4]],
                "top_concepts": [
                    {
                        "id": hit.get("id"),
                        "label": hit.get("label"),
                        "count": hit.get("count"),
                    }
                    for hit in (record.get("concept_hits") or [])[:5]
                ],
                "equation_count": equation_count,
                "figure_count": figure_count,
                "quote_count": quote_count,
                "links": {
                    "source_text": site_link(links.get("source_text") or f"/source-texts/{source['source_id']}/{record.get('slug')}/"),
                    "workbench": site_link(f"/chapter-workbench/{source['source_id']}/{record.get('slug')}/"),
                    "asset": links.get("asset"),
                    "github_text": links.get("github_text"),
                },
            }
        )

    top_concepts = [
        {"id": key, "label": concept_labels.get(key, key), "count": count}
        for key, count in concept_counter.most_common(12)
    ]
    top_glossary = [
        {"id": key, "label": glossary_labels.get(key, key), "count": count}
        for key, count in glossary_counter.most_common(12)
    ]

    priority_sections = sorted(
        section_rows,
        key=lambda item: (
            item["equation_count"] * 120
            + item["figure_count"] * 90
            + item["quote_count"] * 70
            + len(item["top_concepts"]) * 45
            + item["word_count"] // 80
        ),
        reverse=True,
    )[:14]

    result = {
        "source_id": source["source_id"],
        "title": source.get("title"),
        "year": source.get("year"),
        "source_status": source.get("source_status"),
        "processed_status": source.get("processed_status"),
        "internet_archive_id": source.get("internet_archive_id"),
        "local_raw_file": source.get("local_raw_file"),
        "site_path": source.get("site_path"),
        "links": {
            "coverage": f"{BASE_URL}/book-coverage/{source['source_id']}/",
            "curated_source": site_link(source.get("site_path")),
            "source_text_index": f"{BASE_URL}/source-texts/{source['source_id']}/",
            "chapter_workbench_index": f"{BASE_URL}/chapter-workbench/{source['source_id']}/",
            "archive": archive_url(source),
        },
        "section_count": len(section_rows),
        "word_total": word_total,
        "equation_candidate_count": equation_total,
        "figure_candidate_count": figure_total,
        "quote_candidate_count": quote_total,
        "theme_totals": sum_counter(theme_counter, 12),
        "top_concepts": top_concepts,
        "top_glossary": top_glossary,
        "priority_sections": priority_sections,
        "sections": section_rows,
    }
    result["study_guide"] = build_study_guide(result)
    return result


def compact_section_ref(section: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": section.get("id"),
        "label": section.get("label"),
        "slug": section.get("slug"),
        "word_count": section.get("word_count"),
        "top_themes": (section.get("top_themes") or [])[:4],
        "top_concepts": (section.get("top_concepts") or [])[:4],
        "equation_count": section.get("equation_count", 0),
        "figure_count": section.get("figure_count", 0),
        "quote_count": section.get("quote_count", 0),
        "links": section.get("links") or {},
    }


def section_signal_score(section: dict[str, Any]) -> int:
    return (
        int(section.get("equation_count") or 0) * 80
        + int(section.get("figure_count") or 0) * 70
        + int(section.get("quote_count") or 0) * 65
        + len(section.get("top_concepts") or []) * 35
        + int(section.get("word_count") or 0) // 150
    )


def top_sections_by(source: dict[str, Any], key: str, limit: int = 4) -> list[dict[str, Any]]:
    sections = [
        section for section in source.get("sections", []) if int(section.get(key) or 0) > 0
    ]
    sections.sort(
        key=lambda section: (
            -int(section.get(key) or 0),
            -section_signal_score(section),
            str(section.get("label") or ""),
        )
    )
    return [compact_section_ref(section) for section in sections[:limit]]


def theme_sections(source: dict[str, Any], terms: list[str], limit: int = 4) -> list[dict[str, Any]]:
    wanted = [term.lower() for term in terms]
    sections: list[dict[str, Any]] = []
    for section in source.get("sections", []):
        haystack = " ".join(section.get("top_themes") or [])
        haystack += " " + " ".join(hit.get("label", "") for hit in section.get("top_concepts", []))
        haystack = haystack.lower()
        if any(term in haystack for term in wanted):
            sections.append(section)
    sections.sort(key=lambda section: (-section_signal_score(section), str(section.get("label") or "")))
    return [compact_section_ref(section) for section in sections[:limit]]


def build_study_guide(source: dict[str, Any]) -> dict[str, Any]:
    first_read = [compact_section_ref(section) for section in (source.get("priority_sections") or [])[:5]]
    math_sections = top_sections_by(source, "equation_count", 5)
    visual_sections = top_sections_by(source, "figure_count", 5)
    field_language_sections = theme_sections(
        source,
        ["field", "ether", "dielectric", "capacity", "magnetism", "hysteresis", "force"],
        5,
    )
    glossary_sections = theme_sections(
        source,
        ["reactance", "impedance", "admittance", "conductance", "susceptance", "capacity", "counter"],
        5,
    )
    return {
        "quality_note": "Generated from section-level candidate metadata. Use as a reading guide, not as scan verification.",
        "first_read": first_read,
        "mathematics": math_sections,
        "visuals": visual_sections,
        "field_language": field_language_sections,
        "terminology": glossary_sections,
    }


def stat_card(label: str, value: Any, note: str) -> str:
    return (
        '<div>'
        f"<strong>{html_escape(value)}</strong>"
        f"<p>{html_escape(label)}</p>"
        f"<span>{html_escape(note)}</span>"
        "</div>"
    )


def write_index_page(root: Path, atlas: dict[str, Any]) -> None:
    sources = atlas["sources"]
    total_words = sum(int(source.get("word_total") or 0) for source in sources)
    total_equations = sum(int(source.get("equation_candidate_count") or 0) for source in sources)
    total_figures = sum(int(source.get("figure_candidate_count") or 0) for source in sources)
    total_quotes = sum(int(source.get("quote_candidate_count") or 0) for source in sources)

    cards = "\n".join(
        [
            stat_card("processed sections", atlas["total_sections"], "lectures, chapters, sections, and report divisions"),
            stat_card("processed words", format_number(total_words), "candidate text available through source readers"),
            stat_card("equation candidates", format_number(total_equations), "source-linked candidates awaiting scan verification"),
            stat_card("figure candidates", format_number(total_figures), "figure references plus promoted original crops"),
            stat_card("quote candidates", format_number(total_quotes), "hidden-gem seeds and notable passages"),
        ]
    )

    source_cards = "\n".join(
        [
            (
                f'<a href="{html_escape(source["links"]["coverage"])}">'
                f'{html_escape(source["title"])}'
                f"<span>{html_escape(source.get('year') or 'n.d.')} - {source['section_count']} sections - "
                f"{format_number(int(source.get('word_total') or 0))} words - "
                f"{format_number(int(source.get('equation_candidate_count') or 0))} equation candidates</span>"
                "</a>"
            )
            for source in sources
        ]
    )

    rows = "\n".join(
        [
            (
                "<tr>"
                f'<td><a href="{html_escape(source["links"]["coverage"])}">{html_escape(source["title"])}</a></td>'
                f"<td>{html_escape(source.get('year') or 'n.d.')}</td>"
                f"<td>{source['section_count']}</td>"
                f"<td>{format_number(int(source.get('word_total') or 0))}</td>"
                f"<td>{format_number(int(source.get('equation_candidate_count') or 0))}</td>"
                f"<td>{format_number(int(source.get('figure_candidate_count') or 0))}</td>"
                f"<td>{format_number(int(source.get('quote_candidate_count') or 0))}</td>"
                f"<td>{html_escape(', '.join(item['label'] for item in source.get('theme_totals', [])[:3]) or 'pending')}</td>"
                "</tr>"
            )
            for source in sources
        ]
    )

    text = f"""---
title: Book Coverage Atlas
description: Book-level coverage map for every processed Steinmetz source.
---

{GENERATED_NOTE}

Choose a source by reading purpose first: direct text, guided route, concept trail, diagrams, or mathematics. The research metadata remains available for serious verification work, but the public doorway is designed around reading Steinmetz rather than staring at pipeline counters.

<div class="coverage-hero">
  <div>
    <p class="home-kicker">Corpus coverage</p>
    <h1>Every Processed Book, Opened Up</h1>
    <p>The archive currently exposes {atlas["total_sections"]} processed Steinmetz sections across {atlas["source_count"]} seeded sources. Use this atlas when the site feels too broad: it shows what exists, where it lives, and what still needs review.</p>
  </div>
  <div class="coverage-stat-grid">
{cards}
  </div>
</div>

## Choose A Reading Door

<div class="source-matrix">
  <a href="{BASE_URL}/reading-routes/">Choose a guided route<span>Enter by purpose: first hour, source-only, AC math, transients, field language, diagrams, apparatus, or patents.</span></a>
  <a href="{BASE_URL}/book-coverage/radiation-light-and-illumination/">Start with radiation and light<span>A readable first source: radiation, electric waves, spectrum, light, illumination, and original visual crops.</span></a>
  <a href="{BASE_URL}/book-coverage/theory-calculation-alternating-current-phenomena/">Enter the AC mathematics<span>Symbolic method, complex quantities, impedance, reactance, admittance, harmonics, and transformers.</span></a>
  <a href="{BASE_URL}/book-coverage/theory-calculation-transient-electric-phenomena-oscillations/">Follow transients and surges<span>Temporary terms, oscillations, distributed lines, standing waves, traveling waves, and lightning-related behavior.</span></a>
  <a href="{BASE_URL}/concept-concordance/">Trace a concept instead<span>Search across sources by terms such as ether, hysteresis, impedance, dielectricity, waves, and transients.</span></a>
</div>

## Source Maps

<div class="source-matrix">
{source_cards}
</div>

## Complete Corpus Table

<table class="codex-status-table coverage-table">
  <thead>
    <tr>
      <th>Source</th>
      <th>Year</th>
      <th>Sections</th>
      <th>Words</th>
      <th>Equations</th>
      <th>Figures</th>
      <th>Quotes</th>
      <th>Top Themes</th>
    </tr>
  </thead>
  <tbody>
{rows}
  </tbody>
</table>

## How To Use This Layer

<div class="research-passages">
  <section data-layer="source">
    <h3>Read the source first</h3>
    <p>Open a book coverage page, choose a section, then use the source-text link to read the candidate text before using any commentary.</p>
  </section>
  <section data-layer="modern">
    <h3>Use the workbench second</h3>
    <p>The workbench joins concepts, glossary terms, equations, figures, quotes, themes, and source links for the same section.</p>
  </section>
  <section data-layer="interpretive">
    <h3>Promote carefully</h3>
    <p>Interpretive and modern layers should be added only after the exact source location is checked against the scan or source PDF.</p>
  </section>
</div>
"""
    write_text(root / "site" / "src" / "content" / "docs" / "book-coverage" / "index.mdx", text)


def section_table_rows(source: dict[str, Any]) -> str:
    rows: list[str] = []
    for section in source["sections"]:
        concepts = ", ".join(
            f"{hit.get('label')} ({hit.get('count')})" for hit in section.get("top_concepts", [])[:4]
        )
        themes = ", ".join(section.get("top_themes") or [])
        rows.append(
            "<tr>"
            f'<td><a href="{html_escape(section["links"]["source_text"])}">{html_escape(section["label"])}</a>'
            f'<br /><a class="coverage-small-link" href="{html_escape(section["links"]["workbench"])}">research review</a></td>'
            f"<td>{format_number(int(section.get('word_count') or 0))}</td>"
            f"<td>{html_escape(themes or 'pending')}</td>"
            f"<td>{html_escape(concepts or 'pending')}</td>"
            f"<td>{section.get('equation_count', 0)}</td>"
            f"<td>{section.get('figure_count', 0)}</td>"
            f"<td>{section.get('quote_count', 0)}</td>"
            f"<td>{html_escape(section.get('location') or 'processed text')}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def priority_table_rows(source: dict[str, Any]) -> str:
    rows: list[str] = []
    for section in source["priority_sections"]:
        reasons = []
        if section.get("equation_count"):
            reasons.append(f"{section['equation_count']} equation candidates")
        if section.get("figure_count"):
            reasons.append(f"{section['figure_count']} figure candidates")
        if section.get("quote_count"):
            reasons.append(f"{section['quote_count']} quote candidates")
        if section.get("top_concepts"):
            reasons.append("dense concept hits")
        rows.append(
            "<tr>"
            f'<td><a href="{html_escape(section["links"]["source_text"])}">{html_escape(section["label"])}</a></td>'
            f"<td>{html_escape(', '.join(section.get('top_themes') or []) or 'pending')}</td>"
            f"<td>{html_escape('; '.join(reasons) or 'substantial source section')}</td>"
            f'<td><a href="{html_escape(section["links"]["workbench"])}">Research review</a></td>'
            "</tr>"
        )
    return "\n".join(rows)


def pill_list(items: list[dict[str, Any]], empty: str = "Pending", kind: str = "") -> str:
    if not items:
        return f"<span>{html_escape(empty)}</span>"
    chips = []
    for item in items:
        label = html_escape(item.get("label") or item.get("id"))
        count = html_escape(item.get("count"))
        href = chip_href(item, kind)
        if href:
            chips.append(f'<a href="{html_escape(href)}">{label} <b>{count}</b></a>')
        else:
            chips.append(f"<span>{label} <b>{count}</b></span>")
    return "\n".join(chips)


def study_link_list(sections: list[dict[str, Any]], empty: str) -> str:
    if not sections:
        return f"<p>{html_escape(empty)}</p>"
    items = []
    for section in sections:
        theme_values = section.get("top_themes") or []
        themes = ", ".join(theme_values)
        counts = []
        if section.get("equation_count"):
            counts.append(f"{section['equation_count']} eq.")
        if section.get("figure_count"):
            counts.append(f"{section['figure_count']} fig.")
        if section.get("quote_count"):
            counts.append(f"{section['quote_count']} quote")
        meta = "; ".join(counts) or f"{format_number(int(section.get('word_count') or 0))} words"
        links = section.get("links") or {}
        focus_term = (theme_values[0] if theme_values else section.get("label") or "")
        source_link = focused_reader_url(links.get("source_text"), focus_term)
        items.append(
            "<li>"
            f'<a href="{html_escape(source_link)}">{html_escape(section.get("label"))}</a>'
            f'<span>{html_escape(themes or "general section")} - {html_escape(meta)} - '
            f'<a href="{html_escape(links.get("workbench"))}">research review</a></span>'
            "</li>"
        )
    return f"<ul class=\"study-link-list\">\n{''.join(items)}\n</ul>"


def study_panel(title: str, body: str, sections: list[dict[str, Any]], empty: str, layer: str = "source") -> str:
    return f"""  <section data-layer="{html_escape(layer)}">
    <h3>{html_escape(title)}</h3>
    <p>{html_escape(body)}</p>
    {study_link_list(sections, empty)}
  </section>"""


def source_study_guide(source: dict[str, Any]) -> str:
    guide = source.get("study_guide") or {}
    panels = [
        study_panel(
            "Best First Reads",
            "Start here when you want the strongest section-level doorway into this source.",
            guide.get("first_read") or [],
            "No priority sections have been generated yet.",
            "source",
        ),
        study_panel(
            "Mathematics To Inspect",
            "Use these sections to promote equations, notation, derivations, and worked examples.",
            guide.get("mathematics") or [],
            "No equation-dense sections have been detected yet.",
            "modern",
        ),
        study_panel(
            "Visual Material To Crop Or Annotate",
            "Use these sections to locate figure references, scan crops, diagrams, and redraw targets.",
            guide.get("visuals") or [],
            "No figure-dense sections have been detected yet.",
            "source",
        ),
        study_panel(
            "Field And Language Trail",
            "Use these sections for field, ether, dielectric, magnetic, force, and terminology review.",
            guide.get("field_language") or [],
            "No field-language-heavy sections have been detected yet.",
            "interpretive",
        ),
    ]
    return "\n".join(panels)


def write_source_page(root: Path, source: dict[str, Any]) -> None:
    cards = "\n".join(
        [
            stat_card("processed sections", source["section_count"], "all linked to source text and research review"),
            stat_card("processed words", format_number(int(source.get("word_total") or 0)), "candidate reader text"),
            stat_card("equation candidates", format_number(int(source.get("equation_candidate_count") or 0)), "OCR/PDF-derived review seeds"),
            stat_card("figure candidates", format_number(int(source.get("figure_candidate_count") or 0)), "figure references and crops"),
            stat_card("quote candidates", format_number(int(source.get("quote_candidate_count") or 0)), "hidden-gem candidates"),
        ]
    )
    themes = pill_list(source.get("theme_totals") or [], "No theme hits yet", "theme")
    concepts = pill_list(source.get("top_concepts") or [], "No concept hits yet", "concept")
    glossary = pill_list(source.get("top_glossary") or [], "No glossary hits yet", "glossary")
    first_section = (
        source["priority_sections"][0]
        if source.get("priority_sections")
        else source["sections"][0]
        if source.get("sections")
        else {
            "label": "Source text index",
            "links": {"source_text": source["links"]["source_text_index"]},
        }
    )
    formula_map = f"{BASE_URL}/mathematics/source-formula-maps/{source['source_id']}/"

    text = f"""---
title: {yaml_quote(str(source["title"]) + " Reader Guide")}
description: {yaml_quote("Reader-first guide, source text links, and research metadata for " + str(source["title"]))}
---

{GENERATED_NOTE}

<div class="source-access source-reader-hero">
  <div>
    <strong>{html_escape(source["title"])}</strong>
    <p>Year: {html_escape(source.get("year") or "n.d.")}. Start with the source text, then branch into diagrams, formulas, and verification material only when you need them.</p>
  </div>
  <div class="source-access-actions">
    <a href="{html_escape(source["links"]["source_text_index"])}">Read source text</a>
    <a href="{html_escape(first_section["links"]["source_text"])}">Start with strongest section</a>
    <a href="{BASE_URL}/diagrams/source-visuals/">View source visuals</a>
    <a href="{html_escape(formula_map)}">View formula map</a>
    <a href="{html_escape(source["links"]["archive"])}">Original source</a>
  </div>
</div>

## Start Reading

<div class="source-matrix reader-route-grid">
  <a href="{html_escape(source["links"]["source_text_index"])}">Read the source text<span>Open the book's processed source-text reader and move section by section.</span></a>
  <a href="{html_escape(first_section["links"]["source_text"])}">Begin with: {html_escape(first_section["label"])}<span>A high-signal section chosen from concept, equation, figure, and quote density.</span></a>
  <a href="{html_escape(source["links"]["curated_source"])}">Use the curated guide<span>Read the human-facing overview before entering the research workbench.</span></a>
  <a href="{BASE_URL}/reading-routes/">Find a guided route<span>Enter by purpose: source-only reading, AC math, transients, field language, diagrams, apparatus, or patents.</span></a>
</div>

## Best Doorways Into This Source

<div class="research-passages source-study-guide">
{source_study_guide(source)}
</div>

<details class="research-metadata">
  <summary>Research metadata and full section map</summary>
  <p>This layer preserves the rigorous candidate data behind the public reader. Counts and tags are routing aids for researchers, not final scan verification and not the recommended first path for casual reading.</p>

  <h2>Coverage Summary</h2>

  <div class="coverage-stat-grid">
{cards}
  </div>

  <h2>Theme Trails</h2>

  <div class="source-text-tags coverage-pills">
{themes}
  </div>

  <h2>Concept Trails</h2>

  <div class="source-text-tags coverage-pills">
{concepts}
  </div>

  <h2>Glossary Trails</h2>

  <div class="source-text-tags coverage-pills">
{glossary}
  </div>

  <h2>Priority Promotion Sections</h2>

  <p>These sections are useful candidates for deeper narrative pages because they combine large text spans with dense concept, equation, figure, or quote signals.</p>

  <table class="codex-status-table coverage-table">
    <thead>
      <tr>
        <th>Section</th>
        <th>Themes</th>
        <th>Why Promote</th>
        <th>Workbench</th>
      </tr>
    </thead>
    <tbody>
{priority_table_rows(source)}
    </tbody>
  </table>

  <h2>Complete Section Map</h2>

  <table class="codex-status-table coverage-table">
    <thead>
      <tr>
        <th>Section</th>
        <th>Words</th>
        <th>Themes</th>
        <th>Concepts</th>
        <th>Eq.</th>
        <th>Fig.</th>
        <th>Quotes</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
{section_table_rows(source)}
    </tbody>
  </table>
</details>

## Review Rules For This Source

<div class="research-passages">
  <section data-layer="source">
    <h3>Source text</h3>
    <p>Use the source-text link for broad reading and keyword research. Exact quotation still needs scan or source-PDF verification.</p>
  </section>
  <section data-layer="modern">
    <h3>Modern explanation</h3>
    <p>Modern translations should preserve Steinmetz's original notation and terminology before translating it into present-day engineering language.</p>
  </section>
  <section data-layer="interpretive">
    <h3>Interpretive readings</h3>
    <p>Ether-field, Tesla-era, and philosophical readings belong in labeled interpretive sections, never in the source-fact layer.</p>
  </section>
</div>
"""
    write_text(root / "site" / "src" / "content" / "docs" / "book-coverage" / f"{source['source_id']}.mdx", text)

def build_atlas(root: Path) -> dict[str, Any]:
    catalog = load_json(root / "sources" / "source_catalog.json", [])
    workbench = load_json(root / "processed" / "chapter_workbench.json", {})
    records = workbench.get("records", []) if isinstance(workbench, dict) else []
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        grouped[str(record.get("source_id"))].append(record)

    sources = []
    for source in catalog:
        source_id = str(source.get("source_id") or "")
        if not source_id:
            continue
        source_records = grouped.get(source_id, [])
        sources.append(aggregate_records(source, source_records))

    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Book coverage atlas exposes candidate section-level representation. It does not certify OCR text, equations, figures, or quotations as scan-verified.",
        "source_count": len(sources),
        "total_sections": sum(source["section_count"] for source in sources),
        "sources": sources,
    }


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    atlas = build_atlas(root)
    write_json(root / "processed" / "book_coverage_atlas.json", atlas)
    write_index_page(root, atlas)
    for source in atlas["sources"]:
        write_source_page(root, source)


if __name__ == "__main__":
    main()
