#!/usr/bin/env python3
"""Generate a source-grounded theme evidence atlas across processed Steinmetz texts.

The theme atlas is broader than the concept concordance. It gathers passages
around charter-critical research themes such as ether, field language,
dielectricity, hysteresis, reactance, impedance, transients, complex quantities,
symbolic method, and wave phenomena. It is an evidence-routing layer, not a
claim that every matched passage has already been interpreted correctly.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import quote


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_theme_evidence_atlas.py. Do not edit by hand. */}"


THEMES: dict[str, dict[str, Any]] = {
    "ether-field-language": {
        "label": "Ether And Field Language",
        "description": "Source-located passages where Steinmetz uses ether, field, force, stress, strain, pressure, tension, medium, displacement, or related older field vocabulary.",
        "aliases": [
            "ether",
            "aether",
            "field",
            "fields",
            "field of force",
            "field of forces",
            "medium",
            "stress",
            "strain",
            "pressure",
            "tension",
            "elastic",
            "displacement",
        ],
        "modern_prompt": "Read these passages first as historical electrical field language. Translate only after checking whether Steinmetz is describing a mathematical field, a material medium, an analogy, or a physical ontology.",
        "interpretive_boundary": "Ether-field readings may compare this language with later nonstandard vocabularies, but the page itself only proves that the words occur in the processed Steinmetz text.",
    },
    "magnetism-and-hysteresis": {
        "label": "Magnetism And Hysteresis",
        "description": "Passages involving magnetism, magnetic flux, permeability, reluctance, hysteresis, effective resistance, molecular friction, lag, magnetic loss, and hysteresis motor language.",
        "aliases": [
            "magnetism",
            "magnetic",
            "magnetic field",
            "magnetic flux",
            "magnetization",
            "magnetizing",
            "permeability",
            "reluctance",
            "hysteresis",
            "magnetic lag",
            "molecular friction",
            "effective resistance",
            "hysteresis loss",
            "hysteresis motor",
        ],
        "modern_prompt": "Separate magnetic material behavior from circuit equivalents. Steinmetz often lets magnetic loss appear as an equivalent electrical quantity, which is easy to flatten in modern summaries.",
        "interpretive_boundary": "A Wheeler-style reading may treat hysteresis as field lag or memory, but the archive must keep that reading distinct from Steinmetz's explicit engineering treatment.",
    },
    "dielectricity-capacity-and-displacement": {
        "label": "Dielectricity, Capacity, And Displacement",
        "description": "Passages involving dielectric fields, electrostatic capacity, condenser action, displacement current, capacity current, dielectric loss, and condensive reactance.",
        "aliases": [
            "dielectric",
            "dielectrics",
            "dielectricity",
            "electrostatic",
            "electrostatic capacity",
            "capacity",
            "condenser",
            "condensers",
            "capacitance",
            "displacement current",
            "capacity current",
            "dielectric loss",
            "condensive reactance",
        ],
        "modern_prompt": "Track whether Steinmetz is speaking of a physical dielectric, a capacity coefficient, a condenser circuit, or an AC quadrature component.",
        "interpretive_boundary": "Alternative readings that emphasize dielectric compression or counterspatial tendency are interpretive overlays unless Steinmetz's exact context supports the narrower claim.",
    },
    "reactance-impedance-and-admittance": {
        "label": "Reactance, Impedance, And Admittance",
        "description": "Passages involving reactance, impedance, admittance, conductance, susceptance, wattless components, counter e.m.f., and phasor opposition language.",
        "aliases": [
            "reactance",
            "impedance",
            "admittance",
            "conductance",
            "susceptance",
            "counter electromotive force",
            "counter-electromotive force",
            "counter e.m.f.",
            "counter emf",
            "wattless",
            "quadrature",
            "resistance",
            "inductive reactance",
            "condensive reactance",
        ],
        "modern_prompt": "Use these passages to preserve Steinmetz's transition from geometric/vector reasoning into impedance and admittance language.",
        "interpretive_boundary": "Field-pressure or inertia language may be useful as an analogy, but impedance and admittance claims must remain anchored in the circuit mathematics Steinmetz gives.",
    },
    "alternating-current-and-symbolic-method": {
        "label": "Alternating Current And Symbolic Method",
        "description": "Passages involving alternating current, vectors, phasors, complex quantities, imaginary quantities, the symbolic method, harmonics, wave shape, and power factor.",
        "aliases": [
            "alternating current",
            "alternating-current",
            "a.c.",
            "vector",
            "vectors",
            "phasor",
            "complex quantity",
            "complex quantities",
            "imaginary quantity",
            "imaginary quantities",
            "symbolic method",
            "symbolic representation",
            "symbolic expression",
            "harmonic",
            "harmonics",
            "wave shape",
            "power factor",
            "wattless current",
        ],
        "modern_prompt": "Read for the historical bridge from rotating vectors and symbolic notation into the phasor language used in modern AC engineering.",
        "interpretive_boundary": "Do not treat symbolic notation as a metaphysical claim by itself. Interpretive readings must first preserve the mathematical role of the symbols.",
    },
    "transients-oscillations-and-surges": {
        "label": "Transients, Oscillations, And Surges",
        "description": "Passages involving transients, temporary terms, stored energy, damping, oscillation, surges, impulses, lightning, arresters, and high-frequency disturbances.",
        "aliases": [
            "transient",
            "transients",
            "transient phenomenon",
            "transient phenomena",
            "temporary term",
            "stored energy",
            "energy stored",
            "oscillation",
            "oscillations",
            "oscillatory",
            "damping",
            "decrement",
            "surge",
            "surges",
            "impulse",
            "impulses",
            "lightning",
            "arrester",
            "arresters",
            "high frequency",
            "high potential",
            "high tension",
        ],
        "modern_prompt": "Use these hits to study how Steinmetz treats energy storage, natural response, damping, and line effects before modern transient textbooks standardized the presentation.",
        "interpretive_boundary": "Tesla-era and radiant-energy comparisons must be source-by-source. A transient or surge passage is evidence of an electrical phenomenon, not automatic proof of a later interpretive system.",
    },
    "waves-lines-and-radiation": {
        "label": "Waves, Lines, And Radiation",
        "description": "Passages involving waves, wavelength, frequency, propagation, standing waves, traveling waves, distributed constants, electrical radiation, light, spectrum, ultraviolet, X-rays, and transmission lines.",
        "aliases": [
            "wave",
            "waves",
            "wave length",
            "wave-length",
            "wavelength",
            "frequency",
            "periodicity",
            "propagation",
            "traveling wave",
            "travelling wave",
            "standing wave",
            "distributed constants",
            "distributed capacity",
            "distributed inductance",
            "transmission line",
            "radiation",
            "radiant energy",
            "electrical radiation",
            "electric radiation",
            "light",
            "spectrum",
            "ultra-violet",
            "ultraviolet",
            "ultra-red",
            "infra-red",
            "x-rays",
            "hertzian",
            "wireless",
        ],
        "modern_prompt": "This theme bridges ordinary wave language, distributed-line mathematics, and the radiation spectrum. Keep physical scale and context visible.",
        "interpretive_boundary": "Ether, Tesla-era, and Wheeler-style readings are only secondary layers here. The first task is to identify the wave or radiation context Steinmetz actually uses.",
    },
    "energy-power-and-work": {
        "label": "Energy, Power, And Work",
        "description": "Passages involving energy, power, work, watts, losses, efficiency, power factor, stored energy, expenditure of power, and field energy.",
        "aliases": [
            "energy",
            "power",
            "work",
            "watt",
            "watts",
            "loss",
            "losses",
            "efficiency",
            "power factor",
            "stored energy",
            "energy of the field",
            "expenditure of power",
        ],
        "modern_prompt": "Use these hits to keep the engineering accounting visible: what is stored, dissipated, transmitted, transformed, or measured.",
        "interpretive_boundary": "Interpretive field readings should not erase Steinmetz's explicit engineering accounting of power and energy.",
    },
    "machines-apparatus-and-systems": {
        "label": "Machines, Apparatus, And Systems",
        "description": "Passages involving motors, generators, transformers, reactors, lamps, arc lighting, synchronous systems, short circuits, and power-station apparatus.",
        "aliases": [
            "motor",
            "motors",
            "generator",
            "generators",
            "transformer",
            "transformers",
            "reactor",
            "reactors",
            "synchronous",
            "synchronism",
            "short circuit",
            "short-circuit",
            "arc lamp",
            "arc lamps",
            "arc lighting",
            "lamp",
            "lamps",
            "power station",
            "power house",
            "alternator",
            "commutator",
        ],
        "modern_prompt": "Use these hits to connect the abstract theory back to the machines and systems Steinmetz was actually engineering.",
        "interpretive_boundary": "Do not lift apparatus passages into purely philosophical claims without preserving their industrial and circuit context.",
    },
}


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "untitled"


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("{", "&#123;")
        .replace("}", "&#125;")
        .replace("$", "&#36;")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def focused_reader_url(url: Any, term: Any) -> str:
    value = str(url or "")
    query = str(term or "").strip()
    if not value or not query:
        return value
    base = value.split("#", 1)[0]
    separator = "&" if "?" in base else "?"
    return f"{base}{separator}q={quote(query)}#source-text-reader"


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def code_fence(text: str) -> str:
    text = text.rstrip() or "[No snippet captured.]"
    longest = 3
    for match in re.finditer(r"`+", text):
        longest = max(longest, len(match.group(0)) + 1)
    fence = "`" * longest
    return f"{fence}text wrap\n{text}\n{fence}"


def source_page_slug(record: dict[str, Any]) -> str:
    path = Path(str(record.get("text_path") or ""))
    if path.stem:
        return slugify(path.stem)
    return slugify(str(record.get("id") or record.get("title") or "section"))


def chapter_label(record: dict[str, Any]) -> str:
    kind = str(record.get("kind") or "section").replace("-", " ").title()
    number = record.get("number") or record.get("sequence")
    title = str(record.get("title") or "Untitled")
    if number:
        return f"{kind} {number}: {title}"
    return f"{kind}: {title}"


def record_location(record: dict[str, Any]) -> str:
    start = record.get("line_start")
    end = record.get("line_end")
    page_start = record.get("pdf_page_start")
    page_end = record.get("pdf_page_end")
    parts = []
    if page_start and page_end:
        parts.append(f"PDF pages {page_start}-{page_end}" if page_start != page_end else f"PDF page {page_start}")
    if start and end:
        parts.append(f"lines {start}-{end}")
    return ", ".join(parts) or "processed source text"


def read_chapter_text(root: Path, record: dict[str, Any]) -> str:
    path = root / str(record.get("text_path") or "")
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def flexible_alias_pattern(alias: str) -> str:
    alias = alias.strip()
    if not alias:
        return r"(?!x)x"
    if alias.lower() == "a.c.":
        return r"(?<![A-Za-z0-9])a\s*\.?\s*c\s*\.?(?![A-Za-z0-9])"
    tokens = re.findall(r"[A-Za-z0-9]+", alias.lower())
    if not tokens:
        return re.escape(alias.lower())
    if len(tokens) == 1:
        body = re.escape(tokens[0])
    else:
        body = r"[\s\-/.]+".join(re.escape(token) for token in tokens)
    return rf"(?<![A-Za-z0-9]){body}(?![A-Za-z0-9])"


def compile_alias_regex(aliases: list[str]) -> re.Pattern[str]:
    patterns = [flexible_alias_pattern(alias) for alias in aliases if alias.strip()]
    patterns = sorted(set(patterns), key=len, reverse=True)
    return re.compile("|".join(patterns) or r"(?!x)x", re.IGNORECASE)


def alias_counts(text: str, aliases: list[str]) -> list[dict[str, Any]]:
    counts = []
    for alias in aliases:
        regex = compile_alias_regex([alias])
        count = len(list(regex.finditer(text)))
        if count:
            counts.append({"alias": alias, "count": count})
    counts.sort(key=lambda item: (-int(item["count"]), str(item["alias"]).lower()))
    return counts


def find_snippets(text: str, matches: list[re.Match[str]], radius: int = 300, limit: int = 3) -> list[str]:
    snippets: list[str] = []
    seen: set[str] = set()
    for match in matches[: max(limit * 4, limit)]:
        start = max(0, match.start() - radius)
        end = min(len(text), match.end() + radius)
        snippet = normalize_space(text[start:end])
        if start > 0:
            snippet = "... " + snippet
        if end < len(text):
            snippet += " ..."
        key = snippet.lower()
        if key not in seen:
            snippets.append(snippet)
            seen.add(key)
        if len(snippets) >= limit:
            break
    return snippets


def load_chapter_records(root: Path, source_catalog: list[dict[str, Any]]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    source_titles = {source["source_id"]: source.get("title") for source in source_catalog}
    source_years = {source["source_id"]: source.get("year") for source in source_catalog}
    for source in source_catalog:
        source_id = str(source["source_id"])
        chapters = load_json(root / "processed" / source_id / "chapters.json", [])
        if not isinstance(chapters, list):
            continue
        for record in chapters:
            text = read_chapter_text(root, record)
            if not text:
                continue
            slug = source_page_slug(record)
            record = dict(record)
            record["_text"] = text
            record["_source_title"] = source_titles.get(source_id) or source_id
            record["_year"] = source_years.get(source_id)
            record["_source_text_url"] = f"{BASE_URL}/source-texts/{source_id}/{slug}/"
            record["_workbench_url"] = f"{BASE_URL}/chapter-workbench/{source_id}/{slug}/"
            records.append(record)
    return records


def build_theme_atlas(root: Path) -> dict[str, Any]:
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    if not isinstance(source_catalog, list):
        source_catalog = []
    source_titles = {source.get("source_id"): source.get("title") for source in source_catalog}
    chapter_records = load_chapter_records(root, source_catalog)

    themes: list[dict[str, Any]] = []
    for theme_id, theme in THEMES.items():
        regex = compile_alias_regex(theme["aliases"])
        section_hits: list[dict[str, Any]] = []
        source_totals: Counter[str] = Counter()
        source_sections: Counter[str] = Counter()
        total_occurrences = 0
        total_alias_counts: Counter[str] = Counter()

        for record in chapter_records:
            text = str(record.get("_text") or "")
            matches = list(regex.finditer(text))
            if not matches:
                continue
            source_id = str(record.get("source_id") or "")
            count = len(matches)
            aliases_in_section = alias_counts(text, theme["aliases"])
            for alias_count in aliases_in_section:
                total_alias_counts[str(alias_count["alias"])] += int(alias_count["count"])

            total_occurrences += count
            source_totals[source_id] += count
            source_sections[source_id] += 1
            section_hits.append(
                {
                    "source_id": source_id,
                    "source_title": record.get("_source_title"),
                    "year": record.get("_year"),
                    "section_id": record.get("id"),
                    "section_label": chapter_label(record),
                    "section_title": record.get("title"),
                    "kind": record.get("kind"),
                    "sequence": record.get("sequence"),
                    "number": record.get("number"),
                    "location": record_location(record),
                    "status": record.get("status", "candidate"),
                    "word_count": record.get("word_count"),
                    "occurrence_count": count,
                    "top_aliases": aliases_in_section[:8],
                    "source_text_url": record.get("_source_text_url"),
                    "workbench_url": record.get("_workbench_url"),
                    "snippets": find_snippets(text, matches),
                }
            )

        section_hits.sort(key=lambda item: (-int(item["occurrence_count"]), str(item["source_id"]), str(item["section_id"])))
        themes.append(
            {
                "id": theme_id,
                "label": theme["label"],
                "description": theme["description"],
                "aliases": theme["aliases"],
                "modern_prompt": theme["modern_prompt"],
                "interpretive_boundary": theme["interpretive_boundary"],
                "total_occurrences": total_occurrences,
                "matching_source_count": len(source_totals),
                "matching_section_count": len(section_hits),
                "source_totals": [
                    {
                        "source_id": source_id,
                        "source_title": source_titles.get(source_id, source_id),
                        "occurrence_count": source_totals[source_id],
                        "section_count": source_sections[source_id],
                    }
                    for source_id, _ in source_totals.most_common()
                ],
                "alias_totals": [
                    {"alias": alias, "count": count}
                    for alias, count in total_alias_counts.most_common()
                ],
                "section_hits": section_hits,
            }
        )

    themes.sort(key=lambda item: (-int(item["total_occurrences"]), item["label"]))
    return {
        "generated_at": date.today().isoformat(),
        "quality_note": "Generated theme evidence atlas. Counts and snippets are OCR/PDF-text source-location aids, not final claims. Verify exact passages against scans before quotation or interpretation.",
        "person": "Charles Proteus Steinmetz",
        "collection": "steinmetz",
        "source_count": len(source_catalog),
        "section_count": len(chapter_records),
        "total_themes": len(themes),
        "themes": themes,
    }


def build_index_page(atlas: dict[str, Any]) -> str:
    rows = []
    for theme in atlas["themes"]:
        rows.append(
            f"| [{md_escape(theme['label'])}]({BASE_URL}/theme-evidence/{theme['id']}/) | {theme['total_occurrences']} | {theme['matching_source_count']} | {theme['matching_section_count']} | {md_escape(', '.join(theme['aliases'][:8]))} |"
        )

    return f"""---
title: "Theme Evidence Atlas"
description: "Generated source-grounded atlas for charter-critical Steinmetz research themes."
---

{GENERATED_NOTE}

## Theme Evidence Atlas

This generated atlas gathers source-located passages for the project charter's most important research themes: ether, fields, magnetism, dielectricity, hysteresis, reactance, impedance, transients, alternating current, complex quantities, symbolic method, waves, radiation, power, and apparatus.

It is built for two readers at once: the scholar who wants traceable evidence, and the curious reader who wants a guided path into Steinmetz without already knowing which book to open.

<div class="source-text-warning" data-layer="source">
  <strong>Quality rule:</strong> this is an OCR/PDF-text evidence-routing layer. A hit means "read here next," not "this interpretation is proven."
</div>

<div class="codex-signal">
  <div><strong>{atlas['total_themes']} themes</strong><p>Charter-critical electrical, mathematical, field-language, and apparatus themes.</p></div>
  <div><strong>{atlas['section_count']} sections</strong><p>Every currently processed chapter, lecture, section, and report division is searched.</p></div>
  <div><strong>{atlas['source_count']} sources</strong><p>All seeded Steinmetz book and report sources are included in the current pass.</p></div>
</div>

## Best First Routes

<div class="source-matrix">
  <a href="{BASE_URL}/theme-evidence/ether-field-language/">Ether and field language<span>Start here for ether, field, force, stress, strain, pressure, displacement, and medium vocabulary.</span></a>
  <a href="{BASE_URL}/theme-evidence/reactance-impedance-and-admittance/">Impedance and reactance<span>Follow the AC vocabulary that became central to modern circuit engineering.</span></a>
  <a href="{BASE_URL}/theme-evidence/transients-oscillations-and-surges/">Transients and surges<span>Track stored energy, oscillations, damping, lightning, impulses, and high-frequency disturbances.</span></a>
  <a href="{BASE_URL}/theme-evidence/waves-lines-and-radiation/">Waves and radiation<span>Connect waves, lines, frequency, wavelength, radiation, light, spectrum, wireless, and X-rays.</span></a>
</div>

## Themes

| Theme | Hits | Sources | Sections | Search aliases |
| --- | ---: | ---: | ---: | --- |
{chr(10).join(rows)}

## Reading Contract

Use this atlas to discover source passages. Then open the source text, chapter workbench, scan, or curated page before promoting any statement into a concept page, comparison page, equation page, diagram page, or interpretive reading.
"""


def build_theme_page(theme: dict[str, Any]) -> str:
    source_rows = []
    for source in theme["source_totals"]:
        source_rows.append(
            f"| [{md_escape(source['source_title'])}]({BASE_URL}/source-texts/{source['source_id']}/) | {source['occurrence_count']} | {source['section_count']} |"
        )
    if not source_rows:
        source_rows.append("| No current hits | 0 | 0 |")

    alias_rows = []
    for alias in theme["alias_totals"][:24]:
        alias_rows.append(f"| `{md_escape(alias['alias'])}` | {alias['count']} |")
    if not alias_rows:
        alias_rows.append("| No current alias hits | 0 |")

    section_rows = []
    for hit in theme["section_hits"]:
        aliases = ", ".join(f"{item['alias']} ({item['count']})" for item in hit.get("top_aliases", [])[:5])
        first_alias = (hit.get("top_aliases") or [{}])[0].get("alias") if hit.get("top_aliases") else theme["label"]
        source_url = focused_reader_url(hit["source_text_url"], first_alias)
        section_rows.append(
            f"| [{md_escape(hit['section_label'])}]({source_url}) | [{md_escape(hit['source_title'])}]({BASE_URL}/source-texts/{hit['source_id']}/) | {hit['occurrence_count']} | {md_escape(aliases)} | [{md_escape('Research review')}]({hit['workbench_url']}) | {md_escape(hit['location'])} |"
        )
    if not section_rows:
        section_rows.append("| No current hits | - | 0 | - | - | - |")

    snippets = []
    for hit in theme["section_hits"][:30]:
        hit_snippets = hit.get("snippets") or []
        if not hit_snippets:
            continue
        first_alias = (hit.get("top_aliases") or [{}])[0].get("alias") if hit.get("top_aliases") else theme["label"]
        snippet_text = "\n\n".join(code_fence(snippet) for snippet in hit_snippets[:2])
        snippets.append(
            f"""<details class="layered-reading" data-layer="source">
<summary>{html_escape(hit['section_label'])} - {hit['occurrence_count']} hit(s)</summary>
<div class="body">

[Read focused source text]({focused_reader_url(hit['source_text_url'], first_alias)}) | [Research review]({hit['workbench_url']})

{snippet_text}

</div>
</details>"""
        )
    snippet_section = "\n\n".join(snippets) or "No snippets captured for the current pass."

    return f"""---
title: {yaml_quote(theme['label'] + " Evidence")}
description: {yaml_quote("Generated source-grounded evidence atlas page for " + theme['label'] + ".")}
---

{GENERATED_NOTE}

## {md_escape(theme['label'])}

<div class="source-text-warning" data-layer="source">
  <strong>Evidence status:</strong> generated from processed OCR/PDF text. Treat each hit as a source-location aid until the passage is checked against the scan.
</div>

<div class="codex-signal">
  <div><strong>{theme['total_occurrences']} hits</strong><p>Total text matches across processed Steinmetz sections.</p></div>
  <div><strong>{theme['matching_source_count']} sources</strong><p>Sources containing at least one matched alias.</p></div>
  <div><strong>{theme['matching_section_count']} sections</strong><p>Chapters, lectures, sections, or report divisions with matches.</p></div>
</div>

## What This Theme Gathers

{md_escape(theme['description'])}

## Reading Layers

<div class="research-passages">
  <section data-layer="source">
    <h3>Source Evidence</h3>
    <p>Use the tables and snippets below to locate Steinmetz passages. Exact wording still needs scan verification before canonical quotation.</p>
  </section>
  <section data-layer="modern">
    <h3>Modern Reading Prompt</h3>
    <p>{html_escape(theme['modern_prompt'])}</p>
  </section>
  <section data-layer="interpretive">
    <h3>Interpretive Boundary</h3>
    <p>{html_escape(theme['interpretive_boundary'])}</p>
  </section>
</div>

## Matched Aliases

| Alias | Hits |
| --- | ---: |
{chr(10).join(alias_rows)}

## Source Distribution

| Source | Hits | Sections |
| --- | ---: | ---: |
{chr(10).join(source_rows)}

## Section Hits

| Section | Source | Hits | Top matched aliases | Workbench | Location |
| --- | --- | ---: | --- | --- | --- |
{chr(10).join(section_rows)}

## Representative Source-Located Passages

{snippet_section}
"""


def write_pages(root: Path, atlas: dict[str, Any]) -> None:
    out_dir = root / "site" / "src" / "content" / "docs" / "theme-evidence"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    write_text(out_dir / "index.mdx", build_index_page(atlas))
    for theme in atlas["themes"]:
        write_text(out_dir / str(theme["id"]) / "index.mdx", build_theme_page(theme))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()
    atlas = build_theme_atlas(root)
    write_json(root / "processed" / "theme_evidence_atlas.json", atlas)
    write_pages(root, atlas)
    print(
        f"Generated {atlas['total_themes']} theme evidence pages "
        f"from {atlas['section_count']} processed sections."
    )


if __name__ == "__main__":
    main()
