#!/usr/bin/env python3
"""Generate public source-text reader pages for processed chapters.

This script turns `processed/*/chapters.json` records into Starlight MDX pages.
The generated pages expose the current OCR/PDF text for every processed
chapter, lecture, section, and report division while preserving candidate
status labels. They are source access pages, not reviewed editions.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any


BASE_URL = "/Charles-Proteus-Steinmetz-Texts-AI-Decoded"
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_source_text_pages.py. Do not edit by hand. */}"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "untitled"


def yaml_quote(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def html_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def code_fence(text: str) -> str:
    longest = 3
    for match in re.finditer(r"`+", text):
        longest = max(longest, len(match.group(0)) + 1)
    fence = "`" * longest
    return f"{fence}text wrap\n{text.rstrip()}\n{fence}"


def read_source_text(root: Path, record: dict[str, Any]) -> str:
    path = root / str(record.get("text_path") or "")
    if not path.exists():
        return "[Text file missing. Regenerate processed chapter splits before publishing this page.]\n"
    return path.read_text(encoding="utf-8", errors="replace")


def write_source_text_asset(
    root: Path,
    public_data_dir: Path,
    source_id: str,
    record: dict[str, Any],
) -> str:
    text = read_source_text(root, record)
    slug = source_page_slug(record)
    asset_path = public_data_dir / source_id / f"{slug}.txt"
    asset_path.parent.mkdir(parents=True, exist_ok=True)
    asset_path.write_text(text, encoding="utf-8", newline="\n")
    return f"{BASE_URL}/source-texts-data/{source_id}/{slug}.txt"


def source_page_slug(record: dict[str, Any]) -> str:
    path = Path(str(record.get("text_path") or ""))
    if path.stem:
        return slugify(path.stem)
    return slugify(str(record.get("id") or record.get("title") or "section"))


def source_title_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {str(source["source_id"]): str(source.get("title") or source["source_id"]) for source in catalog}


def source_site_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {str(source["source_id"]): str(source.get("site_path") or "") for source in catalog}


def source_archive_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {
        str(source["source_id"]): str(source.get("internet_archive_id") or "")
        for source in catalog
    }


def source_raw_map(catalog: list[dict[str, Any]]) -> dict[str, str]:
    return {
        str(source["source_id"]): str(source.get("local_raw_file") or "")
        for source in catalog
    }


def chapter_label(record: dict[str, Any]) -> str:
    kind = str(record.get("kind") or "section").replace("-", " ").title()
    number = record.get("number") or record.get("sequence")
    title = str(record.get("title") or "Untitled")
    if number:
        return f"{kind} {number}: {title}"
    return f"{kind}: {title}"


def record_location(record: dict[str, Any]) -> str:
    start = record.get("line_start")
    end = record.get("line_end")
    page_start = record.get("pdf_page_start")
    page_end = record.get("pdf_page_end")
    parts = []
    if page_start and page_end:
        parts.append(f"PDF pages {page_start}-{page_end}" if page_start != page_end else f"PDF page {page_start}")
    if start and end:
        parts.append(f"lines {start}-{end}")
    return ", ".join(parts) or "processed source text"


def status_note(status: str) -> str:
    status_lower = status.lower()
    if "pdf-text" in status_lower:
        return "Embedded PDF text extraction. Verify against page images before exact quotation."
    if "ocr" in status_lower or "candidate" in status_lower:
        return "OCR-derived candidate text. Verify against the scan before exact quotation."
    return "Processed source text. Verify against source custody files before canonical use."


def metadata_rows(
    source_title: str,
    record: dict[str, Any],
    location: str,
    text_asset_url: str,
    status: str,
    internet_archive_id: str,
    local_raw_file: str,
) -> str:
    fields = [
        ("Source", source_title),
        ("Section ID", record.get("id") or ""),
        ("Kind", record.get("kind") or ""),
        ("Sequence", record.get("sequence") or ""),
        ("Source Location", location),
        ("Text Path", record.get("text_path") or ""),
        ("Public Text Asset", f'<a href="{html_escape(text_asset_url)}">{html_escape(text_asset_url)}</a>'),
        ("Status", status),
        ("Internet Archive ID", internet_archive_id or "not listed"),
        ("Local Raw File", local_raw_file or "not listed"),
    ]
    rows = []
    for label, value in fields:
        rows.append(f"<tr><th>{html_escape(label)}</th><td>{value if str(value).startswith('<a ') else html_escape(value)}</td></tr>")
    return "\n".join(rows)


def original_scan_block(source_title: str, internet_archive_id: str) -> str:
    if not internet_archive_id:
        return """<div class="source-text-warning" data-layer="source">
  <strong>Original scan:</strong> no Internet Archive scan ID is listed for this source yet. Use the custody files and source manifest until a public scan route is added.
</div>"""
    ia_id = html_escape(internet_archive_id)
    title = html_escape(source_title)
    return f"""<details class="source-reader source-scan-viewer" id="original-scan-viewer" data-layer="source">
  <summary>View Original Scan Inline</summary>
  <p>This embedded Internet Archive scan is the verification layer. Use it when exact wording, page labels, equations, diagrams, or captions matter.</p>
  <iframe src="https://archive.org/embed/{ia_id}" title="Original scan for {title}" loading="lazy"></iframe>
  <p><a href="https://archive.org/details/{ia_id}">Open this scan on Archive.org</a></p>
</details>"""


def build_source_index(
    source_id: str,
    source_title: str,
    source_site_path: str,
    records: list[dict[str, Any]],
) -> str:
    cards = []
    for record in records:
        slug = source_page_slug(record)
        title = chapter_label(record)
        status = str(record.get("status") or "candidate")
        words = record.get("word_count")
        tags = ", ".join(str(tag) for tag in record.get("concept_tags") or []) or "-"
        cards.append(
            f"""<a class="source-section-card" href="{BASE_URL}/source-texts/{source_id}/{slug}/">
  <strong>{html_escape(title)}</strong>
  <span>{html_escape(record_location(record))} - {html_escape(record.get('kind') or 'section')} - {words or '-'} words</span>
  <small>{html_escape(status)} - {html_escape(tags)}</small>
</a>"""
        )
    cards_text = "\n".join(cards)
    first_record = records[0] if records else None
    first_link = (
        f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(first_record)}/">Start reading first section</a>'
        if first_record
        else ""
    )
    return f"""---
title: {yaml_quote(source_title + " Source Text")}
description: {yaml_quote("Generated OCR/PDF text reader for " + source_title + ".")}
pagefind: false
---

{GENERATED_NOTE}

## Source Text Reader

These pages expose the current processed chapter, lecture, section, or report text for this source. They are working research text, not corrected critical editions.

<div class="source-access-actions">
  {first_link}
  <a href="{BASE_URL}{source_site_path}">Open curated source overview</a>
  <a href="{BASE_URL}/chapter-workbench/{source_id}/">Open generated chapter workbench</a>
</div>

<div class="source-text-warning" data-layer="source">
  <strong>Status:</strong> OCR/PDF text is useful for research navigation, but exact quotation still requires scan verification.
</div>

## Sections

<div class="source-section-grid">
{cards_text}
</div>
"""


def build_reader_page(
    source_id: str,
    source_title: str,
    source_site_path: str,
    record: dict[str, Any],
    text_asset_url: str,
    internet_archive_id: str,
    local_raw_file: str,
    previous_record: dict[str, Any] | None,
    next_record: dict[str, Any] | None,
) -> str:
    title = chapter_label(record)
    status = str(record.get("status") or "candidate")
    location = record_location(record)
    tags = record.get("concept_tags") or []
    tag_links = " ".join(f"<span>{html_escape(tag)}</span>" for tag in tags) or "<span>untagged</span>"
    reader_tags = "|".join(str(tag) for tag in tags)
    previous_link = ""
    if previous_record:
        previous_link = (
            f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(previous_record)}/">'
            f"Previous: {html_escape(chapter_label(previous_record))}</a>"
        )
    next_link = ""
    if next_record:
        next_link = (
            f'<a href="{BASE_URL}/source-texts/{source_id}/{source_page_slug(next_record)}/">'
            f"Next: {html_escape(chapter_label(next_record))}</a>"
        )
    back_link = f'<a href="{BASE_URL}/source-texts/{source_id}/">Back to {html_escape(source_title)} source text</a>'
    nav_links = "\n    ".join(link for link in [previous_link, back_link, next_link] if link)
    scan_link = (
        f'<a href="#original-scan-viewer">View original scan</a> <a href="https://archive.org/details/{html_escape(internet_archive_id)}">Archive.org</a>'
        if internet_archive_id
        else '<span>No public scan embed listed yet</span>'
    )

    return f"""---
title: {yaml_quote(title)}
description: {yaml_quote("Generated source text reader page for " + source_title + ".")}
pagefind: false
---

{GENERATED_NOTE}

import SourceRef from '../../../../components/SourceRef.astro';

<SourceRef source="{html_escape(source_title)}" location="{html_escape(location)}" status="{html_escape(status)}" />

<div class="reader-first-callout" data-layer="source">
  <strong>Reader-first view:</strong> the manuscript text is presented first for reading. Custody metadata, extraction warnings, and scan links remain close by but no longer block the reading path.
</div>

<div class="source-text-toolbar" data-layer="source">
  <a href="#source-text">Read source text</a>
  {scan_link}
  <a href="{BASE_URL}/source-texts/{source_id}/">Source text index</a>
  <a href="{BASE_URL}/chapter-workbench/{source_id}/{source_page_slug(record)}/#chapter-local-concept-hits">Focused workbench</a>
  <a href="{BASE_URL}{source_site_path}">Curated source overview</a>
  <a href="https://github.com/TRUEMODELOFTHEWORLD/Charles-Proteus-Steinmetz-Texts-AI-Decoded/blob/main/{html_escape(record.get('text_path') or '')}">Open text file on GitHub</a>
</div>

## Source Text

<div class="source-text-warning" data-layer="source">
  <strong>{html_escape(status_note(status))}</strong>
  <p>Use this text for reading and discovery. Use the original scan below before exact quotation, mathematical transcription, or diagram citation.</p>
</div>

<div
  class="source-text-loader source-text-manuscript"
  id="source-text-reader"
  data-source-text-url="{html_escape(text_asset_url)}"
  data-reader-title="{html_escape(title)}"
  data-reader-source="{html_escape(source_title)}"
  data-reader-location="{html_escape(location)}"
  data-reader-status="{html_escape(status)}"
  data-reader-tags="{html_escape(reader_tags)}"
>Loading source text...</div>

<div class="source-text-tags" data-layer="source">
  {tag_links}
</div>

<noscript>
  <p><a href="{html_escape(text_asset_url)}">Open the source text asset</a></p>
</noscript>

## Original Scan

{original_scan_block(source_title, internet_archive_id)}

<details class="source-metadata-panel" id="reader-metadata" data-layer="source">
  <summary>Reader Metadata And Custody Notes</summary>
  <table class="codex-status-table source-metadata-table">
    <tbody>
{metadata_rows(source_title, record, location, text_asset_url, status, internet_archive_id, local_raw_file)}
    </tbody>
  </table>
</details>

<nav class="source-page-navigation" data-layer="source" aria-label="Source text navigation">
  <strong>Continue Reading</strong>
  <div class="source-text-toolbar">
    {nav_links}
  </div>
</nav>
"""


def build_root_index(catalog: list[dict[str, Any]], grouped: dict[str, list[dict[str, Any]]]) -> str:
    cards = []
    total_sections = 0
    for source in catalog:
        source_id = str(source["source_id"])
        records = grouped.get(source_id, [])
        total_sections += len(records)
        if not records:
            continue
        cards.append(
            f"""<a class="source-section-card source-book-card" href="{BASE_URL}/source-texts/{source_id}/">
  <strong>{html_escape(source.get('title') or source_id)}</strong>
  <span>{len(records)} processed text sections - {html_escape(source.get('year') or '')}</span>
  <small>{html_escape(source.get('processed_status') or '')}</small>
</a>"""
        )
    cards_text = "\n".join(cards)
    return f"""---
title: Source Text Browser
description: Generated public reader for every processed Steinmetz chapter, lecture, section, and report division.
pagefind: false
---

{GENERATED_NOTE}

The source text browser is the archive's broad reading layer. It exposes every processed chapter, lecture, section, and report division generated from OCR or embedded PDF text.

It is deliberately labeled as working text. These pages let researchers read widely now, while the project continues scan verification, corrected transcriptions, equation cleanup, diagram extraction, and deep commentary.

<div class="source-text-warning" data-layer="source">
  <strong>{total_sections} processed text sections are currently public in this generated browser.</strong>
  <p>Use these pages for discovery and broad reading. Use scan-verified pages for exact quotation and canonical mathematical claims.</p>
</div>

## Source Indexes

<div class="source-section-grid">
{cards_text}
</div>

## How To Use This Browser

1. Open a source index.
2. Read the generated text page for a chapter or section.
3. Follow concept tags into curated pages when available.
4. Treat OCR/PDF text as candidate material until scan verification is complete.
5. Promote important passages into concept, equation, diagram, glossary, comparison, or hidden-gem pages only after checking the source image.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("site") / "src" / "content" / "docs" / "source-texts",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    out_dir = root / args.out
    public_data_dir = root / "site" / "public" / "source-texts-data"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if public_data_dir.exists():
        shutil.rmtree(public_data_dir)
    public_data_dir.mkdir(parents=True, exist_ok=True)

    catalog = load_json(root / "sources" / "source_catalog.json", [])
    titles = source_title_map(catalog)
    site_paths = source_site_map(catalog)
    archive_ids = source_archive_map(catalog)
    raw_files = source_raw_map(catalog)
    atlas = load_json(root / "processed" / "chapter_atlas.json", {})
    atlas_records = {
        str(record.get("id")): record
        for record in atlas.get("records", [])
        if isinstance(record, dict)
    }

    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in catalog:
        source_id = str(source["source_id"])
        chapters = load_json(root / "processed" / source_id / "chapters.json", [])
        if not isinstance(chapters, list):
            chapters = []
        for chapter in chapters:
            atlas_record = atlas_records.get(str(chapter.get("id")), {})
            merged = dict(chapter)
            if atlas_record:
                merged["word_count"] = atlas_record.get("word_count")
                merged["theme_counts"] = atlas_record.get("theme_counts")
                merged["top_themes"] = atlas_record.get("top_themes")
            grouped.setdefault(source_id, []).append(merged)

    write_text(out_dir / "index.mdx", build_root_index(catalog, grouped))

    total_pages = 1
    for source_id, records in grouped.items():
        if not records:
            continue
        records.sort(key=lambda record: int(record.get("sequence") or 0))
        source_title = titles.get(source_id, source_id)
        source_site_path = site_paths.get(source_id, f"/sources/{source_id}/")
        internet_archive_id = archive_ids.get(source_id, "")
        local_raw_file = raw_files.get(source_id, "")
        source_dir = out_dir / source_id
        write_text(source_dir / "index.mdx", build_source_index(source_id, source_title, source_site_path, records))
        total_pages += 1
        for index, record in enumerate(records):
            previous_record = records[index - 1] if index else None
            next_record = records[index + 1] if index + 1 < len(records) else None
            text_asset_url = write_source_text_asset(root, public_data_dir, source_id, record)
            write_text(
                source_dir / f"{source_page_slug(record)}.mdx",
                build_reader_page(
                    source_id,
                    source_title,
                    source_site_path,
                    record,
                    text_asset_url,
                    internet_archive_id,
                    local_raw_file,
                    previous_record,
                    next_record,
                ),
            )
            total_pages += 1

    print(f"Generated {total_pages} source-text pages in {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
