#!/usr/bin/env python3
"""Generate visual topic galleries that connect diagrams to sources and math.

The archive has several visual surfaces: original crops, OCR figure candidates,
modern guide diagrams, source visual maps, and formula maps. This generator
builds topic-level galleries so readers can enter visually without losing the
source and verification discipline.
"""

from __future__ import annotations

import html
import json
import re
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_visual_topic_galleries.py. Do not edit by hand. */}"


TOPICS: list[dict[str, Any]] = [
    {
        "id": "radiation-light-spectrum",
        "title": "Radiation, Light, And Spectrum",
        "description": "Visual routes through radiation, electric waves, visible light, ultraviolet, X-rays, refraction, reflection, and spectrum language.",
        "concepts": ["radiation", "electric-waves", "frequency", "spectrum", "ether", "illumination", "light-flux"],
        "keywords": ["radiation", "light", "spectrum", "wave", "frequency", "wavelength", "ultra", "violet", "x-ray", "refraction", "reflection"],
        "sources": ["radiation-light-and-illumination", "general-lectures-electrical-engineering"],
    },
    {
        "id": "ac-symbolic-geometry",
        "title": "AC Symbolic Geometry",
        "description": "Visual routes through vectors, rectangular components, complex quantities, j rotation, impedance, reactance, admittance, and phasor thinking.",
        "concepts": ["symbolic-method", "complex-quantities", "phasor", "operator-j", "impedance", "reactance", "admittance", "phase"],
        "keywords": ["symbolic", "complex", "vector", "rectangular", "component", "phasor", "phase", "impedance", "reactance", "admittance", "quadrature"],
        "sources": [
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-alternating-current-phenomena-1897",
            "theory-calculation-alternating-current-phenomena-1900",
            "engineering-mathematics",
        ],
    },
    {
        "id": "transients-surges-oscillations",
        "title": "Transients, Surges, And Oscillations",
        "description": "Visual routes through condenser charge and discharge, transient terms, damping, impulses, lightning surges, reflections, and traveling waves.",
        "concepts": ["transient-phenomena", "oscillation-damping", "lightning-surges", "traveling-wave", "distributed-constants", "capacity", "condenser"],
        "keywords": ["transient", "surge", "impulse", "lightning", "oscillation", "damping", "decrement", "condenser", "charge", "discharge", "traveling", "standing"],
        "sources": [
            "theory-calculation-transient-electric-phenomena-oscillations",
            "elementary-lectures-electric-discharges-waves-impulses",
            "electric-discharges-waves-impulses-1914",
            "general-lectures-electrical-engineering",
        ],
    },
    {
        "id": "magnetism-hysteresis-machines",
        "title": "Magnetism, Hysteresis, And Machines",
        "description": "Visual routes through magnetic lag, hysteresis loss, rotating magnetic fields, induction machines, effective resistance, and magnetic energy.",
        "concepts": ["hysteresis", "magnetism", "magnetic-loss", "effective-resistance", "rotating-magnetic-field", "induction-motor"],
        "keywords": ["hysteresis", "magnetic", "magnetism", "field", "lag", "loss", "rotating", "motor", "transformer", "flux"],
        "sources": [
            "theoretical-elements-electrical-engineering",
            "theory-calculation-alternating-current-phenomena",
            "theory-calculation-electric-apparatus",
            "engineering-mathematics",
        ],
    },
    {
        "id": "dielectric-field-energy",
        "title": "Dielectric Field And Stored Energy",
        "description": "Visual routes through capacity, dielectric field language, magnetic/dielectric storage, distributed constants, and energy readjustment.",
        "concepts": ["dielectric-field", "dielectric-loss", "capacity", "inductance", "energy-storage", "distributed-constants"],
        "keywords": ["dielectric", "capacity", "condenser", "stored", "energy", "electrostatic", "inductance", "distributed"],
        "sources": [
            "theoretical-elements-electrical-engineering",
            "theory-calculation-electric-circuits",
            "theory-calculation-transient-electric-phenomena-oscillations",
            "elementary-lectures-electric-discharges-waves-impulses",
        ],
    },
    {
        "id": "power-systems-reactors",
        "title": "Power Systems, Reactors, And Synchronism",
        "description": "Visual routes through system sections, reactors, synchronizing current, power-limiting reactance, apparatus, and industrial engineering decisions.",
        "concepts": ["power-limiting-reactors", "synchronizing-power", "reactance", "power-systems", "apparatus"],
        "keywords": ["reactor", "synchron", "station", "system", "power", "apparatus", "machine", "generator", "tie", "short-circuit"],
        "sources": [
            "commonwealth-edison-generating-system-trouble",
            "theory-calculation-electric-circuits",
            "theory-calculation-electric-apparatus",
            "general-lectures-electrical-engineering",
        ],
    },
    {
        "id": "ether-field-relativity",
        "title": "Ether, Field Language, And Relativity",
        "description": "Visual routes through ether references, Faraday-Maxwell field language, field of force, field of energy, and relativity-era boundaries.",
        "concepts": ["ether", "field-language", "energy-field", "relativity", "force"],
        "keywords": ["ether", "field", "force", "energy", "relativity", "space", "gravitation", "faraday", "maxwell"],
        "sources": ["four-lectures-relativity-space", "radiation-light-and-illumination", "theoretical-elements-electrical-engineering"],
    },
    {
        "id": "illumination-engineering",
        "title": "Illumination Engineering",
        "description": "Visual routes through light flux, photometry, distribution curves, inverse-square reasoning, physiological visibility, and lighting practice.",
        "concepts": ["illumination", "light-flux", "photometry", "radiation", "inverse-square"],
        "keywords": ["illumination", "light flux", "photometry", "lumin", "candle", "distribution", "physiological", "visibility"],
        "sources": ["radiation-light-and-illumination"],
    },
]


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")


def clean(value: Any, limit: int | None = None) -> str:
    text = "" if value is None else str(value)
    text = re.sub(r"\s+", " ", text).strip()
    if limit and len(text) > limit:
        text = text[: limit - 3].rstrip() + "..."
    return text


def esc(value: Any, limit: int | None = None) -> str:
    return html.escape(clean(value, limit), quote=True).replace("{", "&#123;").replace("}", "&#125;")


def slug_text(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "-", clean(value).lower()).strip("-")


def haystack(record: dict[str, Any]) -> str:
    parts = [
        record.get("id"),
        record.get("title"),
        record.get("subtitle"),
        record.get("caption"),
        record.get("source_location"),
        record.get("filename"),
        record.get("source_title"),
        record.get("section_label"),
        record.get("original_form"),
        " ".join(str(item) for item in record.get("concepts") or []),
        " ".join(str(item) for item in record.get("sources") or []),
    ]
    return " ".join(clean(part).lower() for part in parts if part)


def matches(record: dict[str, Any], topic: dict[str, Any]) -> bool:
    text = haystack(record)
    terms = [*topic["concepts"], *topic["keywords"], *topic["sources"]]
    return any(term.lower() in text or slug_text(term) in text for term in terms)


def link_to_source_map(source_id: str, kind: str) -> str:
    if kind == "visual":
        return f"{BASE_URL}/diagrams/source-visuals/{source_id}/"
    if kind == "formula":
        return f"{BASE_URL}/mathematics/source-formula-maps/{source_id}/"
    if kind == "source":
        return f"{BASE_URL}/source-texts/{source_id}/"
    return f"{BASE_URL}/book-coverage/{source_id}/"


def visual_cards(records: list[dict[str, Any]]) -> str:
    if not records:
        return "<p>No modern guide diagrams are currently routed to this topic.</p>"
    cards = []
    for record in records:
        concepts = ", ".join(clean(item) for item in record.get("concepts") or [])
        cards.append(
            f"""<div class="codex-visual-card">
  <img src="{esc(record.get('public_url'))}" alt="{esc(record.get('title'))}" />
  <div>
    <strong>{esc(record.get('title'))}</strong>
    <p>{esc(record.get('subtitle'))}</p>
    <p><small>{esc(concepts)}</small></p>
    <p><a href="{esc(record.get('public_url'))}">Open SVG</a> - <a href="{BASE_URL}/diagrams/recreated-visual-index/">all recreated visuals</a></p>
  </div>
</div>"""
        )
    return "\n".join(cards)


def original_crop_records(root: Path, source_titles: dict[str, str]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    crop_root = root / "diagrams" / "original"
    if not crop_root.exists():
        return records
    for manifest in sorted(crop_root.glob("*/figures/*.png.json")):
        data = load_json(manifest, {})
        if not isinstance(data, dict):
            continue
        output_path = str(data.get("output_path") or "")
        if not output_path:
            continue
        public_path = output_path.replace("\\", "/")
        source_id = str(data.get("source_id") or manifest.parts[-3])
        public_url = f"{BASE_URL}/{public_path}"
        title = manifest.name.replace(".png.json", "").replace("-", " ").title()
        records.append(
            {
                "id": data.get("id") or manifest.stem,
                "title": title,
                "filename": manifest.name.replace(".json", ""),
                "source_id": source_id,
                "source_title": source_titles.get(source_id, source_id.replace("-", " ").title()),
                "source_location": data.get("source_location") or "",
                "caption": data.get("quality_note") or "Promoted original scan crop.",
                "public_url": public_url,
                "status": data.get("status") or "promoted original scan crop",
                "links": {
                    "source_text_index": f"{BASE_URL}/source-texts/{source_id}/",
                    "visual_map": f"{BASE_URL}/diagrams/source-visuals/{source_id}/",
                    "diagram_archive": f"{BASE_URL}/diagrams/",
                },
            }
        )
    return records


def original_crop_cards(records: list[dict[str, Any]]) -> str:
    if not records:
        return "<p>No promoted original scan crops are currently routed to this topic. Use the candidate figure leads below to pick the next crops for extraction.</p>"
    cards = []
    for record in records[:18]:
        links = record.get("links") or {}
        cards.append(
            f"""<div class="codex-visual-card original-crop-card">
  <img src="{esc(record.get('public_url'))}" alt="{esc(record.get('title'))}" />
  <div>
    <strong>{esc(record.get('title'))}</strong>
    <p>{esc(record.get('source_title'))}</p>
    <p><small>{esc(record.get('source_location'), 220)}</small></p>
    <p><a href="{esc(record.get('public_url'))}">Open image</a> - <a href="{esc(links.get('source_text_index') or '#')}">read source</a> - <a href="{esc(links.get('visual_map') or '#')}">source visual map</a></p>
  </div>
</div>"""
        )
    return "\n".join(cards)


def figure_rows(records: list[dict[str, Any]], limit: int = 24) -> str:
    rows = []
    for record in records[:limit]:
        links = record.get("links") or {}
        source_link = links.get("source_text") or links.get("source_text_index") or "#"
        workbench_link = links.get("workbench") or links.get("workbench_index") or "#"
        rows.append(
            "<tr>"
            f"<td><code>{esc(record.get('id'))}</code><br/><small>Fig. {esc(record.get('figure_number'))}</small></td>"
            f"<td>{esc(record.get('caption'), 210)}</td>"
            f"<td>{esc(record.get('source_title'))}<br/><small>{esc(record.get('section_label'))}</small></td>"
            f"<td><a href=\"{esc(source_link)}\">source</a><br/><a href=\"{esc(workbench_link)}\">research review</a></td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="4">No OCR figure candidates are currently routed to this topic.</td></tr>')
    return "\n".join(rows)


def formula_rows(records: list[dict[str, Any]], limit: int = 18) -> str:
    rows = []
    for record in records[:limit]:
        links = record.get("links") or {}
        source_link = links.get("source_text") or links.get("source_text_index") or "#"
        workbench_link = links.get("workbench") or links.get("workbench_index") or "#"
        rows.append(
            "<tr>"
            f"<td><code>{esc(record.get('id'))}</code><br/><small>{esc(record.get('family'))}</small></td>"
            f"<td><code>{esc(record.get('original_form'), 180)}</code></td>"
            f"<td>{esc(record.get('source_title'))}<br/><small>{esc(record.get('section_label'))}</small></td>"
            f"<td><a href=\"{esc(source_link)}\">source</a><br/><a href=\"{esc(workbench_link)}\">research review</a></td>"
            "</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="4">No formula candidates are currently routed to this topic.</td></tr>')
    return "\n".join(rows)


def source_links(topic: dict[str, Any]) -> str:
    links = []
    for source_id in topic["sources"]:
        links.append(
            f"""<a href="{link_to_source_map(source_id, 'visual')}">{esc(source_id.replace('-', ' ').title())}
<span>Visual map</span></a>"""
        )
        links.append(
            f"""<a href="{link_to_source_map(source_id, 'formula')}">{esc(source_id.replace('-', ' ').title())}
<span>Formula map</span></a>"""
        )
    return "\n".join(links)


def topic_page(
    topic: dict[str, Any],
    visuals: list[dict[str, Any]],
    original_crops: list[dict[str, Any]],
    figures: list[dict[str, Any]],
    formulas: list[dict[str, Any]],
) -> str:
    source_counter = Counter(clean(record.get("source_title") or record.get("source_id")) for record in figures + formulas)
    source_summary = ", ".join(f"{source} ({count})" for source, count in source_counter.most_common(4)) or "No candidate source distribution yet."
    return f"""---
title: "{topic['title']}"
description: "{topic['description']}"
---

{GENERATED_NOTE}

<div class="coverage-hero visual-topic-hero">
  <div>
    <p class="home-kicker">Visual topic gallery</p>
    <h1>{esc(topic['title'])}</h1>
    <p>{esc(topic['description'])}</p>
  </div>
  <div class="coverage-stat-grid">
    <div><strong>{len(original_crops)}</strong><p>original crops</p><span>scan images routed into this topic</span></div>
    <div><strong>{len(visuals)}</strong><p>modern guide diagrams</p><span>reconstructions, not historical evidence</span></div>
    <div><strong>{len(figures)}</strong><p>figure candidates</p><span>OCR/PDF-text leads needing crop review</span></div>
    <div><strong>{len(formulas)}</strong><p>formula candidates</p><span>math leads needing transcription review</span></div>
  </div>
</div>

<div class="source-text-warning" data-layer="source">
  <strong>Layer rule:</strong> original crops, figure candidates, modern redraws, and formula candidates are separated. Use this page to browse visually, then verify in the linked source text and workbench.
</div>

## Source Routes

<div class="source-matrix visual-topic-routes">
{source_links(topic)}
</div>

## Original Scan Crops

<div class="codex-visual-grid original-crop-grid">
{original_crop_cards(original_crops)}
</div>

## Modern Guide Diagrams

<div class="codex-visual-grid">
{visual_cards(visuals)}
</div>

## Candidate Figure Leads

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>Caption lead</th><th>Source section</th><th>Routes</th></tr>
  </thead>
  <tbody>
{figure_rows(figures)}
  </tbody>
</table>

## Formula Leads That Pair With The Visual Topic

<table class="codex-status-table evidence-candidate-table">
  <thead>
    <tr><th>Candidate</th><th>OCR/PDF text</th><th>Source section</th><th>Routes</th></tr>
  </thead>
  <tbody>
{formula_rows(formulas)}
  </tbody>
</table>

## Editorial Use

This gallery is meant for discovery, not final citation. The strongest current source distribution is: {esc(source_summary)}. Promote a diagram or formula only after the scan, page label, exact caption, and mathematical notation are checked.
"""


def index_page(topic_summaries: list[dict[str, Any]]) -> str:
    cards = []
    for item in topic_summaries:
        cards.append(
            f"""<a href="{BASE_URL}/diagrams/visual-topic-galleries/{item['id']}/">
  <strong>{esc(item['title'])}</strong>
  <span>{esc(item['description'], 150)}</span>
  <small>{item['original_crop_count']} original crops - {item['visual_count']} guide visuals - {item['figure_count']} figure leads - {item['formula_count']} formula leads</small>
</a>"""
        )
    return f"""---
title: Visual Topic Galleries
description: Topic-level visual routes through Steinmetz diagrams, figure candidates, and formula maps.
---

{GENERATED_NOTE}

The visual topic galleries are the bridge between casual visual discovery and the archive's rigorous evidence system. Each route collects modern guide diagrams, figure candidates, source maps, workbench links, and formula leads around a major Steinmetz research theme.

<div class="source-text-warning" data-layer="source">
  <strong>Use rule:</strong> browse here to find a path, then cite from the source text, scans, and verification queues. Modern guide diagrams are explanatory reconstructions.
</div>

<div class="reading-route-index visual-topic-index">
{chr(10).join(cards)}
</div>
"""


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    visual_index = load_json(root / "processed" / "recreated_visual_index.json", {})
    figure_atlas = load_json(root / "processed" / "figure_candidate_atlas.json", {})
    equation_atlas = load_json(root / "processed" / "equation_atlas.json", {})
    source_catalog = load_json(root / "sources" / "source_catalog.json", [])
    source_titles = {
        str(source.get("source_id")): str(source.get("title") or source.get("source_id"))
        for source in source_catalog
        if isinstance(source, dict) and source.get("source_id")
    }

    visual_records = list(visual_index.get("records") or [])
    figure_records = list(figure_atlas.get("candidate_records") or [])
    formula_records = list(equation_atlas.get("records") or [])
    crop_records = original_crop_records(root, source_titles)

    output_root = root / "site" / "src" / "content" / "docs" / "diagrams" / "visual-topic-galleries"
    summaries = []
    payload_topics = []
    for topic in TOPICS:
        topic_visuals = [record for record in visual_records if matches(record, topic)]
        topic_crops = [record for record in crop_records if matches(record, topic)]
        topic_figures = [record for record in figure_records if matches(record, topic)]
        topic_formulas = sorted(
            [record for record in formula_records if matches(record, topic)],
            key=lambda item: -int(item.get("quality_score") or 0),
        )
        write_text(output_root / f"{topic['id']}.mdx", topic_page(topic, topic_visuals, topic_crops, topic_figures, topic_formulas))
        summaries.append(
            {
                "id": topic["id"],
                "title": topic["title"],
                "description": topic["description"],
                "original_crop_count": len(topic_crops),
                "visual_count": len(topic_visuals),
                "figure_count": len(topic_figures),
                "formula_count": len(topic_formulas),
            }
        )
        payload_topics.append(
            {
                **summaries[-1],
                "sources": topic["sources"],
                "concepts": topic["concepts"],
                "keywords": topic["keywords"],
                "links": {
                    "page": f"{BASE_URL}/diagrams/visual-topic-galleries/{topic['id']}/",
                    "diagram_archive": f"{BASE_URL}/diagrams/",
                    "figure_atlas": f"{BASE_URL}/diagrams/figure-candidate-atlas/",
                    "equation_atlas": f"{BASE_URL}/mathematics/equation-atlas/",
                },
            }
        )

    write_text(output_root / "index.mdx", index_page(summaries))
    payload = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Visual topic galleries are discovery routes over source, figure, visual, and formula candidate layers.",
        "topic_count": len(payload_topics),
        "topics": payload_topics,
    }
    write_json(root / "processed" / "visual_topic_galleries.json", payload)
    write_json(root / "site" / "public" / "data" / "visual_topic_galleries.json", payload)
    print(f"Generated {len(payload_topics)} visual topic galleries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
