#!/usr/bin/env python3
"""Generate source-keyed modern visual aids for the Steinmetz archive.

These SVGs are not documentary figures. They are modern guide diagrams that
make source themes easier to navigate while the original figure-crop work
continues through the verification queue.
"""

from __future__ import annotations

import json
import shutil
from datetime import date
from pathlib import Path
from typing import Any


BASE_URL = ""
GENERATED_NOTE = "{/* Generated by pipeline/scripts/generate_recreated_visuals.py. Do not edit by hand. */}"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def svg_shell(title: str, subtitle: str, body: str) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 720" role="img" aria-labelledby="title desc">
  <title id="title">{title}</title>
  <desc id="desc">{subtitle}</desc>
  <style>
    .bg {{ fill: #fbfaf6; }}
    .panel {{ fill: #f1ecdf; stroke: #263231; stroke-width: 2; }}
    .ink {{ fill: #1d2727; font-family: Georgia, 'Times New Roman', serif; }}
    .small {{ font-size: 24px; }}
    .label {{ font-size: 30px; font-weight: 700; }}
    .title {{ font-size: 42px; font-weight: 700; }}
    .muted {{ fill: #596661; }}
    .gold {{ stroke: #c69b39; fill: none; }}
    .green {{ stroke: #2f6d63; fill: none; }}
    .plum {{ stroke: #6c4d85; fill: none; }}
    .red {{ stroke: #a24b3d; fill: none; }}
    .bluefill {{ fill: #dbe8ef; stroke: #456a78; }}
    .goldfill {{ fill: #f2dfad; stroke: #9b7728; }}
    .greenfill {{ fill: #d9e8df; stroke: #2f6d63; }}
    .plumfill {{ fill: #e7dcef; stroke: #6c4d85; }}
    .line {{ stroke-width: 5; stroke-linecap: round; stroke-linejoin: round; }}
    .thin {{ stroke-width: 2.5; stroke-linecap: round; stroke-linejoin: round; }}
  </style>
  <rect class="bg" width="1200" height="720"/>
  <text class="ink title" x="56" y="64">{title}</text>
  <text class="ink small muted" x="56" y="104">{subtitle}</text>
  {body}
</svg>
"""


def visual_records() -> list[dict[str, Any]]:
    return [
        {
            "id": "rotating-magnetic-field",
            "title": "Rotating Magnetic Field From Quadrature Fluxes",
            "subtitle": "Modern reading aid for induction-machine field language in AC and Theoretical Elements sources.",
            "file": "rotating-magnetic-field.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theoretical-elements-electrical-engineering",
                "theory-calculation-electric-apparatus",
            ],
            "concepts": ["symbolic-method", "magnetism", "phase", "induction-motor"],
            "body": """
  <circle cx="340" cy="365" r="190" class="panel"/>
  <line x1="150" y1="365" x2="530" y2="365" class="thin muted" stroke="#596661"/>
  <line x1="340" y1="175" x2="340" y2="555" class="thin muted" stroke="#596661"/>
  <path d="M340 365 L500 365" class="green line"/>
  <path d="M340 365 L340 215" class="plum line"/>
  <path d="M340 365 L460 245" class="gold line"/>
  <path d="M498 260 A170 170 0 0 1 505 455" class="red thin"/>
  <text class="ink label" x="535" y="370">flux A</text>
  <text class="ink label" x="255" y="175">flux B</text>
  <text class="ink label" x="470" y="225">resultant</text>
  <rect x="690" y="205" width="330" height="80" rx="8" class="greenfill"/>
  <rect x="750" y="320" width="330" height="80" rx="8" class="plumfill"/>
  <rect x="810" y="435" width="330" height="80" rx="8" class="goldfill"/>
  <text class="ink label" x="718" y="255">space quadrature</text>
  <text class="ink label" x="778" y="370">time quadrature</text>
  <text class="ink label" x="838" y="485">rotating field</text>
""",
        },
        {
            "id": "distributed-constants-line",
            "title": "Distributed Constants Of A Transmission Line",
            "subtitle": "Modern reading aid for line capacity, inductance, leakage, waves, and transients.",
            "file": "distributed-constants-line.svg",
            "sources": [
                "theory-calculation-transient-electric-phenomena-oscillations",
                "theory-calculation-alternating-current-phenomena-1900",
                "theory-calculation-electric-circuits",
            ],
            "concepts": ["distributed-constants", "capacity", "inductance", "waves"],
            "body": """
  <line x1="90" y1="250" x2="1110" y2="250" class="green line"/>
  <line x1="90" y1="470" x2="1110" y2="470" class="green line"/>
  <path d="M180 250 q20 35 40 0 t40 0 t40 0" class="gold line"/>
  <path d="M520 250 q20 35 40 0 t40 0 t40 0" class="gold line"/>
  <path d="M860 250 q20 35 40 0 t40 0 t40 0" class="gold line"/>
  <line x1="330" y1="250" x2="330" y2="470" class="plum thin"/>
  <line x1="350" y1="250" x2="350" y2="470" class="plum thin"/>
  <line x1="690" y1="250" x2="690" y2="470" class="plum thin"/>
  <line x1="710" y1="250" x2="710" y2="470" class="plum thin"/>
  <path d="M105 160 C220 110 315 210 430 160 S640 110 750 160 S950 210 1095 160" class="red line"/>
  <polygon points="1088,160 1040,140 1046,185" fill="#a24b3d"/>
  <text class="ink label" x="170" y="330">L dx</text>
  <text class="ink label" x="305" y="545">C dx</text>
  <text class="ink label" x="515" y="330">R dx</text>
  <text class="ink label" x="665" y="545">G dx</text>
  <text class="ink label" x="780" y="130">traveling disturbance</text>
""",
        },
        {
            "id": "surge-impulse-reflection",
            "title": "Impulse Surge And Reflection",
            "subtitle": "Modern reading aid for lightning, impulses, discharges, and traveling waves.",
            "file": "surge-impulse-reflection.svg",
            "sources": [
                "elementary-lectures-electric-discharges-waves-impulses",
                "electric-discharges-waves-impulses-1914",
                "general-lectures-electrical-engineering",
            ],
            "concepts": ["lightning-surges", "impulse-current", "traveling-wave"],
            "body": """
  <line x1="90" y1="420" x2="1100" y2="420" class="green line"/>
  <rect x="1010" y="270" width="42" height="250" class="panel"/>
  <path d="M120 420 C180 418 205 416 230 360 C252 305 275 420 330 420 C390 420 430 420 500 420" class="red line"/>
  <polygon points="510,420 465,400 465,440" fill="#a24b3d"/>
  <path d="M990 420 C930 418 905 416 880 360 C858 305 835 420 780 420 C720 420 680 420 610 420" class="plum line"/>
  <polygon points="600,420 645,400 645,440" fill="#6c4d85"/>
  <path d="M185 570 h680" class="thin muted" stroke="#596661"/>
  <text class="ink label" x="150" y="330">incident impulse</text>
  <text class="ink label" x="650" y="330">reflected impulse</text>
  <text class="ink label" x="970" y="250">terminal</text>
  <text class="ink small muted" x="185" y="620">Polarity and magnitude depend on terminal condition and line constants.</text>
""",
        },
        {
            "id": "dielectric-magnetic-energy-storage",
            "title": "Magnetic And Dielectric Energy Storage",
            "subtitle": "Modern reading aid for Steinmetz's paired magnetic-field and dielectric-field language.",
            "file": "dielectric-magnetic-energy-storage.svg",
            "sources": [
                "theoretical-elements-electrical-engineering",
                "elementary-lectures-electric-discharges-waves-impulses",
                "electric-discharges-waves-impulses-1914",
            ],
            "concepts": ["dielectric-field", "magnetic-field", "energy-storage"],
            "body": """
  <rect x="135" y="220" width="150" height="300" class="goldfill"/>
  <rect x="455" y="220" width="150" height="300" class="goldfill"/>
  <line x1="300" y1="270" x2="440" y2="270" class="plum line"/>
  <line x1="300" y1="350" x2="440" y2="350" class="plum line"/>
  <line x1="300" y1="430" x2="440" y2="430" class="plum line"/>
  <polygon points="438,270 405,252 405,288" fill="#6c4d85"/>
  <polygon points="438,350 405,332 405,368" fill="#6c4d85"/>
  <polygon points="438,430 405,412 405,448" fill="#6c4d85"/>
  <path d="M790 270 q45 -70 90 0 t90 0" class="green line"/>
  <path d="M790 360 q45 -70 90 0 t90 0" class="green line"/>
  <path d="M790 450 q45 -70 90 0 t90 0" class="green line"/>
  <circle cx="880" cy="360" r="165" class="panel"/>
  <text class="ink label" x="180" y="570">dielectric field</text>
  <text class="ink label" x="802" y="570">magnetic field</text>
  <text class="ink small muted" x="245" y="630">capacity varies with voltage when dielectric strength is approached</text>
""",
        },
        {
            "id": "admittance-plane",
            "title": "Admittance Plane",
            "subtitle": "Modern reading aid for conductance, susceptance, and reciprocal impedance.",
            "file": "admittance-plane.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theoretical-elements-electrical-engineering",
            ],
            "concepts": ["admittance", "conductance", "susceptance", "symbolic-method"],
            "body": """
  <line x1="200" y1="560" x2="980" y2="560" class="thin muted" stroke="#596661"/>
  <line x1="260" y1="620" x2="260" y2="160" class="thin muted" stroke="#596661"/>
  <path d="M260 560 L790 310" class="green line"/>
  <path d="M260 560 L790 560" class="gold line"/>
  <path d="M790 560 L790 310" class="plum line"/>
  <path d="M350 560 A110 110 0 0 0 330 510" class="red thin"/>
  <text class="ink label" x="820" y="316">Y = g - jb</text>
  <text class="ink label" x="530" y="600">conductance g</text>
  <text class="ink label" x="815" y="450">susceptance b</text>
  <text class="ink small muted" x="320" y="700">Admittance is the reciprocal view: current response per applied voltage.</text>
""",
        },
        {
            "id": "harmonic-wave-shape",
            "title": "Equivalent Sine Waves And Harmonics",
            "subtitle": "Modern reading aid for wave-shape analysis and higher harmonics.",
            "file": "harmonic-wave-shape.svg",
            "sources": [
                "general-lectures-electrical-engineering",
                "theoretical-elements-electrical-engineering",
                "engineering-mathematics",
            ],
            "concepts": ["harmonics", "wave-shape", "fourier-analysis"],
            "body": """
  <path d="M95 360 C170 230 245 230 320 360 S470 490 545 360 S695 230 770 360 S920 490 1095 360" class="green line"/>
  <path d="M95 360 C122 255 150 255 177 360 S232 465 260 360 S315 255 342 360 S397 465 425 360 S480 255 507 360 S562 465 590 360 S645 255 672 360 S727 465 755 360 S810 255 837 360 S892 465 920 360 S1030 465 1095 360" class="plum thin"/>
  <path d="M95 360 C160 190 235 280 320 360 S470 520 545 360 S690 190 770 360 S930 520 1095 360" class="red line"/>
  <text class="ink label" x="105" y="170">fundamental</text>
  <text class="ink label" x="105" y="220">third harmonic</text>
  <text class="ink label" x="105" y="270">resultant wave</text>
  <line x1="370" y1="160" x2="450" y2="160" class="green line"/>
  <line x1="370" y1="210" x2="450" y2="210" class="plum thin"/>
  <line x1="370" y1="260" x2="450" y2="260" class="red line"/>
""",
        },
        {
            "id": "hysteresis-loss-law",
            "title": "Hysteresis Loss Law",
            "subtitle": "Modern reading aid for the Steinmetz law and magnetic energy loss per cycle.",
            "file": "hysteresis-loss-law.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theoretical-elements-electrical-engineering",
                "engineering-mathematics",
            ],
            "concepts": ["hysteresis", "magnetic-loss", "effective-resistance"],
            "body": """
  <line x1="190" y1="560" x2="560" y2="560" class="thin muted" stroke="#596661"/>
  <line x1="375" y1="650" x2="375" y2="185" class="thin muted" stroke="#596661"/>
  <path d="M240 520 C160 365 245 215 380 240 C545 270 570 500 420 520 C330 532 292 505 240 520 Z" fill="#e7dcef" stroke="#6c4d85" stroke-width="5"/>
  <text class="ink label" x="575" y="305">area = energy lost</text>
  <text class="ink label" x="585" y="365">per magnetic cycle</text>
  <rect x="640" y="420" width="430" height="110" rx="8" class="goldfill"/>
  <text class="ink label" x="675" y="490">P_h proportional to f B^1.6</text>
  <text class="ink small muted" x="210" y="690">Scan verification still required for exact constants and unit conventions.</text>
""",
        },
        {
            "id": "synchronous-reactor-power-flow",
            "title": "Reactors And Synchronizing Power",
            "subtitle": "Modern reading aid for the Commonwealth Edison report and system-stability mathematics.",
            "file": "synchronous-reactor-power-flow.svg",
            "sources": ["commonwealth-edison-generating-system-trouble", "theory-calculation-electric-circuits"],
            "concepts": ["synchronizing-power", "power-limiting-reactors", "reactance"],
            "body": """
  <circle cx="230" cy="350" r="110" class="greenfill"/>
  <circle cx="970" cy="350" r="110" class="greenfill"/>
  <text class="ink label" x="186" y="360">G1</text>
  <text class="ink label" x="926" y="360">G2</text>
  <path d="M340 350 H500 q25 -45 50 0 t50 0 t50 0 t50 0 H860" class="gold line"/>
  <path d="M500 250 C620 170 735 210 815 285" class="plum line"/>
  <polygon points="820,290 772,278 800,245" fill="#6c4d85"/>
  <text class="ink label" x="520" y="420">reactor / tie reactance</text>
  <text class="ink label" x="520" y="230">synchronizing current</text>
  <text class="ink small muted" x="410" y="610">Phase displacement drives power exchange; reactance limits current and stabilizes operation.</text>
""",
        },
        {
            "id": "field-energy-relativity-boundary",
            "title": "Field Of Energy Boundary",
            "subtitle": "Modern reading aid for Steinmetz's field language in Relativity and Space.",
            "file": "field-energy-relativity-boundary.svg",
            "sources": ["four-lectures-relativity-space", "theoretical-elements-electrical-engineering"],
            "concepts": ["field-language", "ether", "relativity", "energy-field"],
            "body": """
  <rect x="120" y="240" width="300" height="210" rx="10" class="plumfill"/>
  <rect x="780" y="240" width="300" height="210" rx="10" class="greenfill"/>
  <path d="M450 345 H745" class="gold line"/>
  <polygon points="750,345 702,322 702,368" fill="#c69b39"/>
  <text class="ink label" x="162" y="325">action at</text>
  <text class="ink label" x="162" y="370">a distance</text>
  <text class="ink label" x="830" y="325">field of</text>
  <text class="ink label" x="830" y="370">energy</text>
  <text class="ink small muted" x="260" y="555">Keep three layers separate: Steinmetz wording, modern field theory, later ether-field interpretation.</text>
""",
        },
        {
            "id": "engineering-number-plane",
            "title": "Engineering Number Plane",
            "subtitle": "Modern reading aid for number, direction, and symbolic calculation in Engineering Mathematics.",
            "file": "engineering-number-plane.svg",
            "sources": ["engineering-mathematics", "theory-calculation-alternating-current-phenomena"],
            "concepts": ["complex-quantities", "number", "symbolic-method"],
            "body": """
  <line x1="170" y1="360" x2="1030" y2="360" class="thin muted" stroke="#596661"/>
  <line x1="600" y1="620" x2="600" y2="140" class="thin muted" stroke="#596661"/>
  <path d="M600 360 L860 230" class="green line"/>
  <path d="M600 360 L860 360" class="gold line"/>
  <path d="M860 360 L860 230" class="plum line"/>
  <text class="ink label" x="885" y="236">a + jb</text>
  <text class="ink label" x="805" y="410">real</text>
  <text class="ink label" x="880" y="305">imaginary</text>
  <text class="ink label" x="175" y="345">negative</text>
  <text class="ink label" x="880" y="345">positive</text>
  <text class="ink small muted" x="255" y="665">Steinmetz treats number as directed quantity before it becomes AC operator language.</text>
""",
        },
    ]


def supplemental_visual_records() -> list[dict[str, Any]]:
    """Register older hand-built guide diagrams in the generated visual system.

    These SVGs were already published before the generated visual index existed.
    Keeping them here prevents downstream source visual maps and concept bridges
    from undercounting the real visual surface area of the site.
    """

    return [
        {
            "id": "spectrum-of-radiation",
            "title": "Spectrum Of Radiation",
            "subtitle": "Modern navigation guide for Steinmetz's electric-wave, visible-light, ultraviolet, and X-ray spectrum bridge.",
            "file": "spectrum-of-radiation.svg",
            "sources": ["radiation-light-and-illumination"],
            "concepts": ["radiation", "electric-waves", "frequency", "spectrum", "ether"],
        },
        {
            "id": "ac-symbolic-method-redraw-sheet",
            "title": "AC Symbolic Method Redraw Sheet",
            "subtitle": "Modern redraw sheet for rectangular components, resultant addition, and quarter-period j rotation.",
            "file": "ac-symbolic-method-redraw-sheet.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theory-calculation-alternating-current-phenomena-1897",
                "theory-calculation-alternating-current-phenomena-1900",
                "engineering-mathematics",
            ],
            "concepts": ["symbolic-method", "complex-quantities", "phasor", "operator-j"],
        },
        {
            "id": "transient-condenser-response-redraw-sheet",
            "title": "Transient Condenser Response Redraw Sheet",
            "subtitle": "Modern redraw sheet for logarithmic charge, critical damping, oscillatory charge, and decrement.",
            "file": "transient-condenser-response-redraw-sheet.svg",
            "sources": [
                "theory-calculation-transient-electric-phenomena-oscillations",
                "elementary-lectures-electric-discharges-waves-impulses",
                "electric-discharges-waves-impulses-1914",
            ],
            "concepts": ["transient-phenomena", "oscillation-damping", "capacity", "condenser"],
        },
        {
            "id": "phasor-symbolic-method",
            "title": "Phasor And Symbolic Method",
            "subtitle": "Modern reading aid for vector and complex-number representation of alternating quantities.",
            "file": "phasor-symbolic-method.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theory-calculation-alternating-current-phenomena-1897",
                "theory-calculation-alternating-current-phenomena-1900",
                "engineering-mathematics",
            ],
            "concepts": ["symbolic-method", "complex-quantities", "phase", "phasor"],
        },
        {
            "id": "transient-decay-oscillation",
            "title": "Transient Decay And Oscillation",
            "subtitle": "Modern guide for permanent terms, temporary terms, decay, and oscillatory readjustment.",
            "file": "transient-decay-oscillation.svg",
            "sources": [
                "theory-calculation-transient-electric-phenomena-oscillations",
                "elementary-lectures-electric-discharges-waves-impulses",
                "electric-discharges-waves-impulses-1914",
            ],
            "concepts": ["transient-phenomena", "oscillation-damping", "damping", "stored-energy"],
        },
        {
            "id": "hysteresis-loop",
            "title": "Hysteresis Loop",
            "subtitle": "Modern guide for magnetic lag, loop area, and energy loss per cycle.",
            "file": "hysteresis-loop.svg",
            "sources": [
                "theoretical-elements-electrical-engineering",
                "theory-calculation-alternating-current-phenomena",
                "theory-calculation-electric-apparatus",
                "engineering-mathematics",
            ],
            "concepts": ["hysteresis", "magnetism", "magnetic-loss", "effective-resistance"],
        },
        {
            "id": "field-wave-line",
            "title": "Field Wave Line",
            "subtitle": "Modern reading aid for distributed constants, standing waves, traveling waves, and surge propagation.",
            "file": "field-wave-line.svg",
            "sources": [
                "theory-calculation-transient-electric-phenomena-oscillations",
                "elementary-lectures-electric-discharges-waves-impulses",
                "electric-discharges-waves-impulses-1914",
                "theory-calculation-electric-circuits",
            ],
            "concepts": ["electric-waves", "distributed-constants", "traveling-wave", "lightning-surges"],
        },
        {
            "id": "impedance-reactance-triangle",
            "title": "Impedance And Reactance Triangle",
            "subtitle": "Modern guide for resistance, reactance, impedance, phase angle, and symbolic quantities.",
            "file": "impedance-reactance-triangle.svg",
            "sources": [
                "theory-calculation-alternating-current-phenomena",
                "theory-calculation-alternating-current-phenomena-1897",
                "theory-calculation-alternating-current-phenomena-1900",
                "theory-calculation-electric-circuits",
            ],
            "concepts": ["impedance", "reactance", "power-factor", "symbolic-method"],
        },
        {
            "id": "illumination-inverse-square",
            "title": "Illumination Inverse-Square Geometry",
            "subtitle": "Modern guide for the practical bridge from radiation to visual illumination and light distribution.",
            "file": "illumination-inverse-square.svg",
            "sources": ["radiation-light-and-illumination"],
            "concepts": ["illumination", "radiation", "light-flux", "inverse-square"],
        },
        {
            "id": "commonwealth-edison-system-reactor-map",
            "title": "Commonwealth Edison System Reactor Map",
            "subtitle": "Modern reading aid for station sections, power-limiting reactors, tie cables, and synchronism.",
            "file": "commonwealth-edison-system-reactor-map.svg",
            "sources": ["commonwealth-edison-generating-system-trouble", "theory-calculation-electric-circuits"],
            "concepts": ["power-limiting-reactors", "synchronizing-power", "reactance", "power-systems"],
        },
    ]


def build_index_page(records: list[dict[str, Any]]) -> str:
    cards = []
    for record in records:
        public_url = f"{BASE_URL}/diagrams/{record['file']}"
        source_links = " ".join(
            f'<a href="{BASE_URL}/book-coverage/{source}/">{source}</a>'
            for source in record["sources"][:3]
        )
        cards.append(
            f"""<div class="codex-visual-card">
  <img src="{public_url}" alt="{record['title']}" />
  <div>
    <strong>{record['title']}</strong>
    <p>{record['subtitle']}</p>
    <p class="visual-source-links">{source_links}</p>
  </div>
</div>"""
        )
    return f"""---
title: Recreated Visual Index
description: Modern guide diagrams keyed to Steinmetz source themes.
---

{GENERATED_NOTE}

These diagrams are modern explanatory aids. They are not original Steinmetz figures and should never be used as evidence for a historical claim without the linked source text and scan.

<div class="source-text-warning" data-layer="diagram-reconstruction">
  <strong>Layer rule:</strong> original scan crops, modern redraws, and interpretive annotations remain separate. This page contains modern redraws only.
</div>

<div class="codex-signal">
  <div><strong>{len(records)}</strong><p>generated modern guide diagrams in this index.</p></div>
  <div><strong>{len({source for record in records for source in record["sources"]})}</strong><p>source families represented by visual routes.</p></div>
  <div><strong>{len({concept for record in records for concept in record["concepts"]})}</strong><p>concept tags linked to visual reading.</p></div>
</div>

<div class="source-matrix">
  <a href="{BASE_URL}/diagrams/">Back to Diagram Archive<span>Original crops, visual routes, and verification rules.</span></a>
  <a href="{BASE_URL}/diagrams/figure-candidate-atlas/">Figure Candidate Atlas<span>OCR/PDF-text figure references from the corpus.</span></a>
  <a href="{BASE_URL}/mathematics/equation-atlas/">Equation Atlas<span>Formula candidates that pair with these visual guides.</span></a>
</div>

## Generated Modern Visual Aids

<div class="codex-visual-grid">
{chr(10).join(cards)}
</div>
"""


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    source_dir = root / "diagrams" / "recreated"
    public_dir = root / "site" / "public" / "diagrams"
    records = visual_records() + supplemental_visual_records()
    enriched = []
    for record in records:
        output_path = source_dir / record["file"]
        public_path = public_dir / record["file"]
        if "body" in record:
            svg = svg_shell(record["title"], record["subtitle"], record["body"])
            write_text(output_path, svg)
        elif not output_path.exists() and public_path.exists():
            output_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(public_path, output_path)
        public_path.parent.mkdir(parents=True, exist_ok=True)
        if output_path.exists():
            shutil.copyfile(output_path, public_path)
        enriched.append(
            {
                "id": record["id"],
                "title": record["title"],
                "subtitle": record["subtitle"],
                "file": record["file"],
                "source_path": str(output_path.relative_to(root)).replace("\\", "/") if output_path.exists() else None,
                "public_path": f"/diagrams/{record['file']}",
                "public_url": f"{BASE_URL}/diagrams/{record['file']}",
                "sources": record["sources"],
                "concepts": record["concepts"],
                "status": "modern-recreated-guide-diagram",
                "quality_note": "Generated modern reading aid; not an original Steinmetz figure.",
            }
        )

    payload = {
        "generated_at": date.today().isoformat(),
        "quality_note": "Modern guide diagrams are explanatory reconstructions, not historical figure evidence.",
        "total_records": len(enriched),
        "records": enriched,
    }
    write_json(root / "processed" / "recreated_visual_index.json", payload)
    write_json(root / "site" / "public" / "data" / "recreated_visual_index.json", payload)
    write_text(
        root / "site" / "src" / "content" / "docs" / "diagrams" / "recreated-visual-index.mdx",
        build_index_page(enriched),
    )
    print(f"Generated {len(enriched)} recreated visual aids.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
